<?php
/** 13 Sep 2026 post. Loaded after pages-sept12.php so the blog index and this article win. */
return [
    'blog' => [
        'slug' => 'blog',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Blog',
        'title' => 'Shehanly Blog - Privacy-First Tools, Security & Everyday Workflows',
        'h1' => 'The Shehanly blog',
        'description' => 'Practical guides on using free online tools without leaking data, converting documents safely, generating strong passwords and working faster with developer utilities.',
        'keywords' => 'shehanly blog, private online tools, free developer tools guides, password security, pdf converter safety, jwt decoder, disposable email, base64 encode decode, ai text summarizer, ai code explainer, client side tools',
        'intro' => 'Short, practical articles from the builder of Shehanly. No fluff. Each post solves one problem and points you at the free tool that does the work.',
        'body' => [
            ['h2' => 'Latest posts'],
            'New writing ships here first. Every article is written to rank, to teach, and to send you back into a tool you can actually use.',
            ['link' => ['href' => '/client-file-workflow-guide', 'text' => 'How to process a client file online without leaking it (13 Sep 2026)']],
            ['link' => ['href' => '/browser-only-tools-guide', 'text' => 'Which Shehanly tools stay in your browser, and which ones do not (12 Sep 2026)']],
            ['link' => ['href' => '/code-explainer-guide', 'text' => 'How to explain code online without leaking your source (11 Sep 2026)']],
            ['link' => ['href' => '/text-summarizer-guide', 'text' => 'How to summarize an article online without creating an account (10 Sep 2026)']],
            ['link' => ['href' => '/word-counter-guide', 'text' => 'How to count words and reading time without uploading your draft (9 Sep 2026)']],
            ['link' => ['href' => '/barcode-generator-guide', 'text' => 'How to generate a barcode without uploading your product data (8 Sep 2026)']],
            ['link' => ['href' => '/ip-dns-lookup-guide', 'text' => 'How to look up DNS and IP data without leaking the domain you are investigating (7 Sep 2026)']],
            ['link' => ['href' => '/url-encoder-guide', 'text' => 'How to URL encode and decode without leaking the query string (6 Sep 2026)']],
            ['link' => ['href' => '/base64-guide', 'text' => 'How to encode and decode Base64 without uploading the payload (5 Sep 2026)']],
            ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'How to convert Word to PDF online without leaking the document (4 Sep 2026)']],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'How to format and validate JSON without sending the payload (3 Sep 2026)']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'How to generate MD5 and SHA-256 hashes without uploading the file (2 Sep 2026)']],
            ['link' => ['href' => '/qr-code-guide', 'text' => 'How to generate a QR code without uploading your data (1 Sep 2026)']],
            ['link' => ['href' => '/temp-mail-guide', 'text' => 'How to use a disposable email without leaking your real inbox (31 Aug 2026)']],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'How to decode a JWT in your browser without leaking the token (30 Aug 2026)']],
            ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How to convert a PDF to Word online without leaking the file (29 Aug 2026)']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'How to generate a strong password in your browser (27 Aug 2026)']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data (26 Aug 2026)']],
            ['link' => ['href' => '/education-guides', 'text' => 'Education guides: Excel, Word, PowerPoint and defensive security literacy']],
            'Want a topic covered next? Use the Contact page and say exactly what you were trying to do when a random tool site made you hesitate.',
        ],
        'faq' => [
            ['How often is the blog updated?', 'New posts go up when there is a real problem worth solving, not on a fake daily calendar.'],
            ['Are these posts sales pages?', 'No. The tools stay free. The writing exists to teach and to earn search traffic the honest way.'],
        ],
    ],
    'client-file-workflow-guide' => [
        'slug' => 'client-file-workflow-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Client File Workflow',
        'published' => '2026-09-13',
        'title' => 'How to Process a Client File Online Without Leaking It (2026)',
        'h1' => 'How to process a client file online without leaking it',
        'description' => 'A 2026 freelancer workflow for client files: hash first, count locally, convert only through a proxy, never paste secrets into AI, and prove each step in DevTools. No account required.',
        'keywords' => 'process client file privately, freelancer document workflow 2026, convert client docx without leak, hash file before send, private online tools for freelancers, shehanly',
        'intro' => 'A client file is not a demo PDF. It has a name, a price, a clause, sometimes a passport scan someone should never have uploaded. The usual stack is five random websites and a hope. This page is the shorter stack: stay in the tab until a job honestly needs a server, then use a proxy that does not keep an account history.',
        'body' => [
            'Last updated: 13 September 2026. Written for freelancers, agencies, students and anyone who just received a .docx and is about to drop it into the first converter Google served.',
            ['h2' => 'The job is a pipeline, not a website'],
            'Most leaks are not hackers. They are extra tabs. Count on site A. Convert on site B. Summarize on site C. Generate a QR on site D. Each tab is another copy of the file you did not mean to make.',
            'Treat the file as a pipeline with four stations. Only one station is allowed to leave the machine.',
            ['h2' => 'Station 1: fingerprint the file before you touch it'],
            'Hash the original the moment it lands. SHA-256 is enough. You now have a fingerprint of what the client sent, before any tool rewrites a font or strips a comment.',
            'Do this in the tab. Uploading a contract so a website can print 64 hex characters is how the contract leaves.',
            ['link' => ['href' => '/hash-generator', 'text' => 'Open the browser hash generator']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'How to hash a file without uploading it']],
            ['h2' => 'Station 2: count and inspect without a post'],
            'Need a word count, a reading time, or a sanity check that the brief is 800 words not 8,000? That is a local job. Paste into a counter that never posts the draft.',
            'If the file is JSON from an API, format it locally too. Pretty-print is not a reason to ship a payload that still has tokens in it.',
            ['link' => ['href' => '/word-counter', 'text' => 'Open the word and reading time counter']],
            ['link' => ['href' => '/json-formatter', 'text' => 'Open the JSON formatter']],
            ['h2' => 'Station 3: convert only when the page must freeze'],
            'Word to PDF and PDF to Word cannot honestly finish in a tab. They need a document engine. That is one of the six Shehanly jobs that travel through a PHP proxy on this domain.',
            'The rule is still simple. The browser talks only to shehanly.com. The vendor key stays on the server. There is no account and no share link of last week conversions. The engine still sees the bytes for the length of the request. Do not convert a passport or a payroll sheet on any public box.',
            ['ul' => [
                'Accept or reject tracked changes before you freeze a PDF. The converter will print whatever is on the page.',
                'Prefer DOCX over legacy DOC.',
                'Stay under the 20 MB cap. Compress images in Word first.',
                'Open the PDF once. Check page count and the table that always jumps.',
                'Hash the output if you need to prove what you sent.',
            ]],
            ['link' => ['href' => '/word-to-pdf', 'text' => 'Open Word to PDF']],
            ['link' => ['href' => '/pdf-to-word', 'text' => 'Open PDF to Word']],
            ['link' => ['href' => '/browser-only-tools-guide', 'text' => 'See which tools stay in the tab and which do not']],
            ['h2' => 'Station 4: share a pointer, not another copy'],
            'If the client needs a link on a printed page, generate the QR in the browser. The URL stays in the canvas. Product SKUs belong in the barcode tool the same way.',
            'If the file itself needs a lock later, generate the password in the tab. Do not use a generator that emails you the result.',
            ['link' => ['href' => '/qr-generator', 'text' => 'Open the QR generator']],
            ['link' => ['href' => '/barcode-generator', 'text' => 'Open the barcode generator']],
            ['link' => ['href' => '/password-generator', 'text' => 'Open the password generator']],
            ['h2' => 'What never belongs in the AI boxes'],
            'The summarizer and the code explainer go through /api/ai.php. The PHP layer holds the key and caps the body. The model provider still sees the paste.',
            ['ul' => [
                'A public blog post is fine in the summarizer.',
                'A client brief with pricing is not.',
                'A function with YOUR_TOKEN placeholders is fine in the explainer.',
                'The same function with a live Stripe key is not.',
                'Strip names, amounts and secrets first. If that leaves nothing useful, do the work on your machine.',
            ]],
            ['link' => ['href' => '/text-summarizer', 'text' => 'Open the text summarizer']],
            ['link' => ['href' => '/code-explainer', 'text' => 'Open the code explainer']],
            ['h2' => 'A 90-second run when the email arrives'],
            ['ul' => [
                'Download the attachment. Do not open it inside the webmail preview if you can avoid it.',
                'Hash the file. Save the SHA-256 next to the filename.',
                'If you only need a count, paste into the word counter. Close the tab.',
                'If you need a frozen PDF, convert through the proxy. Open the result. Hash the PDF.',
                'If you need a printed URL, generate the QR locally.',
                'Do not create a disposable inbox as the password-reset address for a client account you care about. When the address dies, recovery dies with it.',
            ]],
            ['h2' => 'How to prove each station in DevTools'],
            ['ul' => [
                'Open the tool. DevTools. Network. Filter Fetch/XHR.',
                'Hash, count, format, QR, barcode, password: no POST of your payload.',
                'Convert or AI: a POST to /api/convert.php or /api/ai.php on this host. Not to a random SaaS hostname from the browser.',
                'If the request leaves for a third-party host from the tab, close it. That is not this pattern.',
            ]],
            'Badges are cheap. The Network tab is not.',
            ['h2' => 'The errors that create a second copy'],
            ['ul' => [
                'Dropping the live file into three converters because the first one felt slow.',
                'Pasting the brief into an AI box to rewrite the intro.',
                'Emailing yourself the PDF from the converter so you have a backup in Gmail.',
                'Using a share link the site generated. That link is a public copy with a guessable path.',
                'Hashing after you converted and calling that the original fingerprint. Hash before and after if you need both.',
            ]],
            ['h2' => 'Pair this workflow with the rest of the writing'],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
            ['link' => ['href' => '/browser-only-tools-guide', 'text' => 'The map of browser-only versus proxied tools']],
            ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'Convert Word to PDF without an account']],
            ['link' => ['href' => '/word-counter-guide', 'text' => 'Count words without uploading the draft']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'Generate a strong password in the browser']],
            ['h2' => 'Why this post sits on the blog'],
            'People do not search for a philosophy of privacy. They search because a file landed and the next click is a converter they have never heard of. The useful page is a pipeline: fingerprint, inspect, convert only if you must, share a pointer, keep AI away from the live brief. Then the tools. That is the Shehanly pattern. Rank for the job. Teach the risk. Finish the job.',
            ['link' => ['href' => '/', 'text' => 'Open the full tool list']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Do I have to upload a client file to use Shehanly?', 'No. Nine tools never leave the tab. Conversion and AI are the exceptions, and they still only talk to this domain from the browser.'],
            ['When is a proxy acceptable?', 'When the job cannot finish locally: Word and PDF layout, live DNS, disposable mail, model inference. Hashing, counting, QR, barcodes, JSON, JWT, Base64 and passwords are not those jobs.'],
            ['Should I summarize a client brief with the AI tool?', 'Not the live brief. Redact names, prices and secrets first. If the remainder is useless, write on your machine.'],
            ['How do I prove the file I sent matches the file I received?', 'Hash the original on arrival. Hash the PDF you send. Keep both digests next to the filenames. Do the hashing in the tab.'],
            ['Do I need an account?', 'No.'],
        ],
    ],
];
