<?php
/** 20 Sep 2026 post. Loaded after pages-sept19.php so the blog index and this article win. */
return [
    'blog' => [
        'slug' => 'blog',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Blog',
        'title' => 'Shehanly Blog - Privacy-First Tools, Security & Everyday Workflows',
        'h1' => 'The Shehanly blog',
        'description' => 'Practical guides on using free online tools without leaking data, converting documents safely, generating strong passwords and working faster with developer utilities.',
        'keywords' => 'shehanly blog, private online tools, free developer tools guides, password security, pdf converter safety, jwt decoder, disposable email, base64 encode decode, paste audit, client side tools, clipboard hygiene',
        'intro' => 'Short, practical articles from the builder of Shehanly. No fluff. Each post solves one problem and points you at the free tool that does the work.',
        'body' => [
            ['h2' => 'Latest posts'],
            'New writing ships here first. Every article is written to rank, to teach, and to send you back into a tool you can actually use.',
            ['link' => ['href' => '/clipboard-hygiene-guide', 'text' => 'How to keep tokens and passwords out of clipboard history after you use a tool (20 Sep 2026)']],
            ['link' => ['href' => '/prove-client-side-tool-guide', 'text' => 'How to prove an online tool stayed in your browser before you paste (19 Sep 2026)']],
            ['link' => ['href' => '/paste-audit-guide', 'text' => 'How to audit what you paste into online tools before you hit submit (18 Sep 2026)']],
            ['link' => ['href' => '/wifi-qr-code-guide', 'text' => 'How to generate a Wi-Fi QR code without uploading the network password (17 Sep 2026)']],
            ['link' => ['href' => '/base64-is-not-encryption-guide', 'text' => 'Base64 is not encryption: how to decode a blob without leaking it (16 Sep 2026)']],
            ['link' => ['href' => '/verify-download-hash-guide', 'text' => 'How to verify a downloaded file with SHA-256 before you run it (15 Sep 2026)']],
            ['link' => ['href' => '/phishing-url-check-guide', 'text' => 'How to decode a suspicious URL without visiting it (14 Sep 2026)']],
            ['link' => ['href' => '/client-file-workflow-guide', 'text' => 'How to process a client file online without leaking it (13 Sep 2026)']],
            ['link' => ['href' => '/browser-only-tools-guide', 'text' => 'Which Shehanly tools stay in your browser, and which ones do not (12 Sep 2026)']],
            ['link' => ['href' => '/code-explainer-guide', 'text' => 'How to explain code online without leaking your source (11 Sep 2026)']],
            ['link' => ['href' => '/text-summarizer-guide', 'text' => 'How to summarize an article online without creating an account (10 Sep 2026)']],
            ['link' => ['href' => '/word-counter-guide', 'text' => 'How to count words and reading time without uploading your draft (9 Sep 2026)']],
            ['link' => ['href' => '/barcode-generator-guide', 'text' => 'How to generate a barcode without uploading your product data (8 Sep 2026)']],
            ['link' => ['href' => '/ip-dns-lookup-guide', 'text' => 'How to look up DNS and IP data without leaking the domain you are investigating (7 Sep 2026)']],
            ['link' => ['href' => '/url-encoder-guide', 'text' => 'How to URL encode and decode without leaking the query string (6 Sep 2026)']],
            ['link' => ['href' => '/base64-guide', 'text' => 'How to encode and decode Base64 without uploading the payload (5 Sep 2026)']],
            ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'How to convert Word to PDF online without leaking the document (4 Sep 2026)']],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'How to format and validate JSON without sending the payload (3 Sep 2026)']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'How to generate MD5 and SHA-256 hashes without uploading the file (2 Sep 2026)']],
            ['link' => ['href' => '/qr-code-guide', 'text' => 'How to generate a QR code without uploading your data (1 Sep 2026)']],
            ['link' => ['href' => '/temp-mail-guide', 'text' => 'How to use a disposable email without leaking your real inbox (31 Aug 2026)']],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'How to decode a JWT in your browser without leaking the token (30 Aug 2026)']],
            ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How to convert a PDF to Word online without leaking the file (29 Aug 2026)']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'How to generate a strong password in your browser (27 Aug 2026)']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data (26 Aug 2026)']],
            ['link' => ['href' => '/education-guides', 'text' => 'Education guides: Excel, Word, PowerPoint and defensive security literacy']],
            'Want a topic covered next? Use the Contact page and say exactly what you were trying to do when a random tool site made you hesitate.',
        ],
        'faq' => [
            ['How often is the blog updated?', 'New posts go up when there is a real problem worth solving, not on a fake daily calendar.'],
            ['Are these posts sales pages?', 'No. The tools stay free. The writing exists to teach and to earn search traffic the honest way.'],
        ],
    ],
    'clipboard-hygiene-guide' => [
        'slug' => 'clipboard-hygiene-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Clipboard Hygiene',
        'published' => '2026-09-20',
        'title' => 'How to Keep Tokens and Passwords Out of Clipboard History After You Use a Tool (2026)',
        'h1' => 'How to keep tokens and passwords out of clipboard history after you use a tool',
        'description' => 'A 2026 workflow for Windows, macOS, Linux and phones: decode a JWT or generate a password in the browser, copy the result once, then overwrite clipboard history so Win+V, clipboard managers and shared laptops do not keep the secret.',
        'keywords' => 'clear clipboard history password, windows clipboard history jwt, macos clipboard manager leak, overwrite clipboard after copy, win+v secrets, shehanly clipboard hygiene, jwt decoder clipboard, password generator clipboard',
        'intro' => 'The tool can stay in the tab and still lose the secret two seconds later. Copy is the leak. Windows clipboard history, macOS managers, phone keyboards and the next Slack paste all keep what you just decoded. This is the 60-second cleanup after the job.',
        'body' => [
            'Last updated: 20 September 2026. Written for developers, freelancers and anyone who copies a JWT, a generated password or a client email out of a browser tool. This is defensive hygiene on a machine you already control. It is not a guide to reading anyone else\'s clipboard.',
            ['h2' => 'The tool was never the last hop'],
            'Yesterday we proved the formatter stayed in the tab. The day before we stripped the paste. None of that matters if you copy the result and walk away. Copy writes the string into a buffer every app on the machine can read until something else overwrites it.',
            'Windows 10 and 11 keep a clipboard history behind Win+V. That list survives the tab. It can sync to other devices if you turned that setting on. A password manager overlay, a GIF picker, a screenshot tool with OCR, a laptop you borrowed in a cafe: they all see the last copy.',
            'The job is not "never copy". The job is copy once, use once, overwrite, close.',
            ['link' => ['href' => '/prove-client-side-tool-guide', 'text' => 'Prove the tool stayed in the tab first']],
            ['link' => ['href' => '/paste-audit-guide', 'text' => 'Audit the paste before you submit']],
            ['h2' => 'What actually sits in the clipboard'],
            'Anything you copy from a Shehanly result box is fair game for the next paste: a JWT payload, a generated password, a Base64 blob, a formatted JSON dump, a decoded URL, a hash, a Wi-Fi QR payload you also copied as text.',
            ['ul' => [
                'High risk: live JWT, password, passphrase, API token, session cookie, client email list.',
                'Medium risk: unique JSON from production, a contract paragraph, a domain you are investigating.',
                'Low risk: a dummy probe string, a public URL, a checksum of a public ISO.',
            ]],
            'If you would not pin it to a cafe noticeboard, treat the clipboard like a postcard. Assume the next app can read it.',
            ['h2' => 'The 60-second close-out'],
            ['ul' => [
                'Finish the job in the tool. Copy the result once. Paste it where it belongs: password manager, terminal, the field that needed it.',
                'Immediately copy a single space, or the word done. That overwrites the current clipboard slot.',
                'On Windows: press Win+V. Delete the secret entries from history. Or turn history off for the session.',
                'On macOS: if you run a clipboard manager, clear its stack. If you do not, copying a space is usually enough for the system pasteboard.',
                'On Linux: clear both CLIPBOARD and PRIMARY if your desktop uses the middle-click selection buffer.',
                'Close the tab. Do not leave the JWT sitting on screen for the next person who walks behind the chair.',
            ]],
            'Copying a space feels stupid. It is the whole control. The next paste in Slack becomes a space instead of the production token.',
            ['h2' => 'Windows: Win+V is the real log'],
            'Settings > System > Clipboard. Clipboard history is a switch. Cloud clipboard sync is a second switch. If you decode tokens on a work laptop, history should be off or emptied after the job. Sync should be off unless you like your JWT landing on the living-room PC.',
            ['ul' => [
                'Win+V opens the history. Hover an item, delete it. Clear all if the list is junk.',
                'Win+V also lets you pin items. Never pin a password. Pinned items survive Clear all on some builds. Unpin first.',
                'A remote desktop session can copy between machines. Treat that as two clipboards, not one.',
            ]],
            'None of this requires admin rights. You are deleting your own history.',
            ['h2' => 'macOS, Linux and the phone'],
            ['ul' => [
                'macOS: the system pasteboard holds one item. Third-party managers (Paste, Alfred, Raycast clipboards) hold dozens. Clear the manager, not just the current slot.',
                'Universal Clipboard / Continuity: a copy on the Mac can appear on the iPhone. If that is on, overwrite on the Mac and check the phone.',
                'Linux: xclip -selection clipboard; xclip -selection primary. Or wl-copy on Wayland. Middle-click paste is a second buffer people forget.',
                'Android and iOS: keyboard clipboards and "recent copies" are the leak. After you paste the password into the vault, copy a space in Notes, then delete that note.',
            ]],
            'Shared cafe PCs get a private window plus this cleanup. Then sign out. Do not save the result to Downloads on a machine you do not own.',
            ['link' => ['href' => '/client-file-workflow-guide', 'text' => 'How to process a client file on a machine you do not fully trust']],
            ['h2' => 'Generate here, store there, never park in chat'],
            'A password that lives in Slack for five minutes is a password that lives in Slack\'s backups. Generate it locally. Copy once. Paste into the vault. Overwrite. Do not paste it into a DM "so I remember".',
            ['link' => ['href' => '/password-generator', 'text' => 'Generate a password in the browser']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'How to generate a strong password in your browser']],
            'Same rule for tokens. Decode the JWT in the tab to read exp and aud. Copy only the claim you need, not the raw token, if a teammate only needed the expiry. Then overwrite.',
            ['link' => ['href' => '/jwt-decoder', 'text' => 'Decode a JWT in the browser']],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'How to decode a JWT without leaking the token']],
            ['h2' => 'What a tool site must never do'],
            ['ul' => [
                'It must not auto-copy the result to the clipboard without a click. Surprise copies are how tokens land in history you did not mean to write.',
                'It must not offer a "share this result" link that stores the payload.',
                'It must not keep a Recent copies list tied to an account.',
                'It must not read the clipboard on page load. A site that sniffs paste on arrival is not a tool. Close it.',
            ]],
            'Shehanly copies only when you click copy. That is the contract. Watch the button. If a page writes to the clipboard before you ask, leave.',
            ['h2' => 'A dummy drill you can run today'],
            ['ul' => [
                'Open the password generator. Generate a throwaway. Copy it.',
                'Press Win+V or open your manager. Confirm the throwaway is there.',
                'Copy a single space. Open the history again. Confirm the current slot is the space. Delete the throwaway entry.',
                'Paste into Notepad. You should get a space, not the password.',
            ]],
            'Do the drill once so the real token is not the first time you remember the steps.',
            ['link' => ['href' => '/password-generator', 'text' => 'Run the drill on the password generator']],
            ['h2' => 'Pair this with the rest of the stack'],
            ['link' => ['href' => '/prove-client-side-tool-guide', 'text' => 'Prove the site did not upload the paste']],
            ['link' => ['href' => '/paste-audit-guide', 'text' => 'Strip secrets before the paste']],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'Format JSON without sending the payload']],
            ['link' => ['href' => '/base64-is-not-encryption-guide', 'text' => 'Decode Base64 without treating it as encryption']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'Hash a file without uploading it']],
            ['h2' => 'Why this post sits next to the tools'],
            'People search jwt decoder and password generator because a job is blocked. The useful page does not end at the result box. It tells them the next paste is the leak, names Win+V and the phone keyboard, and then hands them a local tool so the secret never needed a third website. That is the Shehanly pattern. Rank for the task. Prove the path. Close the clipboard.',
            ['link' => ['href' => '/', 'text' => 'Open the 15 free tools']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Does closing the tab clear the clipboard?', 'No. The clipboard belongs to the operating system. Close the tab, then overwrite the buffer and delete history entries.'],
            ['Is Windows clipboard history on by default?', 'On modern Windows 11 installs, history is easy to enable and easy to forget. Press Win+V. If a list appears, treat it as a log and clean it after a secret copy.'],
            ['Can a website read my clipboard without a paste?', 'Some pages ask for clipboard permission. Deny it. Shehanly does not need it. A tool that reads the clipboard on load is a reason to leave.'],
            ['Should I copy a production JWT to test a decoder?', 'No. Use an expired test token. The clipboard drill works with a throwaway password from the generator.'],
            ['What if I already pasted the token into Slack?', 'Treat that channel as a copy of the secret. Rotate the token. Clearing the laptop clipboard does not unsay a chat message.'],
        ],
    ],
];
