<?php
/** 19 Sep 2026 post. Loaded after pages-sept18.php so the blog index and this article win. */
return [
    'blog' => [
        'slug' => 'blog',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Blog',
        'title' => 'Shehanly Blog - Privacy-First Tools, Security & Everyday Workflows',
        'h1' => 'The Shehanly blog',
        'description' => 'Practical guides on using free online tools without leaking data, converting documents safely, generating strong passwords and working faster with developer utilities.',
        'keywords' => 'shehanly blog, private online tools, free developer tools guides, password security, pdf converter safety, jwt decoder, disposable email, base64 encode decode, paste audit, client side tools, devtools network check',
        'intro' => 'Short, practical articles from the builder of Shehanly. No fluff. Each post solves one problem and points you at the free tool that does the work.',
        'body' => [
            ['h2' => 'Latest posts'],
            'New writing ships here first. Every article is written to rank, to teach, and to send you back into a tool you can actually use.',
            ['link' => ['href' => '/prove-client-side-tool-guide', 'text' => 'How to prove an online tool stayed in your browser before you paste (19 Sep 2026)']],
            ['link' => ['href' => '/paste-audit-guide', 'text' => 'How to audit what you paste into online tools before you hit submit (18 Sep 2026)']],
            ['link' => ['href' => '/wifi-qr-code-guide', 'text' => 'How to generate a Wi-Fi QR code without uploading the network password (17 Sep 2026)']],
            ['link' => ['href' => '/base64-is-not-encryption-guide', 'text' => 'Base64 is not encryption: how to decode a blob without leaking it (16 Sep 2026)']],
            ['link' => ['href' => '/verify-download-hash-guide', 'text' => 'How to verify a downloaded file with SHA-256 before you run it (15 Sep 2026)']],
            ['link' => ['href' => '/phishing-url-check-guide', 'text' => 'How to decode a suspicious URL without visiting it (14 Sep 2026)']],
            ['link' => ['href' => '/client-file-workflow-guide', 'text' => 'How to process a client file online without leaking it (13 Sep 2026)']],
            ['link' => ['href' => '/browser-only-tools-guide', 'text' => 'Which Shehanly tools stay in your browser, and which ones do not (12 Sep 2026)']],
            ['link' => ['href' => '/code-explainer-guide', 'text' => 'How to explain code online without leaking your source (11 Sep 2026)']],
            ['link' => ['href' => '/text-summarizer-guide', 'text' => 'How to summarize an article online without creating an account (10 Sep 2026)']],
            ['link' => ['href' => '/word-counter-guide', 'text' => 'How to count words and reading time without uploading your draft (9 Sep 2026)']],
            ['link' => ['href' => '/barcode-generator-guide', 'text' => 'How to generate a barcode without uploading your product data (8 Sep 2026)']],
            ['link' => ['href' => '/ip-dns-lookup-guide', 'text' => 'How to look up DNS and IP data without leaking the domain you are investigating (7 Sep 2026)']],
            ['link' => ['href' => '/url-encoder-guide', 'text' => 'How to URL encode and decode without leaking the query string (6 Sep 2026)']],
            ['link' => ['href' => '/base64-guide', 'text' => 'How to encode and decode Base64 without uploading the payload (5 Sep 2026)']],
            ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'How to convert Word to PDF online without leaking the document (4 Sep 2026)']],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'How to format and validate JSON without sending the payload (3 Sep 2026)']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'How to generate MD5 and SHA-256 hashes without uploading the file (2 Sep 2026)']],
            ['link' => ['href' => '/qr-code-guide', 'text' => 'How to generate a QR code without uploading your data (1 Sep 2026)']],
            ['link' => ['href' => '/temp-mail-guide', 'text' => 'How to use a disposable email without leaking your real inbox (31 Aug 2026)']],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'How to decode a JWT in your browser without leaking the token (30 Aug 2026)']],
            ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How to convert a PDF to Word online without leaking the file (29 Aug 2026)']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'How to generate a strong password in your browser (27 Aug 2026)']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data (26 Aug 2026)']],
            ['link' => ['href' => '/education-guides', 'text' => 'Education guides: Excel, Word, PowerPoint and defensive security literacy']],
            'Want a topic covered next? Use the Contact page and say exactly what you were trying to do when a random tool site made you hesitate.',
        ],
        'faq' => [
            ['How often is the blog updated?', 'New posts go up when there is a real problem worth solving, not on a fake daily calendar.'],
            ['Are these posts sales pages?', 'No. The tools stay free. The writing exists to teach and to earn search traffic the honest way.'],
        ],
    ],
    'prove-client-side-tool-guide' => [
        'slug' => 'prove-client-side-tool-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Prove Client-Side',
        'published' => '2026-09-19',
        'title' => 'How to Prove an Online Tool Stayed in Your Browser Before You Paste (2026)',
        'h1' => 'How to prove an online tool stayed in your browser before you paste',
        'description' => 'A 2026 DevTools checklist to verify a formatter, decoder or generator is actually client-side. Watch the Network tab, filter XHR and fetch, reject mystery POSTs, then paste. Works on Shehanly and every other tool site.',
        'keywords' => 'how to check if website uploads paste, chrome devtools network tab online tool, prove client side tool, jwt decoder privacy test, json formatter no upload proof, shehanly network check, browser only tools 2026',
        'intro' => 'Marketing copy says "runs in your browser". The Network tab tells the truth. This is the 45-second proof before a JWT, a JSON dump or a client PDF leaves the tab. Yesterday we audited the paste. Today we audit the site.',
        'body' => [
            'Last updated: 19 September 2026. Written for developers, freelancers and anyone who has been burned by a pretty landing page. This is defensive hygiene. It is not a guide to intercepting other people\'s traffic or bypassing anyone\'s auth.',
            ['h2' => 'Trust the panel, not the badge'],
            'A lock icon means TLS. It does not mean the textarea stayed local. A "no signup" badge means they have not asked for an email yet. It does not mean they skipped the POST.',
            'Nine Shehanly tools never leave the tab: Base64, hash generator, JSON formatter, URL encoder, JWT decoder, QR generator, barcode generator, word counter and password generator. Six jobs do leave on purpose through a PHP proxy: PDF to Word, Word to PDF, IP and DNS lookup, 10 minute email, text summarizer and code explainer. The difference is visible in DevTools in under a minute. That is the whole point of this page.',
            ['link' => ['href' => '/browser-only-tools-guide', 'text' => 'Which Shehanly tools stay in the tab, and which six do not']],
            ['link' => ['href' => '/paste-audit-guide', 'text' => 'Audit the paste itself before you hit submit']],
            ['h2' => 'What you are looking for'],
            'After you paste a dummy payload, the Network panel should show static assets: HTML, CSS, JS, fonts, a favicon. It should not show a request whose payload is your textarea.',
            ['ul' => [
                'Good: GET /assets/js/tools/json-formatter.js. Size matches a script, not your 200 KB dump.',
                'Bad: POST /api/format with {"json":"...your paste..."} in the request body.',
                'Also bad: POST to a third-party host you did not type. The tab talked to someone else.',
                'Grey area on Shehanly: POST /api/convert, /api/ai, /api/dns, /api/tempmail. Those six jobs are supposed to leave. Confirm the host is shehanly.com and the body is the stripped file you meant to send.',
            ]],
            'If you cannot name the request that carried your bytes, assume it left.',
            ['h2' => 'A 45-second proof in Chrome or Edge'],
            ['ul' => [
                'Open the tool. Type the hostname yourself. Bookmark it if you will reuse it.',
                'Press F12 or Ctrl+Shift+I. Click Network. Check Preserve log.',
                'Filter: Fetch/XHR. That hides fonts and images so a sneaky POST cannot hide in the noise.',
                'Paste a dummy string first. Not the real JWT. Not the client PDF. Use {"probe":true} or hello-probe.',
                'Trigger the action: Format, Decode, Generate, Convert.',
                'Watch the list. Zero XHR after the click means the job stayed in the tab.',
                'If a row appears, click it. Headers tab: confirm the host. Payload tab: confirm whether your dummy string is in the body.',
            ]],
            'Firefox is the same path: F12, Network, XHR filter. Safari: Develop menu, Show Web Inspector, Network. Enable the Develop menu in Safari settings first.',
            ['h2' => 'What a clean Shehanly check looks like'],
            'JSON formatter, JWT decoder, hash generator, Base64, URL encoder, QR, barcode, word counter, password generator: after the dummy paste you should see no new Fetch/XHR. The result appears in the same tab. That is the contract.',
            ['link' => ['href' => '/json-formatter', 'text' => 'Format JSON in the browser']],
            ['link' => ['href' => '/jwt-decoder', 'text' => 'Decode a JWT in the browser']],
            ['link' => ['href' => '/hash-generator', 'text' => 'Hash text or a file in the browser']],
            ['link' => ['href' => '/password-generator', 'text' => 'Generate a password in the browser']],
            'Converters and AI tools will show a POST to this domain. Read the path. /api/convert and /api/ai are expected. A POST to a random vendor hostname is not. Close the tab if the host is not the one you typed.',
            ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How the PDF to Word proxy is supposed to behave']],
            ['link' => ['href' => '/code-explainer-guide', 'text' => 'How the code explainer proxy is supposed to behave']],
            ['h2' => 'The tricks that still fool people'],
            ['ul' => [
                'Beacons and sendBeacon. Some pages wait until you close the tab, then POST the textarea. Leave Network open, tick Preserve log, close the tool tab from another window, watch the first tab\'s panel.',
                'WebSockets. Filter WS. A socket that opens on paste is a live upload with extra steps.',
                'Image pixels with query strings. A GET to track.example/pixel.gif?q=YOUR_PASTE is still an upload. Sort by name. Look at query strings.',
                'Service workers. They can cache a POST and replay it. In Chrome: Application > Service Workers. Unregister if you did not install one on purpose.',
                'Extensions. A grammar or coupon add-on can POST the field to its own backend. Test once in a clean profile with extensions off.',
            ]],
            'None of this requires reading someone else\'s traffic. You are inspecting the tab you opened, on the machine you already control.',
            ['h2' => 'A dummy payload that cannot hurt you'],
            'Never use a live token to test a site. Use a string you would pin to a cafe noticeboard.',
            ['ul' => [
                'JSON: {"probe":true,"note":"dummy"}',
                'JWT: a token from a local test user, already expired, already revoked. Not staging. Not prod.',
                'File: a one-page PDF that says dummy on it. Not the client contract.',
                'Password field: generate a throwaway in the local generator, then throw it away. Do not test with a vault password.',
            ]],
            'If the Network row contains that dummy string and the host is wrong, you just caught the leak without spending a real secret.',
            ['h2' => 'Shared laptops and cafe Wi-Fi'],
            'The proof still works on a machine you do not own. The extra steps are cleanup, not magic.',
            ['ul' => [
                'Use a private window so the next customer does not inherit your DevTools history.',
                'Run the dummy check first. Then paste the real, stripped payload.',
                'When the job is done: copy the result, close the tab, clear the clipboard. On Windows, copy a single space. On macOS, copy a space. Do not leave the JWT sitting in clipboard managers.',
                'Do not save the result to Downloads on a cafe PC. Email it to yourself from an account you already trust, or write it to a USB you brought.',
            ]],
            ['link' => ['href' => '/client-file-workflow-guide', 'text' => 'How to process a client file without leaking it']],
            ['h2' => 'Pair this with the rest of the stack'],
            ['link' => ['href' => '/paste-audit-guide', 'text' => 'Strip secrets before the paste']],
            ['link' => ['href' => '/phishing-url-check-guide', 'text' => 'Decode a suspicious URL without visiting it']],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'Decode a JWT without leaking the token']],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'Format JSON without sending the payload']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'Hash a file without uploading it']],
            ['h2' => 'Why this post sits next to the tools'],
            'People search jwt decoder and json formatter because a job is blocked. The useful page does not ask them to trust a sentence on a landing page. It shows the panel, names the request that would carry the paste, and then hands them a tool that either stays local or admits the proxy. That is the Shehanly pattern. Rank for the task. Prove the path. Finish the job.',
            ['link' => ['href' => '/', 'text' => 'Open the 15 free tools']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['How do I prove a Shehanly tool stayed in the tab?', 'Open DevTools, Network, filter Fetch/XHR, paste a dummy string, run the action. The nine browser tools should add no request. The six proxy tools should POST only to shehanly.com.'],
            ['What if I see a POST to another domain?', 'Close the tab. Do not paste the real payload. Type a hostname you already trust, or do the job on a machine that never needed a website.'],
            ['Does HTTPS mean my paste stayed local?', 'No. HTTPS only encrypts the trip. The destination can still be a logger. The Network host column is the proof.'],
            ['Can a browser extension leak the textarea?', 'Yes. Test once in a clean profile with extensions disabled if the paste is sensitive.'],
            ['Should I test with a real production token?', 'No. Use a dummy JSON object or an already-revoked test JWT. The probe only needs to be unique enough to spot in the request body.'],
        ],
    ],
];
