<?php
/** 14 Sep 2026 post. Loaded after pages-sept13.php so the blog index and this article win. */
return [
    'blog' => [
        'slug' => 'blog',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Blog',
        'title' => 'Shehanly Blog - Privacy-First Tools, Security & Everyday Workflows',
        'h1' => 'The Shehanly blog',
        'description' => 'Practical guides on using free online tools without leaking data, converting documents safely, generating strong passwords and working faster with developer utilities.',
        'keywords' => 'shehanly blog, private online tools, free developer tools guides, password security, pdf converter safety, jwt decoder, disposable email, base64 encode decode, ai text summarizer, ai code explainer, client side tools',
        'intro' => 'Short, practical articles from the builder of Shehanly. No fluff. Each post solves one problem and points you at the free tool that does the work.',
        'body' => [
            ['h2' => 'Latest posts'],
            'New writing ships here first. Every article is written to rank, to teach, and to send you back into a tool you can actually use.',
            ['link' => ['href' => '/phishing-url-check-guide', 'text' => 'How to decode a suspicious URL without visiting it (14 Sep 2026)']],
            ['link' => ['href' => '/client-file-workflow-guide', 'text' => 'How to process a client file online without leaking it (13 Sep 2026)']],
            ['link' => ['href' => '/browser-only-tools-guide', 'text' => 'Which Shehanly tools stay in your browser, and which ones do not (12 Sep 2026)']],
            ['link' => ['href' => '/code-explainer-guide', 'text' => 'How to explain code online without leaking your source (11 Sep 2026)']],
            ['link' => ['href' => '/text-summarizer-guide', 'text' => 'How to summarize an article online without creating an account (10 Sep 2026)']],
            ['link' => ['href' => '/word-counter-guide', 'text' => 'How to count words and reading time without uploading your draft (9 Sep 2026)']],
            ['link' => ['href' => '/barcode-generator-guide', 'text' => 'How to generate a barcode without uploading your product data (8 Sep 2026)']],
            ['link' => ['href' => '/ip-dns-lookup-guide', 'text' => 'How to look up DNS and IP data without leaking the domain you are investigating (7 Sep 2026)']],
            ['link' => ['href' => '/url-encoder-guide', 'text' => 'How to URL encode and decode without leaking the query string (6 Sep 2026)']],
            ['link' => ['href' => '/base64-guide', 'text' => 'How to encode and decode Base64 without uploading the payload (5 Sep 2026)']],
            ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'How to convert Word to PDF online without leaking the document (4 Sep 2026)']],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'How to format and validate JSON without sending the payload (3 Sep 2026)']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'How to generate MD5 and SHA-256 hashes without uploading the file (2 Sep 2026)']],
            ['link' => ['href' => '/qr-code-guide', 'text' => 'How to generate a QR code without uploading your data (1 Sep 2026)']],
            ['link' => ['href' => '/temp-mail-guide', 'text' => 'How to use a disposable email without leaking your real inbox (31 Aug 2026)']],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'How to decode a JWT in your browser without leaking the token (30 Aug 2026)']],
            ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How to convert a PDF to Word online without leaking the file (29 Aug 2026)']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'How to generate a strong password in your browser (27 Aug 2026)']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data (26 Aug 2026)']],
            ['link' => ['href' => '/education-guides', 'text' => 'Education guides: Excel, Word, PowerPoint and defensive security literacy']],
            'Want a topic covered next? Use the Contact page and say exactly what you were trying to do when a random tool site made you hesitate.',
        ],
        'faq' => [
            ['How often is the blog updated?', 'New posts go up when there is a real problem worth solving, not on a fake daily calendar.'],
            ['Are these posts sales pages?', 'No. The tools stay free. The writing exists to teach and to earn search traffic the honest way.'],
        ],
    ],
    'phishing-url-check-guide' => [
        'slug' => 'phishing-url-check-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Suspicious URL Check',
        'published' => '2026-09-14',
        'title' => 'How to Decode a Suspicious URL Without Visiting It (2026)',
        'h1' => 'How to decode a suspicious URL without visiting it',
        'description' => 'A 2026 defensive guide to inspecting a shady link: percent-decode the path, read every query parameter, check the real host versus a lookalike subdomain, and look up public DNS before you click. No account. No visit required.',
        'keywords' => 'decode suspicious url, check phishing link without clicking, url decode online, percent encoding phishing, inspect query string, dns lookup before click, shehanly',
        'intro' => 'A phishing link is usually not a mystery. It is a long percent-encoded string that looks like your bank until you decode it. Visiting it to see what happens is how the session cookie leaves. This page is the shorter path: decode in the tab, read the host, read the query, then look up public DNS if you still need a second opinion.',
        'body' => [
            'Last updated: 14 September 2026. Written for anyone who just got a Slack ping, an SMS, or a invoice email with a link that feels one character off. This is defensive literacy. It is not a how-to for impersonation or unauthorized access.',
            ['h2' => 'Do not visit the link to inspect the link'],
            'Hovering is not inspecting. Mobile clients hide the real host. Some shorteners bounce three times before the final page. Some pages only look wrong after JavaScript runs. The safe first move is to treat the URL as text.',
            'Copy the full address. Do not tap it. Do not preview it inside the mail client if you can avoid it. Paste it into a decoder that stays in the browser.',
            ['link' => ['href' => '/url-encoder', 'text' => 'Open the URL encoder and decoder']],
            ['link' => ['href' => '/url-encoder-guide', 'text' => 'How URL encoding works, without leaking the query string']],
            ['h2' => 'Step 1: percent-decode until it stops changing'],
            'Attackers wrap a real-looking path in encodeURIComponent so the human eye sees paypal or microsoft and misses the host. Decode once. If the result still contains %2F or %3A, decode again. Double encoding is a common hide.',
            ['ul' => [
                '%2F is a slash. %3A is a colon. %3F is a question mark. %3D is an equals sign. %26 is an ampersand.',
                'A plus sign in a query value is often a space from old form encoding. Toggle that option if the text still looks smashed together.',
                'Smart quotes and invisible Unicode can sit inside a host that looks identical to the real brand. If the decoded host has odd characters, stop.',
            ]],
            'You are done with this step when the string is readable ASCII and another decode pass does not change it.',
            ['h2' => 'Step 2: name the real host, not the path'],
            'People read left to right and trust the first brand word they see. Browsers trust the host. The host is the label between the scheme and the first single slash.',
            ['ul' => [
                'https://paypal.com.example-secure.net/login is not PayPal. The host is example-secure.net.',
                'https://example.com.paypal.account-verify.info is not PayPal. The registrable domain is account-verify.info.',
                'https://paypal.com@evil.example/ is an old userinfo trick. Everything before @ is not the host.',
                'A long path that contains login, invoice or reset-password does not make the host legitimate.',
            ]],
            'Write the host on a separate line. Compare it to the real site you intended, character by character. One swapped letter is enough.',
            ['h2' => 'Step 3: dump every query parameter'],
            'The decoder on this site splits the query into a table. Read each key. Phishing kits love tokens that look official: next, redirect, return_url, continue, dest, target.',
            ['ul' => [
                'If a parameter contains another full URL, decode that inner URL too. That is often the page they want you to think you are visiting.',
                'If a parameter looks like a JWT, decode the payload in the tab. Do not paste a live session token into a site that uploads.',
                'If a parameter is Base64, decode it locally. A padded string that starts with eyJ is usually a JWT header, not a document.',
            ]],
            ['link' => ['href' => '/jwt-decoder', 'text' => 'Open the browser JWT decoder']],
            ['link' => ['href' => '/base64', 'text' => 'Open the browser Base64 decoder']],
            ['h2' => 'Step 4: look up public DNS without leaking your intent twice'],
            'Once you have a clean hostname, a public DNS lookup tells you what the rest of the internet sees: A and AAAA addresses, MX, TXT, NS. A brand-new domain pointing at a random VPS is a signal. A domain with no MX that claims to be your bank mail portal is a signal.',
            'This lookup is one of the six Shehanly jobs that hits a server. The browser talks to this domain. The resolver runs in PHP. That is still a request about that hostname. Do not look up a name you are not willing to appear next to in a resolver log.',
            ['link' => ['href' => '/ip-dns-lookup', 'text' => 'Open the IP and DNS lookup']],
            ['link' => ['href' => '/ip-dns-lookup-guide', 'text' => 'How the DNS tool works, and what it does not log in the tab']],
            ['h2' => 'A 60-second workflow when the message arrives'],
            ['ul' => [
                'Long-press or right-click. Copy link. Do not open.',
                'Paste into the URL decoder on shehanly.com. Confirm the address bar.',
                'Decode until stable. Copy the host onto its own line.',
                'Compare the host to the real brand site you already trust. If they differ, delete the message.',
                'If the host matches and you still hesitate, check public DNS. Fresh registration plus a login path is enough to stop.',
                'Reset the password only from a URL you typed yourself, never from the email.',
            ]],
            ['link' => ['href' => '/url-encoder', 'text' => 'Decode the URL in your browser now']],
            ['h2' => 'What this page will not do'],
            ['ul' => [
                'It will not teach you to build a lookalike domain.',
                'It will not walk through kit setup, landing-page clones or credential capture.',
                'It will not ask you to paste a live password or a session cookie into any tool.',
                'It will not promise that a clean DNS record means the site is safe. Compromised real sites exist.',
            ]],
            'The job is to stop a click. After you stop the click, report the message in the product you use and move on.',
            ['h2' => 'The mistakes that still get people'],
            ['ul' => [
                'Trusting a padlock. TLS only proves the connection is encrypted to that host. It does not prove the host is the brand.',
                'Trusting a preview card. Scrapers follow redirects. You should not.',
                'Opening the link in a private window and calling that a sandbox. A private window still runs the page.',
                'Pasting the full URL, token included, into a random scanner that stores submissions.',
                'Using a disposable inbox as the recovery address for an account you care about. When the address dies, recovery dies.',
            ]],
            ['link' => ['href' => '/temp-mail-guide', 'text' => 'When a disposable inbox is the right tool, and when it is not']],
            ['h2' => 'Pair this check with the rest of the stack'],
            ['link' => ['href' => '/url-encoder', 'text' => 'Percent-decode the path and query']],
            ['link' => ['href' => '/ip-dns-lookup', 'text' => 'Look up A, AAAA, MX and TXT for the host']],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'Read a JWT payload without sending the token']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'Hash a downloaded file before you run it']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
            ['h2' => 'Why this post sits next to the tools'],
            'People search decode url or check suspicious link because a message already landed. The useful page names the host, dumps the query, and refuses to send them into the page that wants the click. Then it hands them a decoder that never uploads the string. That is the Shehanly pattern. Rank for the job. Teach the risk. Finish the job.',
            ['link' => ['href' => '/url-encoder', 'text' => 'Decode a URL in the tab']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Is it safe to paste a phishing URL into Shehanly?', 'The decoder runs in the browser and does not post the string. A DNS lookup of the hostname does leave this domain for a resolver. Decode first. Look up only the host you already isolated.'],
            ['Does a padlock mean the site is real?', 'No. A padlock means TLS to that host. Confirm the host independently.'],
            ['Should I open the link in Incognito to check it?', 'No. A private window still executes the page. Decode the text instead.'],
            ['What if the URL is a short link?', 'Do not follow it. If you cannot see the final host from the text you already have, treat it as untrusted and use a channel you typed yourself.'],
            ['Does this replace a password manager or MFA?', 'No. This stops a bad click. MFA and a unique password still matter after the click is gone.'],
        ],
    ],
];
