<?php
/** 15 Sep 2026 post. Loaded after pages-sept14.php so the blog index and this article win. */
return [
    'blog' => [
        'slug' => 'blog',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Blog',
        'title' => 'Shehanly Blog - Privacy-First Tools, Security & Everyday Workflows',
        'h1' => 'The Shehanly blog',
        'description' => 'Practical guides on using free online tools without leaking data, converting documents safely, generating strong passwords and working faster with developer utilities.',
        'keywords' => 'shehanly blog, private online tools, free developer tools guides, password security, pdf converter safety, jwt decoder, disposable email, base64 encode decode, ai text summarizer, ai code explainer, client side tools',
        'intro' => 'Short, practical articles from the builder of Shehanly. No fluff. Each post solves one problem and points you at the free tool that does the work.',
        'body' => [
            ['h2' => 'Latest posts'],
            'New writing ships here first. Every article is written to rank, to teach, and to send you back into a tool you can actually use.',
            ['link' => ['href' => '/verify-download-hash-guide', 'text' => 'How to verify a downloaded file with SHA-256 before you run it (15 Sep 2026)']],
            ['link' => ['href' => '/phishing-url-check-guide', 'text' => 'How to decode a suspicious URL without visiting it (14 Sep 2026)']],
            ['link' => ['href' => '/client-file-workflow-guide', 'text' => 'How to process a client file online without leaking it (13 Sep 2026)']],
            ['link' => ['href' => '/browser-only-tools-guide', 'text' => 'Which Shehanly tools stay in your browser, and which ones do not (12 Sep 2026)']],
            ['link' => ['href' => '/code-explainer-guide', 'text' => 'How to explain code online without leaking your source (11 Sep 2026)']],
            ['link' => ['href' => '/text-summarizer-guide', 'text' => 'How to summarize an article online without creating an account (10 Sep 2026)']],
            ['link' => ['href' => '/word-counter-guide', 'text' => 'How to count words and reading time without uploading your draft (9 Sep 2026)']],
            ['link' => ['href' => '/barcode-generator-guide', 'text' => 'How to generate a barcode without uploading your product data (8 Sep 2026)']],
            ['link' => ['href' => '/ip-dns-lookup-guide', 'text' => 'How to look up DNS and IP data without leaking the domain you are investigating (7 Sep 2026)']],
            ['link' => ['href' => '/url-encoder-guide', 'text' => 'How to URL encode and decode without leaking the query string (6 Sep 2026)']],
            ['link' => ['href' => '/base64-guide', 'text' => 'How to encode and decode Base64 without uploading the payload (5 Sep 2026)']],
            ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'How to convert Word to PDF online without leaking the document (4 Sep 2026)']],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'How to format and validate JSON without sending the payload (3 Sep 2026)']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'How to generate MD5 and SHA-256 hashes without uploading the file (2 Sep 2026)']],
            ['link' => ['href' => '/qr-code-guide', 'text' => 'How to generate a QR code without uploading your data (1 Sep 2026)']],
            ['link' => ['href' => '/temp-mail-guide', 'text' => 'How to use a disposable email without leaking your real inbox (31 Aug 2026)']],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'How to decode a JWT in your browser without leaking the token (30 Aug 2026)']],
            ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How to convert a PDF to Word online without leaking the file (29 Aug 2026)']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'How to generate a strong password in your browser (27 Aug 2026)']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data (26 Aug 2026)']],
            ['link' => ['href' => '/education-guides', 'text' => 'Education guides: Excel, Word, PowerPoint and defensive security literacy']],
            'Want a topic covered next? Use the Contact page and say exactly what you were trying to do when a random tool site made you hesitate.',
        ],
        'faq' => [
            ['How often is the blog updated?', 'New posts go up when there is a real problem worth solving, not on a fake daily calendar.'],
            ['Are these posts sales pages?', 'No. The tools stay free. The writing exists to teach and to earn search traffic the honest way.'],
        ],
    ],
    'verify-download-hash-guide' => [
        'slug' => 'verify-download-hash-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Verify a Download',
        'published' => '2026-09-15',
        'title' => 'How to Verify a Downloaded File with SHA-256 Before You Run It (2026)',
        'h1' => 'How to verify a downloaded file with SHA-256 before you run it',
        'description' => 'A 2026 defensive guide to checking a downloaded installer or archive against the publisher checksum. Hash the file in your browser with SHA-256, compare it character by character, and skip sites that want the upload. No account required.',
        'keywords' => 'verify download sha256, check file checksum online, sha-256 hash of file, compare publisher checksum, md5 vs sha256 download, hash file in browser, shehanly',
        'intro' => 'A download is not trustworthy because the button said official. It is trustworthy when the bytes on disk match the checksum the publisher posted on a page you already trust. This page is the short loop: get the published digest, hash the local file in the tab, compare, then decide.',
        'body' => [
            'Last updated: 15 September 2026. Written for anyone who just saved an installer, a zip, or a firmware image and is one double-click away from running it. This is defensive literacy. It is not a guide to packing malware, spoofing publishers, or cracking software.',
            ['h2' => 'The file on disk is the only file that matters'],
            'Browsers show a name. Chat apps show a preview. Neither is the bytes. A renamed invoice.pdf.exe still hashes as whatever it actually is. Hash the file you saved, not the filename you hoped for.',
            'Do this before you extract, mount, or run anything. A checksum after the first launch is a diary entry, not a gate.',
            ['link' => ['href' => '/hash-generator', 'text' => 'Open the browser hash generator']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'How the hash tool works, and why the file never uploads']],
            ['h2' => 'Step 1: copy the published checksum from a page you typed'],
            'The comparison value has to come from the vendor, not from the same zip you just pulled. Prefer a checksum block on the official download page, a release note, or a signed announcement on a domain you already use.',
            ['ul' => [
                'Type the vendor site yourself. Do not follow a checksum link that arrived in the same email as the file.',
                'Copy the full hex string. SHA-256 is 64 hex characters. SHA-512 is 128. MD5 is 32 and is only useful as a non-security fingerprint.',
                'Note the algorithm next to the string. Hashing with SHA-256 and comparing to an MD5 line is how people invent a false match.',
                'If the page only publishes SHA-1, treat that as a weak signal. Use it to catch a corrupt download, not to prove a publisher.',
            ]],
            'Write the published digest on its own line before you touch the tool. You need a source of truth that does not live inside the download.',
            ['h2' => 'Step 2: hash the saved file in the tab'],
            'The generator on this site reads the file with FileReader and hashes it with the Web Crypto API. The bytes stay in the tab. There is no upload, no account, and no history table of yesterday\'s installers.',
            ['ul' => [
                'Confirm the address bar is shehanly.com/hash-generator.',
                'Drop the file. Do not paste a path from a random cloud scanner.',
                'Read SHA-256 first. That is the digest most vendors publish in 2026.',
                'If the vendor published SHA-512, switch to that line instead of approximating.',
            ]],
            'Wait until the digest is stable. A large ISO takes a few seconds in the browser. That delay is cheaper than running the wrong binary.',
            ['link' => ['href' => '/hash-generator', 'text' => 'Hash the file without uploading it']],
            ['h2' => 'Step 3: compare every character, not the first eight'],
            'People glance at the start of a hash and call it close enough. Attackers count on that. Compare the full string.',
            ['ul' => [
                'Lowercase versus uppercase hex does not matter. a and A are the same nibble.',
                'Spaces and colons in pretty-printed digests do not matter. Strip them before you compare.',
                'A single different character is a different file. Stop. Do not run it.',
                'A match only proves the file equals the published digest. It does not prove the publisher is honest if you copied the digest from a forum post.',
            ]],
            'If they match and the digest came from the real vendor page, you have done the job this page exists for. Install from that local copy, not from a second download that skipped the check.',
            ['h2' => 'A 45-second workflow after the save dialog'],
            ['ul' => [
                'Leave the file in Downloads. Do not open it.',
                'Open the vendor page in a tab you typed. Copy the published SHA-256.',
                'Open the hash generator on shehanly.com. Confirm the URL.',
                'Drop the file. Wait for SHA-256.',
                'Compare the two strings in full. Mismatch: delete the file. Match from a trusted page: proceed.',
                'If there is no published checksum at all, treat the file as unverified. Use another channel or wait.',
            ]],
            ['link' => ['href' => '/hash-generator', 'text' => 'Hash the download in your browser now']],
            ['h2' => 'What a matching hash does not prove'],
            ['ul' => [
                'It does not prove the vendor is the brand you think it is. Confirm the host the same way you would confirm a login page.',
                'It does not prove the file is free of bugs. It proves the bytes match the digest you compared against.',
                'It does not replace signatures, SmartScreen, Gatekeeper, or a package manager that already verifies.',
                'It does not make MD5 a good choice for installers. Collisions exist. Prefer SHA-256 or SHA-512.',
            ]],
            ['link' => ['href' => '/phishing-url-check-guide', 'text' => 'Confirm the download host before you trust its checksum page']],
            ['h2' => 'The mistakes that still get people'],
            ['ul' => [
                'Hashing a file after running it. The damage window already opened.',
                'Uploading the installer to a public scanner that keeps samples. That is a different job, and it leaks the binary.',
                'Trusting a checksum printed inside the zip you are trying to verify. That is the file talking about itself.',
                'Comparing only SHA-1 because it is shorter. Short is not the point.',
                'Accepting a checksum from the same Telegram group that sent the zip.',
            ]],
            ['h2' => 'Pair this check with the rest of the stack'],
            ['link' => ['href' => '/hash-generator', 'text' => 'Generate MD5, SHA-1, SHA-256 and SHA-512 in the tab']],
            ['link' => ['href' => '/url-encoder', 'text' => 'Decode a download URL before you fetch it']],
            ['link' => ['href' => '/phishing-url-check-guide', 'text' => 'Read the real host on a suspicious link']],
            ['link' => ['href' => '/ip-dns-lookup-guide', 'text' => 'Look up public DNS for a vendor domain you just met']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
            ['h2' => 'Why this post sits next to the tools'],
            'People search verify sha256 download or check file checksum because a file is already sitting in Downloads. The useful page tells them to hash the local bytes, not to upload the installer to a stranger. Then it hands them a generator that never leaves the tab. That is the Shehanly pattern. Rank for the job. Teach the risk. Finish the job.',
            ['link' => ['href' => '/hash-generator', 'text' => 'Hash a file in the tab']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Does Shehanly upload my installer to hash it?', 'No. The hash generator reads the file in the browser with FileReader and Web Crypto. The file never posts to the server.'],
            ['Is a matching SHA-256 enough to run anything?', 'No. It only proves the file matches the digest you compared. The digest still has to come from a publisher page you trust.'],
            ['Should I use MD5 because it is shorter?', 'No. Use MD5 only as a quick integrity check for non-hostile corruption. Prefer SHA-256 or SHA-512 for installers.'],
            ['What if the vendor published no checksum?', 'Do not invent one. Use another official channel, a package manager that already verifies, or wait. Absence of a digest is information.'],
            ['Can I hash a file that is still downloading?', 'No. Wait until the browser marks the download complete. A partial file will never match.'],
        ],
    ],
];
