<?php
/** Extra blog posts merged after config/pages.php */
return [
         'blog' => [
             'slug' => 'blog',
             'category' => 'Guides',
             'type' => 'page',
             'nav' => 'Blog',
             'title' => 'Shehanly Blog - Privacy-First Tools, Security & Everyday Workflows',
             'h1' => 'The Shehanly blog',
             'description' => 'Practical guides on using free online tools without leaking data, converting documents safely, generating strong passwords and working faster with developer utilities.',
             'keywords' => 'shehanly blog, private online tools, free developer tools guides, password security, pdf converter safety, jwt decoder, disposable email, base64 encode decode',
             'intro' => 'Short, practical articles from the builder of Shehanly. No fluff. Each post solves one problem and points you at the free tool that does the work.',
             'body' => [
                 ['h2' => 'Latest posts'],
                 'New writing ships here first. Every article is written to rank, to teach, and to send you back into a tool you can actually use.',
                 ['link' => ['href' => '/base64-guide', 'text' => 'How to encode and decode Base64 without uploading the payload (5 Sep 2026)']],
                 ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'How to convert Word to PDF online without leaking the document (4 Sep 2026)']],
                 ['link' => ['href' => '/json-formatter-guide', 'text' => 'How to format and validate JSON without sending the payload (3 Sep 2026)']],
                 ['link' => ['href' => '/hash-generator-guide', 'text' => 'How to generate MD5 and SHA-256 hashes without uploading the file (2 Sep 2026)']],
                 ['link' => ['href' => '/qr-code-guide', 'text' => 'How to generate a QR code without uploading your data (1 Sep 2026)']],
                 ['link' => ['href' => '/temp-mail-guide', 'text' => 'How to use a disposable email without leaking your real inbox (31 Aug 2026)']],
                 ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'How to decode a JWT in your browser without leaking the token (30 Aug 2026)']],
                 ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How to convert a PDF to Word online without leaking the file (29 Aug 2026)']],
                 ['link' => ['href' => '/strong-password-guide', 'text' => 'How to generate a strong password in your browser (27 Aug 2026)']],
                 ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data (26 Aug 2026)']],
                 ['link' => ['href' => '/education-guides', 'text' => 'Education guides: Excel, Word, PowerPoint and defensive security literacy']],
                 'Want a topic covered next? Use the Contact page and say exactly what you were trying to do when a random tool site made you hesitate.'
             ],
             'faq' => [
                 ['How often is the blog updated?', 'New posts go up when there is a real problem worth solving, not on a fake daily calendar.'],
                 ['Are these posts sales pages?', 'No. The tools stay free. The writing exists to teach and to earn search traffic the honest way.'],
             ],
         ],
    'base64-guide' => [
        'slug' => 'base64-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Base64 Guide',
        'published' => '2026-09-05',
        'title' => 'How to Encode and Decode Base64 Without Uploading the Payload (2026)',
        'h1' => 'How to encode and decode Base64 without uploading the payload',
        'description' => 'A 2026 guide to Base64 encode and decode in the browser: why pasting a token into a random converter is a leak, how UTF-8 and URL-safe alphabets actually work, and a 30-second workflow that never leaves the tab.',
        'keywords' => 'base64 encode online, base64 decode no upload, url safe base64, utf-8 base64 converter, decode base64 locally, shehanly',
        'intro' => 'Base64 looks like noise until you remember what people paste into it: basic-auth headers, JWT segments, data URIs, API tokens wrapped for a config file. The moment a converter posts that string to print readable text, the secret is no longer only yours. This guide shows how to encode and decode in the tab, when to flip the URL-safe alphabet, and why Base64 is never encryption.',
        'body' => [
            'Last updated: 5 September 2026. Written for developers, pentesters, support engineers and anyone who just copied a long string out of a log and needs the original bytes without handing them to a stranger.',
            ['h2' => 'What Base64 actually does'],
            'Base64 turns raw bytes into 64 printable ASCII characters so the payload can sit in email, JSON, HTML or a query string without breaking the container. Every 3 bytes become 4 characters. Padding with = fills the last block. That is the whole trick.',
            'It is an encoding. Anyone can reverse it. There is no key. If the input was a password, the output is the same password wearing a costume. Treat a Base64 blob as sensitive as the bytes it hides.',
            ['h2' => 'Why most online Base64 sites are a leak'],
            'Search base64 decode and the first results look harmless. Paste, click Decode, copy. What they hide is the POST. A bearer token, a .pem wrapped as text, a customer export stuffed into a data URI is now a copy on a box you do not run.',
            'Some tools keep Recent strings. Some wrap the result in a share link. A unique token is identifying even after you close the tab. Support teams paste production headers into converters every day. That is how credentials leave the company without a ticket.',
            ['h2' => 'The safe pattern: encode in the tab'],
            'Shehanly encodes and decodes with TextEncoder, btoa and atob in the browser. UTF-8 is the default so Sinhala, Arabic and emoji survive the round trip. URL-safe mode swaps + and / for - and _ and drops padding so the value can sit in a query string. Nothing is posted. Watch Network while you paste a 200 KB dump. You should see static assets only.',
            ['link' => ['href' => '/base64', 'text' => 'Open the browser Base64 encoder']],
            ['h2' => 'A 30-second workflow when a log line looks like garbage'],
            ['ul' => [
                'Copy the raw string only. Do not copy surrounding JSON quotes unless they belong to the payload.',
                'Open the encoder on shehanly.com. Confirm the URL.',
                'Paste. If it looks like Base64 already, hit Decode. If it is plain text you need to wrap, hit Encode.',
                'Tick URL safe when the string must live in a query parameter or a filename.',
                'Copy the result and close the tab. The original paste never left the machine.',
            ]],
            ['link' => ['href' => '/base64', 'text' => 'Encode or decode locally now']],
            ['h2' => 'Standard versus URL-safe versus UTF-8'],
            ['ul' => [
                'Standard Base64: email attachments, HTTP basic auth, classic data URIs. Alphabet is A-Z a-z 0-9 + / with = padding.',
                'URL-safe Base64: JWT payloads, signed cookies, query values. Alphabet swaps + / for - _ and often drops padding.',
                'UTF-8: the character set of the original text. A Latin-1 decoder will mangle every non-English string and then blame Base64.',
            ]],
            'JWTs are three Base64URL segments joined by dots. Decode the middle segment in this tool if you only need the claims. Use the JWT decoder when you also want exp rendered as a local date.',
            ['h2' => 'The errors that waste an afternoon'],
            ['ul' => [
                'Missing padding. Some libraries strip =. Add them back until the length is a multiple of 4, or use a decoder that does it for you.',
                'Newlines from email. MIME Base64 wraps at 76 characters. Strip whitespace before you decode.',
                'Mixing alphabets. A URL-safe string fed to a strict + / decoder dies on the first hyphen.',
                'Calling it encryption. A junior ticket that says we Base64 the API key is a finding, not a control.',
                'Smart quotes and trailing spaces copied from Slack. They look invisible and break atob.',
            ]],
            'If decode prints garbage with black-diamond characters, you decoded the right Base64 into the wrong character set, or the source was binary and you asked for text. Download the bytes instead of forcing a string.',
            ['h2' => 'What a Base64 tool must never do'],
            ['ul' => [
                'It must not POST the textarea to print ASCII.',
                'It must not create a public /p/abc123 link of your last paste.',
                'It must not call the output encrypted.',
                'It must not phone home with a sample of strings for product analytics.',
                'It must not ask you to log in to copy the result.',
            ]],
            'A fast test: paste SGVsbG8=, open DevTools, watch Network. If a request carries the string, close the tab.',
            ['h2' => 'Pair it with the rest of the stack'],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'Decode a JWT in the browser without leaking the token']],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'Pretty-print the JSON you just unwrapped']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'Hash the original bytes without uploading them']],
            ['link' => ['href' => '/url-encoder', 'text' => 'Percent-encode the result if it still has to travel in a URL']],
            ['h2' => 'Why this post sits next to the tool'],
            'People search base64 decode because a string landed and they cannot read it. The honest page tells them the paste is often a secret, why the converter must stay in the tab, which alphabet to pick, and then hands them the tool. That is the Shehanly pattern: rank for the job, teach the risk, finish the job.',
            ['link' => ['href' => '/base64', 'text' => 'Encode and decode Base64 locally']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Is Base64 encryption?', 'No. It is a reversible encoding. Anyone with the string can recover the original bytes. Use a real cipher if the payload must stay secret.'],
            ['Does Shehanly upload my text?', 'No. Encode and decode run in the browser with TextEncoder and atob. Watch the Network tab if you want proof.'],
            ['Why does decode fail?', 'Wrong alphabet, missing padding, leftover whitespace, or a truncated string. Strip spaces, restore = until the length is a multiple of 4, then try again.'],
            ['When do I use URL-safe Base64?', 'When the value sits in a URL, a filename or a JWT. The standard + and / characters break those containers.'],
        ],
    ],
];
