<?php
/** Latest Shehanly blog posts merged by article.php via config/pages*.php */
return [
    'blog' => [
        'slug' => 'blog',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Blog',
        'title' => 'Shehanly Blog - Privacy-First Tools, Security & Everyday Workflows',
        'h1' => 'The Shehanly blog',
        'description' => 'Practical guides on using free online tools without leaking data, converting documents safely, generating strong passwords and working faster with developer utilities.',
        'keywords' => 'shehanly blog, private online tools, free developer tools guides, password security, pdf converter safety, jwt decoder, disposable email, base64 encode decode, ai text summarizer, ai code explainer',
        'intro' => 'Short, practical articles from the builder of Shehanly. No fluff. Each post solves one problem and points you at the free tool that does the work.',
        'body' => [
            ['h2' => 'Latest posts'],
            'New writing ships here first. Every article is written to rank, to teach, and to send you back into a tool you can actually use.',
            ['link' => ['href' => '/code-explainer-guide', 'text' => 'How to explain code online without leaking your source (11 Sep 2026)']],
            ['link' => ['href' => '/text-summarizer-guide', 'text' => 'How to summarize an article online without creating an account (10 Sep 2026)']],
            ['link' => ['href' => '/word-counter-guide', 'text' => 'How to count words and reading time without uploading your draft (9 Sep 2026)']],
            ['link' => ['href' => '/barcode-generator-guide', 'text' => 'How to generate a barcode without uploading your product data (8 Sep 2026)']],
            ['link' => ['href' => '/ip-dns-lookup-guide', 'text' => 'How to look up DNS and IP data without leaking the domain you are investigating (7 Sep 2026)']],
            ['link' => ['href' => '/url-encoder-guide', 'text' => 'How to URL encode and decode without leaking the query string (6 Sep 2026)']],
            ['link' => ['href' => '/base64-guide', 'text' => 'How to encode and decode Base64 without uploading the payload (5 Sep 2026)']],
            ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'How to convert Word to PDF online without leaking the document (4 Sep 2026)']],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'How to format and validate JSON without sending the payload (3 Sep 2026)']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'How to generate MD5 and SHA-256 hashes without uploading the file (2 Sep 2026)']],
            ['link' => ['href' => '/qr-code-guide', 'text' => 'How to generate a QR code without uploading your data (1 Sep 2026)']],
            ['link' => ['href' => '/temp-mail-guide', 'text' => 'How to use a disposable email without leaking your real inbox (31 Aug 2026)']],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'How to decode a JWT in your browser without leaking the token (30 Aug 2026)']],
            ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How to convert a PDF to Word online without leaking the file (29 Aug 2026)']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'How to generate a strong password in your browser (27 Aug 2026)']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data (26 Aug 2026)']],
            ['link' => ['href' => '/education-guides', 'text' => 'Education guides: Excel, Word, PowerPoint and defensive security literacy']],
            'Want a topic covered next? Use the Contact page and say exactly what you were trying to do when a random tool site made you hesitate.',
        ],
        'faq' => [
            ['How often is the blog updated?', 'New posts go up when there is a real problem worth solving, not on a fake daily calendar.'],
            ['Are these posts sales pages?', 'No. The tools stay free. The writing exists to teach and to earn search traffic the honest way.'],
        ],
    ],
    'code-explainer-guide' => [
        'slug' => 'code-explainer-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Code Explainer Guide',
        'published' => '2026-09-11',
        'title' => 'How to Explain Code Online Without Leaking Your Source (2026)',
        'h1' => 'How to explain code online without leaking your source',
        'description' => 'A 2026 guide to explaining a function, class, SQL query or shell script in plain English without creating an account: what a safe code explainer must never keep, how the Shehanly PHP proxy works, what never to paste, and a 60-second workflow.',
        'keywords' => 'ai code explainer no signup, explain code online free, understand code snippet, explain python javascript php sql, private code explainer 2026, shehanly',
        'intro' => 'A snippet looks small until you remember what lives next to it. An API key in a comment. A customer table name. The one-off script that still has production hostnames. The moment a random explainer asks you to sign in so it can save your history, that source is no longer only yours. This guide shows how to get a beginner walkthrough, a standard pass or an expert edge-case brief through a short-lived proxy, what a safe explainer must never do, and how to finish the job in under a minute.',
        'body' => [
            'Last updated: 11 September 2026. Written for juniors reading inherited code, seniors reviewing a pull request on a phone, students stuck on a lab, and anyone who just opened a 80-line function and needs the point before standup.',
            ['h2' => 'What a code explainer actually does'],
            'It turns a snippet into a map. Not a rewrite. Not a refactor. A walkthrough: what the code does, which inputs matter, where it can fail, and what you should check next.',
            'That job needs a language model. A browser cannot honestly pretend to run a frontier model locally and still return a useful expert brief in two seconds. Honesty beats a fake local badge.',
            ['h2' => 'Why most online explainers are a leak'],
            'Search explain this code and the first results look identical. Paste, wait, copy bullets. What they hide is the rest of the funnel: a forced signup, a history pane of every function you ever pasted, a share link that stays in their sitemap, or a training toggle that is on by default.',
            'Source is identifying even after you close the tab. Interns paste take-home tests. Founders paste billing webhooks. Support teams paste the one query that still has a real customer email in the WHERE clause. That is how unpublished work leaves the laptop without a breach ticket.',
            ['h2' => 'The honest pattern: proxy, do not pretend'],
            'Nine Shehanly tools never leave the tab. The code explainer is not one of them. The paste travels to /api/ai.php on this domain. The PHP proxy holds the provider key, rate-limits the IP, caps the body at 12,000 characters, and never exposes the key to JavaScript.',
            'The browser only talks to shehanly.com. You do not create an account. The proxy does not write the paste to a history table. The model provider still sees the text for the duration of that request. That is the real trade. Treat it like emailing a colleague the function, not like locking a vault.',
            ['link' => ['href' => '/code-explainer', 'text' => 'Open the code explainer']],
            ['h2' => 'A 60-second workflow when standup is in ten minutes'],
            ['ul' => [
                'Cut the snippet to the function, class, query or script you actually need explained. Drop lockfiles, generated clients and the 400-line comment block that is not the point.',
                'Strip secrets first. Replace API keys, tokens, production hostnames, real emails and customer IDs with obvious placeholders.',
                'Open the explainer on shehanly.com. Confirm the URL.',
                'Paste. Stay under 12,000 characters. That is roughly 3,000 words or a few hundred lines. Split a file if you are over.',
                'Pick a language: auto-detect for most work, or pin JavaScript, Python, PHP, Java, C#, C/C++, Go, Rust, SQL, Bash or Other when the snippet is short and ambiguous.',
                'Pick a depth: beginner when the reader is new to the language, standard for a PR review, expert when you need complexity, failure modes and edge cases.',
                'Copy the output into your notes or download the .md. Close the tab. Do not leave a second copy of the source on a random tool site.',
            ]],
            ['link' => ['href' => '/code-explainer', 'text' => 'Explain the snippet now']],
            ['h2' => 'What to paste and what to keep off the wire'],
            ['ul' => [
                'Safe enough for most work: public samples, your own functions, interview-style puzzles, queries you would already paste in Slack.',
                'Keep off the wire: production secrets, private keys, unreleased billing logic under NDA, customer PII inside a SQL dump, anything you would not email a contractor.',
                'Redact first: swap real hostnames for example.com, replace tokens with YOUR_TOKEN, drop the .env block that was sitting above the function.',
                'Language follows the source. Paste Sinhala comments or Arabic strings and the explanation should still describe the code, not invent a rewrite.',
            ]],
            'If you would not forward the raw paste to a contractor, do not paste it into an explainer. The proxy removes the account form. It does not remove physics.',
            ['h2' => 'The errors that waste an afternoon'],
            ['ul' => [
                'Pasting an entire repository dump, node_modules included, then blaming the model for a sloppy brief.',
                'Asking for an expert pass of a 6-line helper and treating invented Big-O claims as facts. The tool should not invent. Still read the output.',
                'Leaving a live JWT or database password in a comment and calling it a snippet.',
                'Pasting proprietary code from a client who forbids third-party processors. That is a contract problem, not a tooling problem.',
                'Feeding the same function five times because the first pass was beginner. Change the depth, do not hammer the rate limit.',
            ]],
            'If two passes disagree on what a line does, the snippet is incomplete or you pasted different text. Open the original file. The explanation is a map, not the compiler.',
            ['h2' => 'What a code explainer must never do'],
            ['ul' => [
                'It must not force an account to print a walkthrough.',
                'It must not keep a public /s/abc123 link of your last paste.',
                'It must not ship the provider key to the browser.',
                'It must not claim the model runs locally when the Network tab shows an API call.',
                'It must not train a public model on your paste as a hidden default.',
            ]],
            'A fast test: paste a dummy function, open DevTools, watch Network. You should see a POST to /api/ai.php on this host. If the request goes to a third-party hostname from the browser, close the tab.',
            ['h2' => 'Pair it with the rest of the stack'],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'Format the payload the function is parsing before you explain the parser']],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'Decode a JWT in the browser when the snippet is token handling']],
            ['link' => ['href' => '/text-summarizer-guide', 'text' => 'Summarize the README first when the file is long']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'Hash a file locally when you only needed a checksum, not an explanation']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
            ['h2' => 'Why this post sits next to the tool'],
            'People search explain this code because a review is soon and the function is dense. The honest page tells them the paste leaves the machine, why the key stays on the server, what never belongs in the box, and then hands them the tool. That is the Shehanly pattern: rank for the job, teach the risk, finish the job.',
            ['link' => ['href' => '/code-explainer', 'text' => 'Explain code without creating an account']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Does the explainer upload my code?', 'Yes, to shehanly.com only. The PHP proxy calls the model provider. The browser never sees the API key. Do not paste secrets you would not send to a processor.'],
            ['Do I need an account?', 'No. There is no signup and no history pane of old snippets.'],
            ['How long can the input be?', '12,000 characters per request. Cut the file to the function you actually need explained.'],
            ['Is my code stored?', 'The proxy does not log request bodies. The model provider has its own retention rules. Treat the paste as sent.'],
            ['Which depth should I pick?', 'Beginner when the reader is new to the language. Standard for most PR reviews. Expert when you need complexity, failure modes and edge cases.'],
        ],
    ],
    'text-summarizer-guide' => [
        'slug' => 'text-summarizer-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Text Summarizer Guide',
        'published' => '2026-09-10',
        'title' => 'How to Summarize an Article Online Without Creating an Account (2026)',
        'h1' => 'How to summarize an article online without creating an account',
        'description' => 'A 2026 guide to summarizing articles, reports and transcripts without signing up: why random AI summarizer sites keep the paste, how a PHP proxy should work, what never to paste, and a 45-second workflow that stays on shehanly.com.',
        'keywords' => 'ai text summarizer no signup, summarize article online free, tldr generator private, executive summary tool, article summarizer 2026, shehanly',
        'intro' => 'A long page looks harmless until you remember what is in it. A client brief. A draft that is not public. A transcript with real names. The moment a summarizer asks you to create an account so it can email you the bullets, the source is no longer only yours. This guide shows how to get a TL;DR, a bullet brief or an executive summary through a short-lived proxy, what a safe summarizer must never do, and how to finish the job in under a minute.',
        'body' => [
            'Last updated: 10 September 2026. Written for students, founders, analysts, YouTubers and anyone who just opened a 3,000-word tab and needs the point before the meeting starts.',
            ['h2' => 'What a summarizer actually does'],
            'It compresses a source into fewer words while keeping names, numbers and dates intact. The output is not a rewrite. It is a map: four to seven bullets, one tight paragraph, one sentence under 30 words, or an executive brief with impact, risk and a next step.',
            'That job needs a language model. A browser cannot honestly pretend to run a frontier model locally and still return a useful executive summary in two seconds. Honesty beats a fake local badge.',
            ['h2' => 'Why most online summarizers are a leak'],
            'Search summarize article and the first results look identical. Paste, wait, copy bullets. What they hide is the rest of the funnel: a forced signup, a history pane of everything you ever pasted, a share link that stays in their sitemap, or a training toggle that is on by default.',
            'A unique brief is identifying even after you close the tab. Students paste unpublished essays. Founders paste investor updates. Support teams paste tickets with customer emails still in the header. That is how unpublished work leaves the laptop without a breach ticket.',
            ['h2' => 'The honest pattern: proxy, do not pretend'],
            'Nine Shehanly tools never leave the tab. The text summarizer is not one of them. The paste travels to /api/ai.php on this domain. The PHP proxy holds the provider key, rate-limits the IP, caps the body at 12,000 characters, and never exposes the key to JavaScript.',
            'The browser only talks to shehanly.com. You do not create an account. The proxy does not write the paste to a history table. The model provider still sees the text for the duration of that request. That is the real trade. Treat it like emailing a colleague, not like locking a vault.',
            ['link' => ['href' => '/text-summarizer', 'text' => 'Open the text summarizer']],
            ['h2' => 'A 45-second workflow when the meeting is in ten minutes'],
            ['ul' => [
                'Strip what the model does not need. Drop email headers, comment threads, tracked-changes junk and any secret that is not required for the brief.',
                'Open the summarizer on shehanly.com. Confirm the URL.',
                'Paste. Stay under 12,000 characters. That is roughly 3,000 words. Cut the appendix if you are over.',
                'Pick a style: bullets for a scan, paragraph for a Slack paste, TL;DR for a subject line, executive for a founder update, ELI5 when the room is mixed.',
                'Pick a length: short when the slot is one slide, medium for most work, detailed when the source is dense and the reader will not open it.',
                'Copy the output into your notes. Close the tab. Do not build a second copy of the source on a random tool site.',
            ]],
            ['link' => ['href' => '/text-summarizer', 'text' => 'Summarize the page now']],
            ['h2' => 'What to paste and what to keep off the wire'],
            ['ul' => [
                'Safe enough for most work: public articles, your own drafts, meeting notes you would already email, transcripts you have the right to process.',
                'Keep off the wire: passwords, API keys, unreleased payroll, medical notes, a customer list, anything under NDA that forbids third-party processors.',
                'Redact first: replace real emails with a@example.com, strip account numbers, drop the attachment that was not the point.',
                'Language follows the source. Paste Sinhala or Arabic and the summary should come back in the same language.',
            ]],
            'If you would not forward the raw paste to a contractor, do not paste it into a summarizer. The proxy removes the account form. It does not remove physics.',
            ['h2' => 'The errors that waste an afternoon'],
            ['ul' => [
                'Pasting the whole PDF dump, ads and cookie banner included, then blaming the model for a sloppy brief.',
                'Asking for an executive summary of a source that has no numbers, then treating invented metrics as facts. The prompt on this tool says do not invent. Still read the output.',
                'Using TL;DR on a 40-page policy and expecting the one sentence to carry the exceptions.',
                'Summarizing a paywalled article you pasted from a pirate copy. That is not a tooling problem.',
                'Feeding the same source five times because the first pass was short. Change the style, do not hammer the rate limit.',
            ]],
            'If two passes disagree on a number, the source is ambiguous or you pasted different text. Open the original. The summary is a map, not the territory.',
            ['h2' => 'What a summarizer must never do'],
            ['ul' => [
                'It must not force an account to print four bullets.',
                'It must not keep a public /s/abc123 link of your last paste.',
                'It must not ship the provider key to the browser.',
                'It must not claim the model runs locally when the Network tab shows an API call.',
                'It must not train a public model on your paste as a hidden default.',
            ]],
            'A fast test: paste a dummy paragraph, open DevTools, watch Network. You should see a POST to /api/ai.php on this host. If the request goes to a third-party hostname from the browser, close the tab.',
            ['h2' => 'Pair it with the rest of the stack'],
            ['link' => ['href' => '/word-counter-guide', 'text' => 'Count the source and the summary before you hit a word limit']],
            ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'Freeze the brief to PDF without leaking the file']],
            ['link' => ['href' => '/code-explainer', 'text' => 'Explain a code snippet through the same proxy when the source is a function']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
            ['h2' => 'Why this post sits next to the tool'],
            'People search summarize article because a meeting is soon and the tab is long. The honest page tells them the paste leaves the machine, why the key stays on the server, what never belongs in the box, and then hands them the tool. That is the Shehanly pattern: rank for the job, teach the risk, finish the job.',
            ['link' => ['href' => '/text-summarizer', 'text' => 'Summarize an article without creating an account']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Does the summarizer upload my text?', 'Yes, to shehanly.com only. The PHP proxy calls the model provider. The browser never sees the API key. Do not paste secrets you would not send to a processor.'],
            ['Do I need an account?', 'No. There is no signup and no history pane of old pastes.'],
            ['How long can the input be?', '12,000 characters per request, about 3,000 words. Cut appendices first.'],
            ['Is my text stored?', 'The proxy does not log request bodies. The model provider has its own retention rules. Treat the paste as sent.'],
            ['Which style should I pick?', 'Bullets for a scan. Paragraph for Slack. TL;DR for a subject line. Executive when a founder needs impact, risk and a next step. ELI5 when the room is mixed.'],
        ],
    ],
];
