<?php
/** 17 Sep 2026 post. Loaded after pages-sept16.php so the blog index and this article win. */
return [
    'blog' => [
        'slug' => 'blog',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Blog',
        'title' => 'Shehanly Blog - Privacy-First Tools, Security & Everyday Workflows',
        'h1' => 'The Shehanly blog',
        'description' => 'Practical guides on using free online tools without leaking data, converting documents safely, generating strong passwords and working faster with developer utilities.',
        'keywords' => 'shehanly blog, private online tools, free developer tools guides, password security, pdf converter safety, jwt decoder, disposable email, base64 encode decode, wifi qr code, client side tools',
        'intro' => 'Short, practical articles from the builder of Shehanly. No fluff. Each post solves one problem and points you at the free tool that does the work.',
        'body' => [
            ['h2' => 'Latest posts'],
            'New writing ships here first. Every article is written to rank, to teach, and to send you back into a tool you can actually use.',
            ['link' => ['href' => '/wifi-qr-code-guide', 'text' => 'How to generate a Wi-Fi QR code without uploading the network password (17 Sep 2026)']],
            ['link' => ['href' => '/base64-is-not-encryption-guide', 'text' => 'Base64 is not encryption: how to decode a blob without leaking it (16 Sep 2026)']],
            ['link' => ['href' => '/verify-download-hash-guide', 'text' => 'How to verify a downloaded file with SHA-256 before you run it (15 Sep 2026)']],
            ['link' => ['href' => '/phishing-url-check-guide', 'text' => 'How to decode a suspicious URL without visiting it (14 Sep 2026)']],
            ['link' => ['href' => '/client-file-workflow-guide', 'text' => 'How to process a client file online without leaking it (13 Sep 2026)']],
            ['link' => ['href' => '/browser-only-tools-guide', 'text' => 'Which Shehanly tools stay in your browser, and which ones do not (12 Sep 2026)']],
            ['link' => ['href' => '/code-explainer-guide', 'text' => 'How to explain code online without leaking your source (11 Sep 2026)']],
            ['link' => ['href' => '/text-summarizer-guide', 'text' => 'How to summarize an article online without creating an account (10 Sep 2026)']],
            ['link' => ['href' => '/word-counter-guide', 'text' => 'How to count words and reading time without uploading your draft (9 Sep 2026)']],
            ['link' => ['href' => '/barcode-generator-guide', 'text' => 'How to generate a barcode without uploading your product data (8 Sep 2026)']],
            ['link' => ['href' => '/ip-dns-lookup-guide', 'text' => 'How to look up DNS and IP data without leaking the domain you are investigating (7 Sep 2026)']],
            ['link' => ['href' => '/url-encoder-guide', 'text' => 'How to URL encode and decode without leaking the query string (6 Sep 2026)']],
            ['link' => ['href' => '/base64-guide', 'text' => 'How to encode and decode Base64 without uploading the payload (5 Sep 2026)']],
            ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'How to convert Word to PDF online without leaking the document (4 Sep 2026)']],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'How to format and validate JSON without sending the payload (3 Sep 2026)']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'How to generate MD5 and SHA-256 hashes without uploading the file (2 Sep 2026)']],
            ['link' => ['href' => '/qr-code-guide', 'text' => 'How to generate a QR code without uploading your data (1 Sep 2026)']],
            ['link' => ['href' => '/temp-mail-guide', 'text' => 'How to use a disposable email without leaking your real inbox (31 Aug 2026)']],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'How to decode a JWT in your browser without leaking the token (30 Aug 2026)']],
            ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How to convert a PDF to Word online without leaking the file (29 Aug 2026)']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'How to generate a strong password in your browser (27 Aug 2026)']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data (26 Aug 2026)']],
            ['link' => ['href' => '/education-guides', 'text' => 'Education guides: Excel, Word, PowerPoint and defensive security literacy']],
            'Want a topic covered next? Use the Contact page and say exactly what you were trying to do when a random tool site made you hesitate.',
        ],
        'faq' => [
            ['How often is the blog updated?', 'New posts go up when there is a real problem worth solving, not on a fake daily calendar.'],
            ['Are these posts sales pages?', 'No. The tools stay free. The writing exists to teach and to earn search traffic the honest way.'],
        ],
    ],
    'wifi-qr-code-guide' => [
        'slug' => 'wifi-qr-code-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Wi-Fi QR Code',
        'published' => '2026-09-17',
        'title' => 'How to Generate a Wi-Fi QR Code Without Uploading the Network Password (2026)',
        'h1' => 'How to generate a Wi-Fi QR code without uploading the network password',
        'description' => 'A 2026 defensive guide to building a Wi-Fi login QR in the browser. Keep the SSID and passphrase in the tab, encode the standard payload, print the code, and skip cloud generators that want a copy of your network secret.',
        'keywords' => 'wifi qr code generator, wifi qr code without upload, generate wifi qr in browser, wifi login qr code, ssid password qr private, shehanly qr generator, guest wifi qr code 2026',
        'intro' => 'A Wi-Fi QR is a convenience sticker, not a cloud product. The payload is the network name plus the passphrase in a public format phones already understand. This page is the short loop: write the payload yourself, encode it in the tab, print it, and never paste the home or office password into a generator you do not run.',
        'body' => [
            'Last updated: 17 September 2026. Written for cafe owners, office admins, Airbnb hosts, and anyone who is tired of spelling a 20-character passphrase out loud. This is for networks you already control. It is not a guide to joining, attacking, or mapping someone else\'s Wi-Fi.',
            ['h2' => 'The QR is the password in another shape'],
            'Phones do not magic a connection out of dots. They read a short text payload, parse the network name and the passphrase, and offer to join. Anyone who photographs that printout has the same secret as anyone who read it off the router sticker.',
            'That is fine for a guest network you intended to share. It is not fine for the admin SSID, the camera VLAN, or the network that also carries the till. Encode what you are willing to hang on a wall. Nothing else.',
            ['link' => ['href' => '/qr-generator', 'text' => 'Open the browser QR code generator']],
            ['link' => ['href' => '/qr-code-guide', 'text' => 'How the QR tool works, and why the payload never uploads']],
            ['h2' => 'Why most Wi-Fi QR sites are a leak'],
            'Search wifi qr code generator and the first results look helpful. Type SSID, type password, download PNG. Plenty of those pages POST the form. Your home passphrase, your shop network, the Airbnb network that never rotates is now a copy on a box you do not run.',
            'Some tools add a share link. Some keep a recent codes list tied to a session cookie. A unique SSID plus a unique passphrase is identifying even after you close the tab. Treat a cloud Wi-Fi QR the same way you treat a cloud password generator: assume the field was logged.',
            ['h2' => 'The payload phones actually read'],
            'Android and iOS understand a small, public text format. You do not need an app to invent it. You need the network name, the security type the router is already using, and the passphrase for that network.',
            ['ul' => [
                'Start with WIFI: and end with ;;. That wrapper is the whole protocol.',
                'T is the security type the router already uses. WPA covers WPA2 and WPA3 personal on most guest phones. WEP is legacy. nopass is an open network.',
                'S is the SSID exactly as the router broadcasts it. Case matters. A hidden space at the end will fail at the table.',
                'P is the passphrase. If the password itself contains a semicolon, backslash, or quote, escape those characters with a backslash so the parser does not split the field.',
                'H is optional. Set it only if the network is hidden. Most guest networks are not.',
            ]],
            'Example shape, not a real network: WIFI:T:WPA;S:GuestNet;P:correct-horse-battery;H:false;;',
            'Write that string in a local note first. Proofread the SSID. Then encode the finished string. Do not invent extra fields. Do not wrap it in JSON. Phones want that one line.',
            ['h2' => 'Step 1: decide which network is allowed on paper'],
            ['ul' => [
                'Prefer a dedicated guest SSID with client isolation. Do not print the staff or camera network.',
                'Rotate the guest passphrase when the printout has lived in public long enough to be photographed by everyone who ate there.',
                'If the only network you have is the one that also holds admin traffic, stop. Split it before you print a QR.',
                'Never encode a WPS PIN, a router admin password, or a fiber-account passphrase. Those are not Wi-Fi join secrets.',
            ]],
            'A QR does not add security. It only changes how the secret is typed. The security decision happened when you chose the SSID and the passphrase.',
            ['h2' => 'Step 2: encode the line in the tab'],
            'The Shehanly generator draws the code in the browser. Watch Network while you paste. You should see static assets only.',
            ['ul' => [
                'Confirm the address bar is shehanly.com/qr-generator.',
                'Paste the finished WIFI:...;; line. Not the password alone. Not the SSID alone.',
                'Generate. Scan it with the same phone you will hand a guest, standing next to the real radio.',
                'Download the PNG only after a live join works. A pretty code that points at a typo is a support ticket.',
                'Close the tab. Do not leave the passphrase sitting in a textarea on a shared laptop.',
            ]],
            ['link' => ['href' => '/qr-generator', 'text' => 'Generate the QR without uploading the passphrase']],
            ['h2' => 'Step 3: print like the code is a password, because it is'],
            ['ul' => [
                'Put it at the till, on the guest table card, or in the welcome book. Not on the street-facing window.',
                'Do not post the PNG to Instagram, Google Business, or a public menu PDF unless that network is meant for the internet to join.',
                'If you email the PNG to a printer, you just emailed the passphrase. Use a machine you already trust, or print locally.',
                'When you rotate the guest password, reprint. An old QR is an old password that still works until you change the router.',
            ]],
            'A faded printout on the wall is still a live credential. Treat reprinting as part of the password rotation, not as decoration.',
            ['h2' => 'A 40-second workflow before the lunch rush'],
            ['ul' => [
                'Confirm you are encoding the guest SSID, not the staff one.',
                'Write the WIFI: line in a local note. Check the SSID character for character.',
                'Open shehanly.com/qr-generator. Confirm the URL.',
                'Paste. Generate. Scan with your own phone while you can still see the router lights.',
                'If it joins, download the PNG and print. If it fails, fix the string. Do not add a second generator to the mix.',
                'Close the tab. Wipe the local note if that machine is shared.',
            ]],
            ['link' => ['href' => '/qr-generator', 'text' => 'Build the code in the tab now']],
            ['h2' => 'What a Wi-Fi QR does not prove'],
            ['ul' => [
                'It does not prove the network is safe. It only proves a phone can submit the passphrase you encoded.',
                'It does not hide the password from anyone with a camera.',
                'It does not replace a guest VLAN, client isolation, or a captive portal you actually configured on the access point.',
                'It does not make an open network private. nopass means anyone in range is already in.',
            ]],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'Need a better guest passphrase first? Generate one in the tab']],
            ['link' => ['href' => '/password-generator', 'text' => 'Open the browser password generator']],
            ['h2' => 'The mistakes that still get shops'],
            ['ul' => [
                'Pasting the home passphrase into the first Google result for wifi qr.',
                'Encoding the ISP-printed default that is also on the router label under the desk.',
                'Printing the staff SSID because the guest network was one extra screen in the mesh app.',
                'Leaving special characters unescaped so half the phones parse a truncated password.',
                'Uploading the PNG to a public menu and wondering who is on the till network.',
            ]],
            ['h2' => 'Pair this with the rest of the stack'],
            ['link' => ['href' => '/qr-generator', 'text' => 'Generate any QR payload in the tab']],
            ['link' => ['href' => '/password-generator', 'text' => 'Generate a fresh guest passphrase first']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'How to generate a strong password without a cloud vault']],
            ['link' => ['href' => '/barcode-generator', 'text' => 'Need a product barcode instead? That tool also stays local']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
            ['h2' => 'Why this post sits next to the tools'],
            'People search wifi qr code because a guest is standing at the counter and nobody wants to spell the passphrase. The useful page tells them the code is the password, shows the public payload format, and hands them a generator that never leaves the tab. That is the Shehanly pattern. Rank for the job. Teach the risk. Finish the job.',
            ['link' => ['href' => '/qr-generator', 'text' => 'Generate the Wi-Fi QR in your browser']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Does Shehanly upload my Wi-Fi password to draw the QR?', 'No. The generator runs in the browser. Watch the Network tab if you want proof.'],
            ['Will iPhone and Android both read the code?', 'Yes, if you use the standard WIFI:...;; payload and the security type matches the router. Scan it yourself before you print.'],
            ['Is printing a Wi-Fi QR safe?', 'It is as safe as taping the passphrase to the wall. Use a guest network, rotate it, and do not post the PNG on a public page.'],
            ['What if the phone refuses to join?', 'The SSID is wrong, the security type does not match, or a special character in the password was not escaped. Fix the string and encode again. Do not add a second website.'],
            ['Can I encode the router admin password this way?', 'No. This format is only for joining a radio. Router admin credentials do not belong in a QR on a table.'],
        ],
    ],
];
