<?php
/** 18 Sep 2026 post. Loaded after pages-sept17.php so the blog index and this article win. */
return [
    'blog' => [
        'slug' => 'blog',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Blog',
        'title' => 'Shehanly Blog - Privacy-First Tools, Security & Everyday Workflows',
        'h1' => 'The Shehanly blog',
        'description' => 'Practical guides on using free online tools without leaking data, converting documents safely, generating strong passwords and working faster with developer utilities.',
        'keywords' => 'shehanly blog, private online tools, free developer tools guides, password security, pdf converter safety, jwt decoder, disposable email, base64 encode decode, paste audit, client side tools',
        'intro' => 'Short, practical articles from the builder of Shehanly. No fluff. Each post solves one problem and points you at the free tool that does the work.',
        'body' => [
            ['h2' => 'Latest posts'],
            'New writing ships here first. Every article is written to rank, to teach, and to send you back into a tool you can actually use.',
            ['link' => ['href' => '/paste-audit-guide', 'text' => 'How to audit what you paste into online tools before you hit submit (18 Sep 2026)']],
            ['link' => ['href' => '/wifi-qr-code-guide', 'text' => 'How to generate a Wi-Fi QR code without uploading the network password (17 Sep 2026)']],
            ['link' => ['href' => '/base64-is-not-encryption-guide', 'text' => 'Base64 is not encryption: how to decode a blob without leaking it (16 Sep 2026)']],
            ['link' => ['href' => '/verify-download-hash-guide', 'text' => 'How to verify a downloaded file with SHA-256 before you run it (15 Sep 2026)']],
            ['link' => ['href' => '/phishing-url-check-guide', 'text' => 'How to decode a suspicious URL without visiting it (14 Sep 2026)']],
            ['link' => ['href' => '/client-file-workflow-guide', 'text' => 'How to process a client file online without leaking it (13 Sep 2026)']],
            ['link' => ['href' => '/browser-only-tools-guide', 'text' => 'Which Shehanly tools stay in your browser, and which ones do not (12 Sep 2026)']],
            ['link' => ['href' => '/code-explainer-guide', 'text' => 'How to explain code online without leaking your source (11 Sep 2026)']],
            ['link' => ['href' => '/text-summarizer-guide', 'text' => 'How to summarize an article online without creating an account (10 Sep 2026)']],
            ['link' => ['href' => '/word-counter-guide', 'text' => 'How to count words and reading time without uploading your draft (9 Sep 2026)']],
            ['link' => ['href' => '/barcode-generator-guide', 'text' => 'How to generate a barcode without uploading your product data (8 Sep 2026)']],
            ['link' => ['href' => '/ip-dns-lookup-guide', 'text' => 'How to look up DNS and IP data without leaking the domain you are investigating (7 Sep 2026)']],
            ['link' => ['href' => '/url-encoder-guide', 'text' => 'How to URL encode and decode without leaking the query string (6 Sep 2026)']],
            ['link' => ['href' => '/base64-guide', 'text' => 'How to encode and decode Base64 without uploading the payload (5 Sep 2026)']],
            ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'How to convert Word to PDF online without leaking the document (4 Sep 2026)']],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'How to format and validate JSON without sending the payload (3 Sep 2026)']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'How to generate MD5 and SHA-256 hashes without uploading the file (2 Sep 2026)']],
            ['link' => ['href' => '/qr-code-guide', 'text' => 'How to generate a QR code without uploading your data (1 Sep 2026)']],
            ['link' => ['href' => '/temp-mail-guide', 'text' => 'How to use a disposable email without leaking your real inbox (31 Aug 2026)']],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'How to decode a JWT in your browser without leaking the token (30 Aug 2026)']],
            ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How to convert a PDF to Word online without leaking the file (29 Aug 2026)']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'How to generate a strong password in your browser (27 Aug 2026)']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data (26 Aug 2026)']],
            ['link' => ['href' => '/education-guides', 'text' => 'Education guides: Excel, Word, PowerPoint and defensive security literacy']],
            'Want a topic covered next? Use the Contact page and say exactly what you were trying to do when a random tool site made you hesitate.',
        ],
        'faq' => [
            ['How often is the blog updated?', 'New posts go up when there is a real problem worth solving, not on a fake daily calendar.'],
            ['Are these posts sales pages?', 'No. The tools stay free. The writing exists to teach and to earn search traffic the honest way.'],
        ],
    ],
    'paste-audit-guide' => [
        'slug' => 'paste-audit-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Paste Audit',
        'published' => '2026-09-18',
        'title' => 'How to Audit What You Paste Into Online Tools Before You Hit Submit (2026)',
        'h1' => 'How to audit what you paste into online tools before you hit submit',
        'description' => 'A 2026 defensive checklist for tokens, JSON, passwords and documents before they leave your clipboard. Strip secrets, confirm the URL, watch the Network tab, and only then use a tool.',
        'keywords' => 'audit paste online tools, do not paste api keys, jwt decoder privacy, json formatter secrets, client side tools checklist, shehanly paste audit, how to use online tools safely 2026',
        'intro' => 'Most leaks do not start with a zero-day. They start with a paste. A JWT from staging. A JSON blob with a live key. A client PDF that still has tracked changes. This page is the 60-second audit before you trust any textarea on the public internet, including ours.',
        'body' => [
            'Last updated: 18 September 2026. Written for developers, freelancers and small-team admins who live in browser tools. This is defensive hygiene. It is not a guide to stealing tokens, bypassing auth, or reading someone else\'s mail.',
            ['h2' => 'The paste is the payload'],
            'A tool cannot protect a secret you already handed it. Client-side code can keep the bytes in the tab. A PHP proxy can hide a vendor key. Neither of those facts undoes a paste that contained a production token, a payroll sheet, or a home Wi-Fi passphrase.',
            'Treat the clipboard like an unencrypted USB stick. Look at what is on it. Then choose the smallest tool that finishes the job.',
            ['link' => ['href' => '/browser-only-tools-guide', 'text' => 'Which Shehanly tools stay in the tab, and which six do not']],
            ['h2' => 'The four things that should never ride along'],
            ['ul' => [
                'Live API keys, session cookies, refresh tokens and Authorization headers. Replace them with PLACEHOLDER_KEY before any formatter or explainer sees the text.',
                'Real customer IDs, emails, phone numbers and invoice totals. Swap them for obvious fakes. If the shape is what you need, the real value is not.',
                'Passwords and Wi-Fi passphrases, unless the tool is a local generator you just used to create them. Do not paste an existing secret into a generator to "check strength" on a site you do not run.',
                'Scans of passports, bank letters, offer letters and anything you would not pin to a cafe noticeboard. Convert those on a machine you already trust, or do not convert them on a public box.',
            ]],
            'If you hesitate for more than two seconds, that hesitation is the audit. Stop. Strip. Then paste.',
            ['h2' => 'Step 1: name the job before you name the website'],
            'Search results lie by being convenient. "jwt decoder", "json formatter", "pdf to word free" all return boxes that want the raw payload. Decide the job first.',
            ['ul' => [
                'Read a token header and expiry: decode, do not verify a signature on a random site.',
                'Pretty-print a payload: format, do not send it to an AI unless you already stripped secrets.',
                'Check a download: hash the file you have, compare to the vendor page you typed.',
                'Share a draft length: count words in the tab. Do not upload the novel to a counter that stores history.',
                'Avoid a signup email: use a disposable inbox, not your real one, and never use it for banks or work SSO.',
            ]],
            'One job. One tool. Close the tab when the job is done. Do not leave yesterday\'s JWT sitting in a textarea on a shared laptop.',
            ['h2' => 'Step 2: confirm the address bar like it is a lock'],
            'Phishing pages copy layouts. They rarely copy the hostname you actually typed last week. Before any paste, look at the bar.',
            ['ul' => [
                'Type shehanly.com yourself or use a bookmark you created. Do not trust the first ad result.',
                'Confirm https. Confirm the exact path. /jwt-decoder is not /jwt-decoder-free on another host.',
                'If a tool asked you to create an account to format JSON, you already lost the plot. Close it.',
            ]],
            ['link' => ['href' => '/phishing-url-check-guide', 'text' => 'How to decode a suspicious URL without visiting it']],
            ['link' => ['href' => '/url-encoder', 'text' => 'Open the URL encoder / decoder']],
            ['h2' => 'Step 3: strip, then choose in-tab when you can'],
            'Nine Shehanly tools never leave the tab: Base64, hash generator, JSON formatter, URL encoder, JWT decoder, QR generator, barcode generator, word counter and password generator. Use those first when the payload is sensitive.',
            ['ul' => [
                'JSON with secrets: delete keys, then format. Watch Network. You should see static assets only.',
                'JWT from a test user: decode in the tab. Read exp and iss. Do not paste a production refresh token anywhere.',
                'File you just downloaded: drop it on the hash tool. Compare SHA-256 to the vendor page you typed, not to a comment on a forum.',
                'New password: generate in the tab, copy once into your password manager, close the generator.',
            ]],
            ['link' => ['href' => '/json-formatter', 'text' => 'Format JSON in the browser']],
            ['link' => ['href' => '/jwt-decoder', 'text' => 'Decode a JWT in the browser']],
            ['link' => ['href' => '/hash-generator', 'text' => 'Hash a file in the browser']],
            ['link' => ['href' => '/password-generator', 'text' => 'Generate a password in the browser']],
            ['h2' => 'Step 4: if it must leave the tab, tell the truth about the proxy'],
            'Six Shehanly jobs cannot honestly finish in JavaScript: PDF to Word, Word to PDF, IP and DNS lookup, 10 minute email, text summarizer and code explainer. They go through a PHP proxy on this domain. The browser still only talks to shehanly.com. The vendor key never ships to JavaScript. There is no account and no history table of old pastes.',
            'The model provider or conversion library still sees the payload for the length of that request. That is the real trade. Do not put a passport through a converter. Do not put a production codebase through an explainer. Strip first. Cap the paste. Close the tab.',
            ['link' => ['href' => '/code-explainer-guide', 'text' => 'How to explain code without leaking source']],
            ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How to convert a PDF to Word without leaking the file']],
            ['link' => ['href' => '/temp-mail-guide', 'text' => 'How to use a disposable email without leaking your real inbox']],
            ['h2' => 'A 60-second paste audit'],
            ['ul' => [
                'Name the job in one sentence. If you cannot, you are browsing, not working.',
                'Scan the clipboard for keys, tokens, emails, account numbers and names. Replace them.',
                'Type the hostname. Confirm the path. Reject anything that wants an account for a two-second job.',
                'Prefer an in-tab tool. Open DevTools, Network, then paste.',
                'If the job needs the proxy, paste the stripped version only. Stay under the published size cap.',
                'Finish. Download if you must. Close the tab. Clear the clipboard on a shared machine.',
            ]],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
            ['h2' => 'The mistakes that still show up in support mail'],
            ['ul' => [
                'Pasting a live Authorization header into a JWT site because the token "would not decode" in the first result.',
                'Formatting production JSON with customer emails still in the fields.',
                'Uploading a client contract to a converter, then emailing the same file from a personal Gmail draft that auto-saved.',
                'Generating a password on a site that also offers to "save it for you".',
                'Using a 10 minute inbox for a bank reset. Disposable mail is for throwaway confirmations, not money.',
            ]],
            ['h2' => 'Pair this with the rest of the stack'],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'Decode a JWT without leaking the token']],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'Format JSON without sending the payload']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'Generate hashes without uploading the file']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'Generate a strong password in the browser']],
            ['link' => ['href' => '/client-file-workflow-guide', 'text' => 'Process a client file without leaking it']],
            ['h2' => 'Why this post sits next to the tools'],
            'People search jwt decoder and pdf to word free because a job is blocked. The useful page does not pretend every tool is magic privacy. It teaches the audit, names which jobs stay local, names which jobs hit a proxy, and then finishes the job. That is the Shehanly pattern. Rank for the task. Tell the truth about the path. Send them back into a tool that does not ask for an account.',
            ['link' => ['href' => '/', 'text' => 'Open the 15 free tools']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Does Shehanly store what I paste?', 'The nine browser tools never upload the payload. The six proxy tools send it for the length of the request and are built not to write a history table. Treat any proxy paste as seen by the upstream for that moment.'],
            ['How do I prove a tool stayed in the tab?', 'Open DevTools, Network, then paste. You should see static assets only. If you see a POST to /api/, that job left the tab on purpose.'],
            ['What should I strip first?', 'API keys, tokens, real emails, customer IDs, passwords and anything you would not put on a shared slide. Replace them with obvious placeholders.'],
            ['Is a disposable email safe for everything?', 'No. Use it for throwaway confirmations. Never use it for banks, government, or work SSO.'],
            ['Can I paste production source into the code explainer?', 'No. Strip secrets, shrink the snippet, and treat the paste like emailing a colleague the function. The proxy plus the model provider will see it for that request.'],
        ],
    ],
];
