<?php
/** 12 Sep 2026 post. Loaded after pages-latest.php so the blog index and this article win. */
return [
    'blog' => [
        'slug' => 'blog',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Blog',
        'title' => 'Shehanly Blog - Privacy-First Tools, Security & Everyday Workflows',
        'h1' => 'The Shehanly blog',
        'description' => 'Practical guides on using free online tools without leaking data, converting documents safely, generating strong passwords and working faster with developer utilities.',
        'keywords' => 'shehanly blog, private online tools, free developer tools guides, password security, pdf converter safety, jwt decoder, disposable email, base64 encode decode, ai text summarizer, ai code explainer, client side tools',
        'intro' => 'Short, practical articles from the builder of Shehanly. No fluff. Each post solves one problem and points you at the free tool that does the work.',
        'body' => [
            ['h2' => 'Latest posts'],
            'New writing ships here first. Every article is written to rank, to teach, and to send you back into a tool you can actually use.',
            ['link' => ['href' => '/browser-only-tools-guide', 'text' => 'Which Shehanly tools stay in your browser, and which ones do not (12 Sep 2026)']],
            ['link' => ['href' => '/code-explainer-guide', 'text' => 'How to explain code online without leaking your source (11 Sep 2026)']],
            ['link' => ['href' => '/text-summarizer-guide', 'text' => 'How to summarize an article online without creating an account (10 Sep 2026)']],
            ['link' => ['href' => '/word-counter-guide', 'text' => 'How to count words and reading time without uploading your draft (9 Sep 2026)']],
            ['link' => ['href' => '/barcode-generator-guide', 'text' => 'How to generate a barcode without uploading your product data (8 Sep 2026)']],
            ['link' => ['href' => '/ip-dns-lookup-guide', 'text' => 'How to look up DNS and IP data without leaking the domain you are investigating (7 Sep 2026)']],
            ['link' => ['href' => '/url-encoder-guide', 'text' => 'How to URL encode and decode without leaking the query string (6 Sep 2026)']],
            ['link' => ['href' => '/base64-guide', 'text' => 'How to encode and decode Base64 without uploading the payload (5 Sep 2026)']],
            ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'How to convert Word to PDF online without leaking the document (4 Sep 2026)']],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'How to format and validate JSON without sending the payload (3 Sep 2026)']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'How to generate MD5 and SHA-256 hashes without uploading the file (2 Sep 2026)']],
            ['link' => ['href' => '/qr-code-guide', 'text' => 'How to generate a QR code without uploading your data (1 Sep 2026)']],
            ['link' => ['href' => '/temp-mail-guide', 'text' => 'How to use a disposable email without leaking your real inbox (31 Aug 2026)']],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'How to decode a JWT in your browser without leaking the token (30 Aug 2026)']],
            ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How to convert a PDF to Word online without leaking the file (29 Aug 2026)']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'How to generate a strong password in your browser (27 Aug 2026)']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data (26 Aug 2026)']],
            ['link' => ['href' => '/education-guides', 'text' => 'Education guides: Excel, Word, PowerPoint and defensive security literacy']],
            'Want a topic covered next? Use the Contact page and say exactly what you were trying to do when a random tool site made you hesitate.',
        ],
        'faq' => [
            ['How often is the blog updated?', 'New posts go up when there is a real problem worth solving, not on a fake daily calendar.'],
            ['Are these posts sales pages?', 'No. The tools stay free. The writing exists to teach and to earn search traffic the honest way.'],
        ],
    ],
    'browser-only-tools-guide' => [
        'slug' => 'browser-only-tools-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Browser-Only Tools Guide',
        'published' => '2026-09-12',
        'title' => 'Which Shehanly Tools Stay in Your Browser (and Which Do Not) - 2026',
        'h1' => 'Which Shehanly tools stay in your browser, and which ones do not',
        'description' => 'A 2026 map of Shehanly tools: the nine that never leave the tab, the six that travel through a PHP proxy, how to verify the difference in DevTools, and a 30-second rule for what you should paste where.',
        'keywords' => 'client side online tools, browser only tools no upload, private developer tools 2026, shehanly privacy, php proxy tools, no signup utilities, web crypto tools',
        'intro' => 'Free tools lie with badges. Local. Private. Instant. Then the Network tab shows a POST to a hostname you have never heard of. This page is the honest map of Shehanly: nine tools that never leave the tab, six that go through a PHP proxy on this domain, how to prove it yourself, and a rule for what belongs in each bucket.',
        'body' => [
            'Last updated: 12 September 2026. Written for anyone who has hovered over Convert and wondered where the file actually goes.',
            ['h2' => 'The only question that matters'],
            'Does the payload stay in this process, or does it leave the machine? Everything else is decoration. Sign-up walls, share links, history panes and training toggles are just ways of making the leave-the-machine case worse.',
            'Shehanly splits the suite on that line. The split is public. The Network tab is the proof.',
            ['h2' => 'The nine that never leave the tab'],
            'These tools run on Web APIs in your browser. No account. No upload. Close the tab and the input is gone.',
            ['ul' => [
                'Base64 encode and decode. Strings stay in memory. Nothing is posted.',
                'Hash generator. MD5, SHA-1, SHA-256 and friends via Web Crypto. The file is read locally.',
                'JSON formatter. Parse, pretty-print and validate in the page.',
                'URL encode and decode. Query strings never leave the box.',
                'JWT decoder. Header and payload are base64url-decoded locally. The signature is not sent to a server to verify.',
                'QR code generator. Canvas stays on device.',
                'Barcode generator. Same rule. Product SKUs do not get a free ride to a log file.',
                'Word and reading time. Counts happen on the paste. The draft is not stored.',
                'Password generator. Randomness is created in the browser. The result is not emailed to you and is not saved in an account.',
            ]],
            ['link' => ['href' => '/base64', 'text' => 'Open Base64']],
            ['link' => ['href' => '/hash-generator', 'text' => 'Open the hash generator']],
            ['link' => ['href' => '/json-formatter', 'text' => 'Open the JSON formatter']],
            ['link' => ['href' => '/url-encoder', 'text' => 'Open URL encode / decode']],
            ['link' => ['href' => '/jwt-decoder', 'text' => 'Open the JWT decoder']],
            ['link' => ['href' => '/qr-generator', 'text' => 'Open the QR generator']],
            ['link' => ['href' => '/barcode-generator', 'text' => 'Open the barcode generator']],
            ['link' => ['href' => '/word-counter', 'text' => 'Open the word counter']],
            ['link' => ['href' => '/password-generator', 'text' => 'Open the password generator']],
            ['h2' => 'The six that travel through a PHP proxy'],
            'These jobs cannot honestly finish inside a tab. Document conversion needs a library. Live DNS needs a resolver. Temporary inboxes need a mail backend. The two AI tools need a model. Pretending those run locally would be a badge, not a fact.',
            ['ul' => [
                'PDF to Word. File goes to /api/convert.php on this host. Default cap is 20 MB.',
                'Word to PDF. Same proxy, same cap.',
                'IP and DNS lookup. Hostname goes to /api/dns.php. You asked for public records. That is the point.',
                '10 minute email. The inbox lives on the server for a short window. That is how disposable mail works.',
                'Text summarizer. Paste goes to /api/ai.php. The PHP layer holds the provider key, rate-limits the IP and caps the body at 12,000 characters.',
                'Code explainer. Same AI proxy. Same cap. Same rule: strip secrets first.',
            ]],
            'The browser still only talks to shehanly.com. The provider key never ships to JavaScript. There is no account and no history table of old pastes. The model provider or conversion library still sees the payload for that request. That is the real trade.',
            ['link' => ['href' => '/pdf-to-word', 'text' => 'Open PDF to Word']],
            ['link' => ['href' => '/word-to-pdf', 'text' => 'Open Word to PDF']],
            ['link' => ['href' => '/ip-dns-lookup', 'text' => 'Open IP and DNS lookup']],
            ['link' => ['href' => '/temp-mail', 'text' => 'Open 10 minute email']],
            ['link' => ['href' => '/text-summarizer', 'text' => 'Open the text summarizer']],
            ['link' => ['href' => '/code-explainer', 'text' => 'Open the code explainer']],
            ['h2' => 'A 30-second rule before you paste'],
            ['ul' => [
                'If you would not email the raw file to a contractor, do not put it in a proxied tool.',
                'Passwords, tokens, private keys and unpublished customer data belong in the nine browser-only tools, or nowhere online.',
                'A JWT you are debugging can stay in the decoder. A production refresh token should be redacted first even there.',
                'A public blog post is fine in the summarizer. A payroll spreadsheet is not.',
                'A function with YOUR_TOKEN placeholders is fine in the explainer. The same function with a live Stripe key is not.',
            ]],
            ['h2' => 'How to verify the claim in DevTools'],
            ['ul' => [
                'Open the tool. Open DevTools. Network tab. Filter Fetch/XHR.',
                'Paste a dummy string or drop a tiny file.',
                'Browser-only tools: you should see no POST to an API. Maybe a font or an ad. Not your payload.',
                'Proxied tools: you should see a POST to /api/convert.php, /api/dns.php, /api/tempmail.php or /api/ai.php on this host.',
                'If the request leaves for a third-party hostname from the browser, close the tab. That is not the Shehanly pattern.',
            ]],
            'Badges are cheap. The Network tab is not.',
            ['h2' => 'The errors that waste a Saturday'],
            ['ul' => [
                'Trusting a Local processing label on a site that still posts the file to api.random-saas.com.',
                'Pasting a .env into an explainer because the box looks small.',
                'Generating a password in a tool that emails you the result.',
                'Hashing a confidential contract on a site that stores uploads for 24 hours so you can share a link.',
                'Using disposable mail as a password-reset inbox for an account you care about. When the address dies, recovery dies with it.',
            ]],
            ['h2' => 'Pair this map with the rest of the writing'],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'Generate a strong password in the browser']],
            ['link' => ['href' => '/code-explainer-guide', 'text' => 'Explain code without leaking source']],
            ['link' => ['href' => '/text-summarizer-guide', 'text' => 'Summarize a page without creating an account']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'Hash a file without uploading it']],
            ['h2' => 'Why this post sits on the blog'],
            'People search private online tools and get a wall of identical landing pages. The useful page is a map: what stays, what leaves, how to check, what never to paste. Then the tools. That is the Shehanly pattern. Rank for the job. Teach the risk. Finish the job.',
            ['link' => ['href' => '/', 'text' => 'Open the full tool list']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Which tools never upload my data?', 'Nine: Base64, hash generator, JSON formatter, URL encoder, JWT decoder, QR generator, barcode generator, word counter and password generator. They run in the tab.'],
            ['Which tools leave the browser?', 'Six: PDF to Word, Word to PDF, IP and DNS lookup, 10 minute email, text summarizer and code explainer. They go through a PHP proxy on shehanly.com.'],
            ['Does the proxy store my files?', 'The convert and AI endpoints are built not to write a history table of pastes. Treat the payload as sent for the length of the request. The model provider or conversion library still sees it.'],
            ['How do I prove a tool is browser-only?', 'DevTools, Network, dummy paste. No POST of your payload. If you see a third-party API from the browser, leave.'],
            ['Do I need an account?', 'No. Not for the nine. Not for the six.'],
        ],
    ],
];
