<?php
/** 21 Sep 2026 post. Loaded after pages-sept20.php so the blog index and this article win. */
return [
    'blog' => [
        'slug' => 'blog',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Blog',
        'title' => 'Shehanly Blog - Privacy-First Tools, Security & Everyday Workflows',
        'h1' => 'The Shehanly blog',
        'description' => 'Practical guides on using free online tools without leaking data, converting documents safely, generating strong passwords and working faster with developer utilities.',
        'keywords' => 'shehanly blog, private online tools, free developer tools guides, password security, pdf converter safety, jwt decoder, disposable email, base64 encode decode, paste audit, client side tools, clipboard hygiene, shared laptop hygiene',
        'intro' => 'Short, practical articles from the builder of Shehanly. No fluff. Each post solves one problem and points you at the free tool that does the work.',
        'body' => [
            ['h2' => 'Latest posts'],
            'New writing ships here first. Every article is written to rank, to teach, and to send you back into a tool you can actually use.',
            ['link' => ['href' => '/shared-laptop-hygiene-guide', 'text' => 'How to leave no files, no history and no secrets on a shared laptop after you use a tool (21 Sep 2026)']],
            ['link' => ['href' => '/clipboard-hygiene-guide', 'text' => 'How to keep tokens and passwords out of clipboard history after you use a tool (20 Sep 2026)']],
            ['link' => ['href' => '/prove-client-side-tool-guide', 'text' => 'How to prove an online tool stayed in your browser before you paste (19 Sep 2026)']],
            ['link' => ['href' => '/paste-audit-guide', 'text' => 'How to audit what you paste into online tools before you hit submit (18 Sep 2026)']],
            ['link' => ['href' => '/wifi-qr-code-guide', 'text' => 'How to generate a Wi-Fi QR code without uploading the network password (17 Sep 2026)']],
            ['link' => ['href' => '/base64-is-not-encryption-guide', 'text' => 'Base64 is not encryption: how to decode a blob without leaking it (16 Sep 2026)']],
            ['link' => ['href' => '/verify-download-hash-guide', 'text' => 'How to verify a downloaded file with SHA-256 before you run it (15 Sep 2026)']],
            ['link' => ['href' => '/phishing-url-check-guide', 'text' => 'How to decode a suspicious URL without visiting it (14 Sep 2026)']],
            ['link' => ['href' => '/client-file-workflow-guide', 'text' => 'How to process a client file online without leaking it (13 Sep 2026)']],
            ['link' => ['href' => '/browser-only-tools-guide', 'text' => 'Which Shehanly tools stay in your browser, and which ones do not (12 Sep 2026)']],
            ['link' => ['href' => '/code-explainer-guide', 'text' => 'How to explain code online without leaking your source (11 Sep 2026)']],
            ['link' => ['href' => '/text-summarizer-guide', 'text' => 'How to summarize an article online without creating an account (10 Sep 2026)']],
            ['link' => ['href' => '/word-counter-guide', 'text' => 'How to count words and reading time without uploading your draft (9 Sep 2026)']],
            ['link' => ['href' => '/barcode-generator-guide', 'text' => 'How to generate a barcode without uploading your product data (8 Sep 2026)']],
            ['link' => ['href' => '/ip-dns-lookup-guide', 'text' => 'How to look up DNS and IP data without leaking the domain you are investigating (7 Sep 2026)']],
            ['link' => ['href' => '/url-encoder-guide', 'text' => 'How to URL encode and decode without leaking the query string (6 Sep 2026)']],
            ['link' => ['href' => '/base64-guide', 'text' => 'How to encode and decode Base64 without uploading the payload (5 Sep 2026)']],
            ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'How to convert Word to PDF online without leaking the document (4 Sep 2026)']],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'How to format and validate JSON without sending the payload (3 Sep 2026)']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'How to generate MD5 and SHA-256 hashes without uploading the file (2 Sep 2026)']],
            ['link' => ['href' => '/qr-code-guide', 'text' => 'How to generate a QR code without uploading your data (1 Sep 2026)']],
            ['link' => ['href' => '/temp-mail-guide', 'text' => 'How to use a disposable email without leaking your real inbox (31 Aug 2026)']],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'How to decode a JWT in your browser without leaking the token (30 Aug 2026)']],
            ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How to convert a PDF to Word online without leaking the file (29 Aug 2026)']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'How to generate a strong password in your browser (27 Aug 2026)']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data (26 Aug 2026)']],
            ['link' => ['href' => '/education-guides', 'text' => 'Education guides: Excel, Word, PowerPoint and defensive security literacy']],
            'Want a topic covered next? Use the Contact page and say exactly what you were trying to do when a random tool site made you hesitate.',
        ],
        'faq' => [
            ['How often is the blog updated?', 'New posts go up when there is a real problem worth solving, not on a fake daily calendar.'],
            ['Are these posts sales pages?', 'No. The tools stay free. The writing exists to teach and to earn search traffic the honest way.'],
        ],
    ],
    'shared-laptop-hygiene-guide' => [
        'slug' => 'shared-laptop-hygiene-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Shared Laptop Hygiene',
        'published' => '2026-09-21',
        'title' => 'How to Leave No Files, No History and No Secrets on a Shared Laptop After You Use a Tool (2026)',
        'h1' => 'How to leave no files, no history and no secrets on a shared laptop after you use a tool',
        'description' => 'A 2026 close-out for cafe PCs, hotel business centers and borrowed work laptops: private window, dummy probe, convert or decode, copy once, wipe Downloads, wipe clipboard history, sign out. Defensive hygiene only.',
        'keywords' => 'shared laptop privacy, cafe computer wipe history, hotel business center security, clear downloads after converter, private window online tools, leave no files shared pc, shehanly shared laptop hygiene',
        'intro' => 'The tab can stay honest and the machine can still keep the work. Downloads, Recent files, browser history, autofill and Win+V all outlive the converter. This is the five-minute close-out for a laptop you do not own.',
        'body' => [
            'Last updated: 21 September 2026. Written for freelancers on a cafe PC, students on a lab machine, travelers on a hotel business-center box, and anyone who just converted a client PDF on a laptop that is not theirs. This is defensive hygiene on a machine you already have permission to use. It is not a guide to wiping other people\'s accounts or hiding activity from an employer.',
            ['h2' => 'The tool was never the last hop'],
            'Yesterday we overwrote the clipboard. The day before we proved the formatter stayed in the tab. None of that matters if the PDF lands in C:\\Users\\Public\\Downloads and the next guest opens File Explorer.',
            'A shared laptop keeps five copies of the job by default: the download, the browser history entry, the Recent files list, the clipboard, and sometimes an Office or Preview thumbnail. Closing the tab deletes one of those five. The other four wait.',
            'The job is not "never use a public PC". The job is private window, dummy file first, real file once, copy once, wipe the five copies, walk away.',
            ['link' => ['href' => '/clipboard-hygiene-guide', 'text' => 'Overwrite the clipboard after the copy']],
            ['link' => ['href' => '/prove-client-side-tool-guide', 'text' => 'Prove the tool stayed in the tab first']],
            ['link' => ['href' => '/client-file-workflow-guide', 'text' => 'How to process a client file on a machine you do not fully trust']],
            ['h2' => 'When this workflow is the right call'],
            ['ul' => [
                'A hotel business center when the only other option is emailing the file to yourself on hotel Wi-Fi.',
                'A campus lab machine that resets nightly but still keeps the current session.',
                'A colleague laptop you borrowed for twenty minutes because yours died.',
                'A family PC that three people share and nobody locked the Downloads folder.',
            ]],
            'If the file is under NDA that forbids any third-party processor, do not convert it on a cafe PC. Hygiene does not create a contract exception. Wait for your own machine.',
            ['h2' => 'The five-minute close-out'],
            ['ul' => [
                'Open a private or Incognito window. Confirm the address is shehanly.com before you drop anything.',
                'Run a dummy first. A one-page fake PDF or a throwaway password. Watch Network. If a third-party host appears, close the window and leave.',
                'Do the real job once. Convert, decode, hash, generate. Download only if you must. Prefer copy into the place that needs it.',
                'Copy a single space after the last paste so the current clipboard slot is junk.',
                'Open Downloads. Delete the input and the output. Empty the Recycle Bin or Trash. On Windows, Shift+Delete skips the Bin if the policy allows it.',
                'Clear browsing data for this session only: history, cookies, cached files. Then close every private window.',
                'Sign out of any account you touched. Do not save passwords when the browser offers.',
            ]],
            'If you cannot empty Trash because the account is locked down, at least delete the files from Downloads and overwrite the clipboard. Partial cleanup beats a live contract sitting in Recent.',
            ['h2' => 'Downloads is the real log'],
            'Browsers love to drop converter output into the default Downloads folder with the original filename. A file named Acme-payroll-September.docx is a label, not just a document.',
            ['ul' => [
                'Before you upload, rename the local copy to dummy-scan.pdf. Convert. Rename the result after it is on a machine you own.',
                'Never let the site auto-open the PDF in the laptop\'s reader. That reader writes thumbnails and Recent lists of its own.',
                'Check Desktop and Documents. Some browsers "helpfully" save there when Downloads is full.',
                'Office, Preview and Photos keep recently opened lists. Close the file, then scan those lists and remove the entry if the UI lets you.',
            ]],
            'A hash of the file on this laptop is fine. Uploading the same file to a second random converter "just to be sure" is how you double the copies.',
            ['link' => ['href' => '/hash-generator', 'text' => 'Hash the file in the browser before you move it']],
            ['link' => ['href' => '/verify-download-hash-guide', 'text' => 'How to verify a download with SHA-256']],
            ['h2' => 'Browser history, autofill and the next guest'],
            'A private window hides history from the next profile. It does not hide a file already written to disk. It also does not hide a password you told Chrome to save in the normal profile because you opened the wrong window.',
            ['ul' => [
                'If you accidentally used a normal window, clear history for the last hour, not "all time", unless this is your machine.',
                'Decline Save password. Decline the translate popup that wants to send the page.',
                'Do not pin the result tab. Do not leave the JWT decoder sitting on screen while you pay for coffee.',
                'If the cafe PC has a clipboard manager or a "recent copies" keyboard, treat it as Win+V and clear it.',
            ]],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'Decode a JWT without leaving the token on screen']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'Generate a password in the tab, then store it in your vault not the laptop']],
            ['h2' => 'What belongs on a shared PC and what does not'],
            ['ul' => [
                'Safe enough for a hurried job: a public article to summarize, a dummy JSON probe, a checksum of a public ISO, a throwaway signup with disposable mail.',
                'Keep off a shared disk: live payroll, unsigned contracts, production JWTs, client PII, anything you would not print at the front desk.',
                'Redact first if you must convert: strip comments, tracked changes and hidden author names in Word before the file ever hits Downloads.',
            ]],
            'Disposable mail plus a generated password is how you confirm an account without teaching the cafe PC your real inbox.',
            ['link' => ['href' => '/temp-mail', 'text' => 'Open a disposable inbox']],
            ['link' => ['href' => '/temp-mail-guide', 'text' => 'How to use disposable email without leaking your real inbox']],
            ['link' => ['href' => '/password-generator', 'text' => 'Generate the password in the browser']],
            ['h2' => 'Converters make extra copies. Plan for that.'],
            'PDF to Word and Word to PDF touch a server. That is honest. The extra copy you control is the download on this laptop. Delete both the upload source and the converted output when the job is done.',
            ['link' => ['href' => '/pdf-to-word', 'text' => 'PDF to Word converter']],
            ['link' => ['href' => '/word-to-pdf', 'text' => 'Word to PDF converter']],
            ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How to convert a PDF to Word without leaking the file']],
            ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'How to convert Word to PDF without leaking the document']],
            'Nine Shehanly tools never leave the tab. Use those when the cafe PC is the only option and the payload is already sensitive enough that a download would be a mistake.',
            ['link' => ['href' => '/browser-only-tools-guide', 'text' => 'Which tools stay in the browser']],
            ['h2' => 'A dummy drill you can run today'],
            ['ul' => [
                'On your own machine, open a private window. Convert a one-page dummy PDF.',
                'Find the file in Downloads. Delete it. Empty Trash.',
                'Copy a space. Open clipboard history if you have it and delete the dummy name.',
                'Close the private window. Confirm the dummy URL is not in normal history.',
            ]],
            'Do the drill once so the live client file is not the first time you remember Downloads exists.',
            ['h2' => 'Pair this with the rest of the stack'],
            ['link' => ['href' => '/clipboard-hygiene-guide', 'text' => 'Clipboard close-out after the copy']],
            ['link' => ['href' => '/paste-audit-guide', 'text' => 'Strip secrets before the paste']],
            ['link' => ['href' => '/prove-client-side-tool-guide', 'text' => 'Watch Network before you trust the tab']],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'Format JSON without sending the payload']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
            ['h2' => 'Why this post sits next to the tools'],
            'People search pdf to word on a machine they do not own because a deadline is now. The useful page does not end at the download button. It names Downloads, Recent files, Win+V and the private window, then hands them a tool that does not need an account. That is the Shehanly pattern. Rank for the task. Prove the path. Leave the laptop cleaner than you found it.',
            ['link' => ['href' => '/', 'text' => 'Open the 15 free tools']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Does Incognito delete the downloaded PDF?', 'No. A private window hides history from the next profile. Files in Downloads stay until you delete them and empty Trash.'],
            ['Is it safe to convert a client contract on a hotel PC?', 'Only if the alternative is worse and the NDA allows a processor. Use a dummy first, rename the file, delete both copies, overwrite the clipboard, close the private window.'],
            ['Can I skip emptying the Recycle Bin?', 'Do not. Restoring a deleted payroll PDF is a single click for the next user if Trash still holds it.'],
            ['Does Shehanly keep the file after I close the tab?', 'The nine browser tools never receive the file. The converters proxy the bytes and unlink the upload. Your leftover copy is the one in Downloads on that laptop.'],
            ['What if the shared PC blocks emptying Trash?', 'Delete the files from Downloads anyway, overwrite the clipboard, close the private window, and move the real work to a machine you control as soon as you can.'],
        ],
    ],
];
