<?php
/** Extra indexable pages merged on top of config/routes.php */
return [
    'word-to-pdf-guide' => [
        'slug' => 'word-to-pdf-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Word to PDF Guide',
        'published' => '2026-09-04',
        'title' => 'How to Convert Word to PDF Online Without Leaking the Document (2026)',
        'h1' => 'How to convert Word to PDF online without leaking the document',
        'description' => 'A 2026 guide to turning DOC and DOCX files into print-ready PDFs: why random converter sites keep a copy, how a PHP proxy conversion should work, and a 60-second workflow that does not ask you to create an account.',
        'keywords' => 'word to pdf online, convert docx to pdf free, word to pdf no signup, secure document converter, convert word document, shehanly',
        'intro' => 'A Word file is rarely just a resume. It is a contract, a payroll sheet, a client proposal, a school assignment with a real name on page one. The moment a converter asks you to create an account so it can email you the PDF, the document is no longer only yours. This guide shows how to convert DOC and DOCX to PDF through a short-lived proxy, what a safe converter must never do, and how to finish the job in under a minute.',
        'body' => [
            'Last updated: 4 September 2026. Written for students, freelancers, small business owners and anyone who just finished a .docx and needs a PDF that prints the same on every device.',
            ['h2' => 'What Word to PDF actually does'],
            'A Word file is a package: text, fonts, images, headers, comments, tracked changes and sometimes embedded objects. A PDF freezes that layout into a page description. The reader cannot casually break your margins. The printer cannot invent a different font. That is why people convert before they send.',
            'The conversion is not a browser toy. Rendering Word layout correctly needs a document engine. That is why this job is one of the six Shehanly tools that touch a server. The other nine stay in the tab. Honesty beats a fake local badge.',
            ['h2' => 'Why most online converters are a leak'],
            'Search word to pdf and the first results look identical. Drop file, wait, download. What they hide is the rest of the funnel: a forced signup, a watermark unless you pay, a share link that stays live, or a recent files list tied to an email you never wanted to give.',
            'Some sites keep the upload so they can offer Convert again later. Some scan the file for marketing keywords. A unique contract PDF is identifying even after you close the tab. If the converter also wants permission to email you tips, you just handed them a document and an inbox.',
            ['h2' => 'The safe pattern: proxy the file, delete the file'],
            'Shehanly never lets the browser talk to the conversion vendor. The file is streamed to a PHP proxy on this domain. The proxy attaches the private API key on the server, sends the bytes, returns the PDF, and unlinks the upload in a finally block. The key never ships to the tab. The document is not kept as an account artifact, because there are no accounts.',
            ['link' => ['href' => '/word-to-pdf', 'text' => 'Open the Word to PDF converter']],
            ['h2' => 'A 60-second workflow when the draft is done'],
            ['ul' => [
                'Save the Word file as .docx if you still have a legacy .doc. Both work. .docx is smaller and cleaner.',
                'Accept or reject tracked changes first if the file is going to a client. A PDF will freeze whatever is on the page, including leftover markup you forgot to hide.',
                'Open the converter on shehanly.com. Confirm the URL.',
                'Drop the file. Wait for the download. The default Hostinger-friendly cap is 20 MB.',
                'Open the PDF once. Check page count, headers and any table that likes to jump.',
                'Send the PDF. Leave the .docx on your machine if you still need to edit.',
            ]],
            ['link' => ['href' => '/word-to-pdf', 'text' => 'Convert the document now']],
            ['h2' => 'What a converter must never do'],
            ['ul' => [
                'It must not force an account to return your own file.',
                'It must not stamp a watermark on a free export and call that a preview.',
                'It must not keep a public /files/abc123 link of the PDF.',
                'It must not email the result to an address you typed in a panic.',
                'It must not expose the vendor API key in JavaScript so anyone can burn your quota.',
            ]],
            'A fast test: upload a one-page dummy file, open DevTools, watch Network. You should see a request to this domain only. If the browser posts straight to a third-party converter, close the tab.',
            ['h2' => 'Layout surprises that waste an afternoon'],
            ['ul' => [
                'Fonts that live only on your laptop. If the engine cannot embed them, it substitutes and the line breaks move.',
                'Text boxes parked in the margin. They look fine in Print Layout and fall off the PDF page.',
                'Headers that collide with a logo you placed on the first page only.',
                'Comments and ink. Decide whether they belong in the sent file before you convert.',
                'A 40 MB image dump. Compress pictures in Word first. A 20 MB cap is a feature on shared hosting, not a bug.',
            ]],
            'If the PDF looks wrong, fix the Word file. Converting twice with the same broken layout will not invent a better page.',
            ['h2' => 'Word to PDF versus PDF to Word'],
            'These are opposite jobs. Word to PDF freezes. PDF to Word tries to thaw a page back into an editable document, and tables never come back perfect. Use Word to PDF when the writing is finished. Use PDF to Word when someone sent you a locked page and you need the text.',
            ['link' => ['href' => '/pdf-to-word', 'text' => 'Need the other direction? Open PDF to Word']],
            ['h2' => 'Pair it with the rest of the stack'],
            ['link' => ['href' => '/word-counter', 'text' => 'Count words and reading time before you freeze the draft']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'Hash the PDF locally if you need a checksum of what you sent']],
            ['link' => ['href' => '/qr-generator', 'text' => 'Put a QR code on the last page without uploading the URL']],
            ['link' => ['href' => '/password-generator', 'text' => 'Generate a strong password if the PDF itself needs a lock later']],
            ['h2' => 'Why this post sits next to the tool'],
            'People search word to pdf because a document is done and a reader needs a frozen page. The honest page tells them the file will hit a server, why that server should be a proxy that deletes the upload, what the converter must never keep, and then hands them the tool. That is the Shehanly pattern: rank for the job, teach the risk, finish the job.',
            ['link' => ['href' => '/word-to-pdf', 'text' => 'Convert DOC or DOCX to PDF']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Is the Word file stored after conversion?', 'No. The upload is written to a temporary directory, streamed through the proxy and unlinked in a finally block. There is no account history because there are no accounts.'],
            ['Do you add a watermark?', 'No. The PDF you download is exactly what the converter produced.'],
            ['Which formats are accepted?', 'DOC, DOCX, ODT and RTF hit the same endpoint. Prefer DOCX when you have a choice.'],
            ['Why not convert inside the browser?', 'Faithful Word layout needs a document engine. Pretending a laptop tab can match Word page-for-page is marketing. The honest design is a short-lived proxy that never exposes the vendor key.'],
        ],
    ],
    'json-formatter-guide' => [
        'slug' => 'json-formatter-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'JSON Formatter Guide',
        'published' => '2026-09-03',
        'title' => 'How to Format and Validate JSON in Your Browser Without Sending the Payload (2026)',
        'h1' => 'How to format and validate JSON in your browser without sending the payload',
        'description' => 'A 2026 guide to pretty-printing, minifying and validating JSON in the tab: why pasting an API response into a random formatter is a leak, how to find the exact syntax error, and when minify versus beautify actually matters.',
        'keywords' => 'json formatter online, json validator no upload, pretty print json browser, minify json, json lint privacy, format json locally, shehanly',
        'intro' => 'JSON is just text until it contains a session token, a customer list, or last night production log. The moment a formatter uploads that text to print indentation, the payload is no longer yours. This guide shows how to beautify, minify and lint JSON in the tab, read the error line, and keep the bytes on your machine.',
        'body' => [
            'Last updated: 3 September 2026. Written for backend engineers, QA, support teams and anyone who just copied a response out of DevTools and needs it readable without handing it to a stranger.',
            ['h2' => 'What a JSON formatter actually does'],
            'Pretty-print adds whitespace so humans can scan keys. Minify strips that whitespace so the payload is smaller on the wire. Validate checks that the text is legal JSON: matching braces, quoted keys, no trailing commas, no comments unless you opted into a superset.',
            'None of those jobs need a server. JSON.parse runs in every browser. A local formatter is a thin UI over that parser plus a printer.',
            ['h2' => 'Why most online JSON sites are a leak'],
            'Search json formatter and the first results look harmless. Paste, click Format, copy. What they do not put in the hero is that the textarea is a form post. An access token, a webhook body with card last-fours, a GraphQL dump with emails is now a copy on a box you do not run.',
            'Some tools keep Recent pastes. Some wrap the result in a share link. A unique JSON blob is identifying even after you close the tab. Support tickets get pasted into formatters every day. That is how customer data leaves the company without a breach ticket.',
            ['h2' => 'The safe pattern: parse in the tab'],
            'Shehanly formats, minifies, validates and sorts keys in the browser. Nothing is posted. Watch the Network panel while you paste a 2 MB export. You should see static assets only.',
            ['link' => ['href' => '/json-formatter', 'text' => 'Open the browser JSON formatter']],
            ['h2' => 'A 45-second workflow when an API response looks like noise'],
            ['ul' => [
                'Copy the raw body from DevTools, a log line, or a .json file. Do not copy the headers unless you need them.',
                'Open the formatter on shehanly.com. Confirm the URL.',
                'Paste. Hit validate first if the print looks empty. A single trailing comma will fail the parse.',
                'Read the error position. Line and column beat staring at a wall of text.',
                'Beautify when you need to scan. Minify when you are about to ship the payload or hash it.',
                'Copy the result and close the tab. The original paste never left the machine.',
            ]],
            ['link' => ['href' => '/json-formatter', 'text' => 'Format the payload locally now']],
            ['h2' => 'Beautify versus minify versus sort'],
            ['ul' => [
                'Beautify: debugging, code review, writing a fixture by hand. Two-space indent is the default most teams already use.',
                'Minify: request size, storing a blob in a column, or hashing the canonical bytes. Pretty JSON and minified JSON are different strings.',
                'Sort keys: diffs. Unsorted keys make git blame lie. Sorted keys make two equal objects look equal.',
            ]],
            'If you hash JSON, minify and sort first or you will hash whitespace noise. Pair the formatter with the local hash tool when you need a digest of the canonical payload.',
            ['h2' => 'The errors that waste an afternoon'],
            ['ul' => [
                'Trailing commas. Legal in JavaScript object literals. Illegal in JSON. Remove the last comma before the closing brace.',
                'Single quotes. JSON keys and strings use double quotes. A Python dict pasted raw will fail.',
                'Comments. JSON has none. JSONC and JSON5 are different languages. Strip comments or use a parser that admits it is not JSON.',
                'NaN, Infinity, undefined. JSON has null. Those three values are JavaScript, not the interchange format.',
                'Smart quotes from Slack or Word. They look identical until the parser dies on byte 0xE2.',
            ]],
            'If the error points at line 1 column 1, you probably pasted HTML, a JWT, or a Python repr. Check the first character. JSON objects start with { or [.',
            ['h2' => 'What a JSON tool must never do'],
            ['ul' => [
                'It must not POST the textarea to print spaces.',
                'It must not create a public /p/abc123 link of your last paste.',
                'It must not auto-save the payload to an account you did not ask for.',
                'It must not call itself a JSON encryptor. Formatting is not encryption.',
                'It must not phone home with a sample of keys for product analytics.',
            ]],
            'A fast test: paste {"probe":true}, open DevTools, watch Network. If a request carries the object, close the tab.',
            ['h2' => 'Large files and pretty-print cost'],
            'A 20 MB export will format in the tab. It will also freeze a cheap laptop if you re-render the whole tree as nested HTML. Prefer a plain textarea print for big blobs. Collapse is a viewer feature, not a parser feature.',
            'If the file is a secret dump, do the work on a machine that is already allowed to hold it. A private formatter does not make a classified file public-safe. It only stops a third website from joining the party.',
            ['h2' => 'Pair it with the rest of the stack'],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'Decode a JWT in the browser without leaking the token']],
            ['link' => ['href' => '/base64', 'text' => 'Base64 decode a wrapped payload first']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'Hash the minified JSON without uploading it']],
            ['link' => ['href' => '/url-encoder', 'text' => 'URL-decode a query string before you parse it']],
            ['h2' => 'Why this post sits next to the tool'],
            'People search json formatter because a response landed and they cannot read it. The honest page tells them the paste is often a secret, why the parser must stay in the tab, which error to fix first, and then hands them the formatter. That is the Shehanly pattern: rank for the job, teach the risk, finish the job.',
            ['link' => ['href' => '/json-formatter', 'text' => 'Format, validate and minify JSON locally']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Does formatting JSON change the data?', 'No. Beautify and minify change whitespace only. Sort keys changes key order, which is still the same object, but a different string if you hash it.'],
            ['Why does my JSON fail to parse?', 'Trailing comma, single quotes, a comment, or smart quotes from chat. The error line is the shortest path. Fix that character and parse again.'],
            ['Does Shehanly upload my JSON?', 'No. Parse and print run in the browser. Watch the Network tab if you want proof.'],
            ['Is minified JSON faster for my API?', 'Smaller body, yes. The CPU cost of parse is almost the same. Minify when size or a stable hash matters. Beautify when a human has to read it.'],
        ],
    ],
    'hash-generator-guide' => [
        'slug' => 'hash-generator-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Hash Generator Guide',
        'published' => '2026-09-02',
        'title' => 'How to Generate MD5 and SHA-256 Hashes Without Uploading the File (2026)',
        'h1' => 'How to generate MD5 and SHA-256 hashes without uploading the file',
        'description' => 'A 2026 guide to hashing text and files in the browser: when MD5 is still useful, why SHA-1 is dead for security, how SHA-256 checksums verify a download, and why an online hash tool must never send your file to a server.',
        'keywords' => 'md5 hash online, sha256 checksum, hash generator no upload, file checksum browser, sha-512 hash, verify download hash, shehanly',
        'intro' => 'A hash is a fingerprint, not a lock. The moment a website asks you to upload a confidential PDF so it can print 32 hex characters, you have given away the document. This guide shows how to hash text and files in the tab, pick the right algorithm, and verify a download without sending the bytes anywhere.',
        'body' => [
            'Last updated: 2 September 2026. Written for developers, sysadmins, CTF players and anyone who just downloaded an ISO and wants to know whether the file matches the publisher checksum.',
            ['h2' => 'What a hash actually is'],
            'A cryptographic hash takes any input and returns a fixed-length digest. The same input always produces the same output. Change one bit and the digest looks unrelated. You cannot reverse a hash to recover the file. That is the point.',
            'MD5 is 128 bits. SHA-1 is 160 bits. SHA-256 is 256 bits. SHA-512 is 512 bits. Longer is not automatically better for every job, but it is safer when the digest is used as a security control. A checksum for did-this-download-match is a different job from store-this-password.',
            ['h2' => 'Why most online hash sites are a bad idea'],
            'Plenty of hash generators look harmless. You drop a file, they print MD5. What they do not advertise is that the file just travelled to a server you do not control. A contract PDF, a customer export, a private key backup, a disk image with real data is now a copy on someone else disk, even if only for a minute.',
            'Some sites keep a history of recent hashes. Some log filenames. A few wrap the result in ads and a share-this-checksum button that posts the digest next to the original filename. A digest of a unique document can still identify that document.',
            ['h2' => 'The safe pattern: hash in the tab with Web Crypto'],
            'Shehanly hashes text and files in the browser. SHA-1, SHA-256 and SHA-512 use the Web Crypto API. MD5 uses a small local implementation because browsers refuse to expose a broken algorithm on purpose. There is no upload. Watch the Network tab while you drop a file. Nothing should leave the page.',
            ['link' => ['href' => '/hash-generator', 'text' => 'Open the browser hash generator']],
            ['h2' => 'A 60-second workflow to verify a download'],
            ['ul' => [
                'Copy the official checksum from the publisher. Prefer SHA-256 or SHA-512. Treat an MD5-only page as a hint, not a guarantee.',
                'Open the generator on shehanly.com. Confirm the URL.',
                'Drop the downloaded file. Do not paste a secret into the text box if a file input will do.',
                'Compare the digest character by character. Case does not matter. Spaces do.',
                'If the hashes differ, delete the file. Do not run the installer just to see. A mismatch is the whole warning.',
                'Close the tab. The file never left your machine.',
            ]],
            ['link' => ['href' => '/hash-generator', 'text' => 'Hash the file locally now']],
            ['h2' => 'When to use each algorithm'],
            ['ul' => [
                'MD5: legacy checksums and old software manifests. Collision attacks are practical. Do not use it to prove authenticity.',
                'SHA-1: dying. Use it only to match an old published digest.',
                'SHA-256: the default in 2026. Git, package registries, Linux ISOs and most vendor pages publish it. Use this first.',
                'SHA-512: extra margin on large files and long-lived archives. Still instant in the browser for anything you would email.',
            ]],
            'If a vendor still publishes only MD5, hash with MD5 to match their page, then hash again with SHA-256 and keep that digest in your own notes.',
            ['h2' => 'Text hashes versus file hashes'],
            'Hashing a string and hashing a file are the same math with different bytes. Newlines matter. If a published digest does not match, check encoding first: UTF-8 versus UTF-16, CRLF versus LF.',
            'Never hash a live production password in a public tab on a shared computer. The digest is not the secret, but the input field still holds the secret.',
            ['h2' => 'What a hash tool must never do'],
            ['ul' => [
                'It must not upload the file to print a digest. The CPU in your laptop can do this.',
                'It must not keep a public leaderboard of recent hashes.',
                'It must not call the digest encryption. Hashing is not reversible. Encryption is.',
                'It must not offer to email you the result.',
                'It must not store the file in localStorage as a convenience feature.',
            ]],
            'A fast test: drop a 1 KB dummy file, open DevTools, watch Network. If a multipart upload fires, close the tab.',
            ['h2' => 'Checksums are not signatures'],
            'A matching SHA-256 proves the file matches the bytes that produced the published digest. It does not prove who published the digest. If the download page and the checksum sit on the same compromised server, both can lie together.',
            'When a vendor publishes SHA256SUMS and a signature file, verify the signature first, then the hash. The browser hasher does the second half. The first half belongs in GnuPG or a local CLI you trust.',
            ['h2' => 'Pair it with the rest of the stack'],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'Decode a JWT in the browser without leaking the token']],
            ['link' => ['href' => '/base64', 'text' => 'Base64 encode or decode in the tab']],
            ['link' => ['href' => '/json-formatter', 'text' => 'Format JSON locally before you hash it']],
            ['h2' => 'Why this post sits next to the tool'],
            'People search md5 hash and sha256 checksum because a download finished and they want a yes or no. The honest page tells them which algorithm still counts, why the file must stay in the tab, and then hands them the generator. That is the Shehanly pattern: rank for the job, teach the risk, finish the job.',
            ['link' => ['href' => '/hash-generator', 'text' => 'Generate MD5, SHA-256 and SHA-512 locally']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Is hashing a file the same as encrypting it?', 'No. A hash is a one-way fingerprint. Anyone can compute the same digest from the same file. Encryption hides the file and needs a key to reverse.'],
            ['Is MD5 safe in 2026?', 'Not for security. Use it only when you must match an old published checksum. Prefer SHA-256 for new work.'],
            ['Does Shehanly upload my file to hash it?', 'No. SHA family hashes use the Web Crypto API in your browser. MD5 is computed locally. Watch the Network tab if you want proof.'],
            ['Why does my hash not match the website?', 'Different algorithm, a partial download, a trailing newline in text, or a page that published the digest of a different build. Re-download and compare SHA-256 first.'],
        ],
    ],
];
