<?php
/** 16 Sep 2026 post. Loaded after pages-sept15.php so the blog index and this article win. */
return [
    'blog' => [
        'slug' => 'blog',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Blog',
        'title' => 'Shehanly Blog - Privacy-First Tools, Security & Everyday Workflows',
        'h1' => 'The Shehanly blog',
        'description' => 'Practical guides on using free online tools without leaking data, converting documents safely, generating strong passwords and working faster with developer utilities.',
        'keywords' => 'shehanly blog, private online tools, free developer tools guides, password security, pdf converter safety, jwt decoder, disposable email, base64 encode decode, ai text summarizer, ai code explainer, client side tools',
        'intro' => 'Short, practical articles from the builder of Shehanly. No fluff. Each post solves one problem and points you at the free tool that does the work.',
        'body' => [
            ['h2' => 'Latest posts'],
            'New writing ships here first. Every article is written to rank, to teach, and to send you back into a tool you can actually use.',
            ['link' => ['href' => '/base64-is-not-encryption-guide', 'text' => 'Base64 is not encryption: how to decode a blob without leaking it (16 Sep 2026)']],
            ['link' => ['href' => '/verify-download-hash-guide', 'text' => 'How to verify a downloaded file with SHA-256 before you run it (15 Sep 2026)']],
            ['link' => ['href' => '/phishing-url-check-guide', 'text' => 'How to decode a suspicious URL without visiting it (14 Sep 2026)']],
            ['link' => ['href' => '/client-file-workflow-guide', 'text' => 'How to process a client file online without leaking it (13 Sep 2026)']],
            ['link' => ['href' => '/browser-only-tools-guide', 'text' => 'Which Shehanly tools stay in your browser, and which ones do not (12 Sep 2026)']],
            ['link' => ['href' => '/code-explainer-guide', 'text' => 'How to explain code online without leaking your source (11 Sep 2026)']],
            ['link' => ['href' => '/text-summarizer-guide', 'text' => 'How to summarize an article online without creating an account (10 Sep 2026)']],
            ['link' => ['href' => '/word-counter-guide', 'text' => 'How to count words and reading time without uploading your draft (9 Sep 2026)']],
            ['link' => ['href' => '/barcode-generator-guide', 'text' => 'How to generate a barcode without uploading your product data (8 Sep 2026)']],
            ['link' => ['href' => '/ip-dns-lookup-guide', 'text' => 'How to look up DNS and IP data without leaking the domain you are investigating (7 Sep 2026)']],
            ['link' => ['href' => '/url-encoder-guide', 'text' => 'How to URL encode and decode without leaking the query string (6 Sep 2026)']],
            ['link' => ['href' => '/base64-guide', 'text' => 'How to encode and decode Base64 without uploading the payload (5 Sep 2026)']],
            ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'How to convert Word to PDF online without leaking the document (4 Sep 2026)']],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'How to format and validate JSON without sending the payload (3 Sep 2026)']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'How to generate MD5 and SHA-256 hashes without uploading the file (2 Sep 2026)']],
            ['link' => ['href' => '/qr-code-guide', 'text' => 'How to generate a QR code without uploading your data (1 Sep 2026)']],
            ['link' => ['href' => '/temp-mail-guide', 'text' => 'How to use a disposable email without leaking your real inbox (31 Aug 2026)']],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'How to decode a JWT in your browser without leaking the token (30 Aug 2026)']],
            ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How to convert a PDF to Word online without leaking the file (29 Aug 2026)']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'How to generate a strong password in your browser (27 Aug 2026)']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data (26 Aug 2026)']],
            ['link' => ['href' => '/education-guides', 'text' => 'Education guides: Excel, Word, PowerPoint and defensive security literacy']],
            'Want a topic covered next? Use the Contact page and say exactly what you were trying to do when a random tool site made you hesitate.',
        ],
        'faq' => [
            ['How often is the blog updated?', 'New posts go up when there is a real problem worth solving, not on a fake daily calendar.'],
            ['Are these posts sales pages?', 'No. The tools stay free. The writing exists to teach and to earn search traffic the honest way.'],
        ],
    ],
    'base64-is-not-encryption-guide' => [
        'slug' => 'base64-is-not-encryption-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Base64 Is Not Encryption',
        'published' => '2026-09-16',
        'title' => 'Base64 Is Not Encryption: How to Decode a Blob Without Leaking It (2026)',
        'h1' => 'Base64 is not encryption: how to decode a blob without leaking it',
        'description' => 'A 2026 defensive guide to spotting Base64, decoding it in the browser, and stopping the habit of treating encoded text as a secret. No upload, no account, no "encrypted" marketing. Pair with the Shehanly Base64 tool.',
        'keywords' => 'base64 is not encryption, decode base64 online private, base64 vs encryption, decode base64 in browser, base64 jwt header, shehanly base64, encode decode base64 no upload',
        'intro' => 'A string of A-Z, a-z, 0-9, plus and slash with an equals sign at the end is not a lock. It is packaging. This page is the short loop: recognise the blob, decode it in the tab, read what was always in plaintext, and stop pasting "secrets" into random sites.',
        'body' => [
            'Last updated: 16 September 2026. Written for developers, support teams, and anyone who just got a "encrypted token" in Slack that is actually Base64. This is defensive literacy. It is not a guide to hiding malware, obfuscating stolen data, or pretending encoding is a control.',
            ['h2' => 'Encoding moves bytes. Encryption hides them.'],
            'Base64 exists so binary can travel through systems that only like text: email bodies, JSON strings, HTML attributes, config files. The algorithm is public. The alphabet is public. Anyone with the string can reverse it. That is the design, not a bug.',
            'Encryption needs a key you do not publish next to the ciphertext. AES, age, Signal, a password manager vault: those hide bytes from people who lack the key. Base64 does not. If you can decode it in a tab with no password prompt, it was never a secret.',
            ['link' => ['href' => '/base64', 'text' => 'Open the browser Base64 encoder / decoder']],
            ['link' => ['href' => '/base64-guide', 'text' => 'How the Base64 tool works, and why the payload never uploads']],
            ['h2' => 'How to recognise Base64 in the wild'],
            'You do not need a scanner. You need a pattern.',
            ['ul' => [
                'Charset: A-Z, a-z, 0-9, +, /. URL-safe variants swap in - and _. That is still Base64.',
                'Padding: zero, one, or two = characters at the end. Missing padding is common. It is still Base64.',
                'Length: the raw string length is almost always a multiple of 4 after padding.',
                'A JWT has two dots and three Base64url segments. The header almost always decodes to {"alg":...}.',
                'data:image/png;base64, is an image, not a password. The comma is the split. Everything after it is the file.',
            ]],
            'If a teammate says the field is encrypted and you can paste it into a decoder with no key, the teammate is wrong. Fix the language before you fix the ticket.',
            ['h2' => 'Step 1: decode in the tab, not on a stranger\'s form'],
            'Search decode base64 and the first results look harmless. Paste, click, copy. Plenty of those pages POST the textarea. A session cookie, a Basic auth header, a customer export wrapped for transport is now a copy on a box you do not run.',
            'The Shehanly decoder runs in the browser. Watch Network while you paste. You should see static assets only.',
            ['ul' => [
                'Confirm the address bar is shehanly.com/base64.',
                'Paste the blob. Do not include the data: prefix if you only want the bytes.',
                'Decode. Read the output as text first. If it is binary, you will see noise. That is expected.',
                'If the output is JSON, take it to the local formatter next. Do not bounce through a second cloud toy.',
            ]],
            ['link' => ['href' => '/base64', 'text' => 'Decode the blob without uploading it']],
            ['link' => ['href' => '/json-formatter', 'text' => 'Pretty-print the decoded JSON in the same tab stack']],
            ['h2' => 'Step 2: name what you actually decoded'],
            'The job is not "make it readable." The job is "know what this field is so you stop treating it as a control."',
            ['ul' => [
                'A username:password pair after Basic is still a password. The word Basic is the giveaway. Rotate it. Do not commit it.',
                'A JWT payload is claims, not a vault. Expiry, subject, issuer live in plaintext on purpose. Verify the signature elsewhere. Decoding is not verifying.',
                'A PEM body between BEGIN and END lines is often Base64 already. Decoding it again is how people corrupt a key file.',
                'An image or PDF will not read as English. Stop. You decoded a file, not a message.',
            ]],
            'If the decoded text contains an access token, a cookie, or a customer email, the leak already happened when the Base64 string was shared. The decoder did not create the leak. The Slack paste did.',
            ['h2' => 'A 40-second workflow when someone says the field is encrypted'],
            ['ul' => [
                'Look at the charset. If it is the Base64 alphabet, assume encoding until proven otherwise.',
                'Open shehanly.com/base64. Confirm the URL.',
                'Paste. Decode. Read.',
                'If you get readable JSON, headers, or a login pair, it was not encryption. Say that in the ticket.',
                'If you get garbage and there was a key or passphrase in the spec, stop using a Base64 toy. You need the real decrypt path.',
                'Close the tab. Do not leave a production token sitting in a textarea on a shared laptop.',
            ]],
            ['link' => ['href' => '/base64', 'text' => 'Decode it locally now']],
            ['h2' => 'What Base64 does not prove'],
            ['ul' => [
                'It does not prove the data is confidential. Anyone can decode it.',
                'It does not prove integrity. Change one character and you get different bytes, but there is no publisher checksum in the encoding itself.',
                'It does not replace HTTPS. TLS is the transport lock. Base64 is the envelope inside the truck.',
                'It does not make a password safe to email. Encoding a password is still emailing a password.',
            ]],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'Need a fingerprint instead of a disguise? Hash the bytes in the tab']],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'If the blob has two dots, decode the JWT properly']],
            ['h2' => 'The mistakes that still get teams'],
            ['ul' => [
                'Calling a Base64 config value encryption in a security review. Auditors will decode it in front of you.',
                'Pasting a production token into the first Google result for decode base64.',
                'Double-encoding until the string looks "more random." Longer is not stronger.',
                'Storing passwords as Base64 in a database and calling it hashing. Hashing is one-way. Base64 is not.',
                'Shipping a "secret" in a mobile app as a Base64 string and hoping nobody opens DevTools.',
            ]],
            ['h2' => 'Pair this check with the rest of the stack'],
            ['link' => ['href' => '/base64', 'text' => 'Encode or decode Base64 in the tab']],
            ['link' => ['href' => '/jwt-decoder', 'text' => 'Decode a JWT without sending the token']],
            ['link' => ['href' => '/json-formatter', 'text' => 'Format the decoded JSON locally']],
            ['link' => ['href' => '/url-encoder', 'text' => 'Percent-decode a query string that wrapped the blob']],
            ['link' => ['href' => '/hash-generator', 'text' => 'Hash the original or decoded bytes without an upload']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
            ['h2' => 'Why this post sits next to the tools'],
            'People search is base64 encryption and decode base64 online because a blob landed in a ticket and someone used the wrong word. The useful page tells them encoding is not a lock, shows the pattern, and hands them a decoder that never leaves the tab. That is the Shehanly pattern. Rank for the job. Teach the risk. Finish the job.',
            ['link' => ['href' => '/base64', 'text' => 'Decode Base64 in your browser']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Is Base64 encryption?', 'No. Base64 is an encoding. Anyone with the string can reverse it. Encryption needs a key you do not publish next to the ciphertext.'],
            ['Does Shehanly upload the blob I paste?', 'No. Encode and decode run in the browser. Watch the Network tab if you want proof.'],
            ['Why do so many tokens look like Base64?', 'Because JSON and HTTP like text. JWTs, Basic auth, and data URLs wrap bytes in Base64 so they can travel. The wrapping is not the protection.'],
            ['Can I use Base64 to hide a password in a repo?', 'No. Treat a Base64 password as a plaintext password. Use a secrets manager or a real encrypt-at-rest design.'],
            ['What if decode produces garbage?', 'You may have the wrong alphabet, missing padding, or actual ciphertext. Do not keep rerunning a Base64 tool against a locked payload.'],
        ],
    ],
];
