<?php
return [
    'ip-dns-lookup-guide' => [
        'slug' => 'ip-dns-lookup-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'DNS Lookup Guide',
        'published' => '2026-09-07',
        'title' => 'How to Look Up DNS and IP Data Without Leaking the Domain You Are Investigating (2026)',
        'h1' => 'How to look up DNS and IP data without leaking the domain you are investigating',
        'description' => 'A 2026 guide to A, AAAA, MX, TXT, NS and CAA lookups plus IP geolocation: why random whois sites log the domain you type, how a server-side resolver should work, and a 45-second workflow for authorized recon only.',
        'keywords' => 'dns lookup online, mx record checker, ip geolocation, nslookup online, txt record lookup, caa record, whois alternative, shehanly',
        'intro' => 'A domain lookup looks public until you remember the context. A pre-launch hostname, a client staging box, a brand you have not announced, an IP that belongs to an incident you are handling. The moment a random whois site logs that query next to your IP, the investigation is no longer only yours. This guide shows how to read public DNS and IP data through a proxy that rejects private ranges, what the records actually mean, and why this work stays legal only when the target is public or you have written authorization.',
        'body' => [
            'Last updated: 7 September 2026. Written for developers, sysadmins, support engineers and anyone doing authorized, defensive recon. Public DNS is public. Guessing passwords, bypassing auth, or scanning a network you do not own is a different job and it is not this page.',
            ['h2' => 'What a DNS lookup actually returns'],
            'DNS is the phone book of the internet. You ask a resolver for a name. It answers with records. The common ones you will actually use:',
            ['ul' => [
                'A: IPv4 address of a host.',
                'AAAA: IPv6 address of the same host.',
                'CNAME: an alias. Follow it until you hit an A or AAAA.',
                'MX: mail servers and their priority. Lower number is tried first.',
                'TXT: free text. SPF, DKIM, DMARC, domain verification tokens and the occasional leftover secret people should not have published.',
                'NS: the authoritative name servers for the zone.',
                'SOA: serial, refresh and the mailbox that owns the zone.',
                'CAA: which certificate authorities are allowed to issue for the name.',
            ]],
            'None of that is a vulnerability by itself. It is the public contract the domain owner published. Your job is to read it without adding a third party to the conversation.',
            ['h2' => 'Why most online lookup sites are a leak'],
            'Search dns lookup and the first results look like a terminal in a browser. Type a hostname, get records. What they hide is the log. The domain you typed, your IP, the time, sometimes a shareable /lookup/example.com page that stays in their sitemap.',
            'That is fine when the name is google.com. It is not fine when the name is a client staging host, a not-yet-announced product subdomain, or an IP from an incident ticket. Some sites wrap the result in ads and a Recent lookups list. A unique hostname is identifying even after you close the tab.',
            'WHOIS is worse. Registrars already publish a lot. Random whois front-ends add another copy of the query and often scrape contact fields you did not need.',
            ['h2' => 'The safe pattern: resolve on a server you control, never follow private ranges'],
            'A browser cannot run a real recursive lookup the way a public resolver can. ISP cache, split horizon, and stale TTL will lie to you. Shehanly therefore resolves on the server with dns_get_record and a DNS-over-HTTPS fallback. You see what a public resolver sees, not what your hotel Wi-Fi cached.',
            'The proxy rejects RFC1918, loopback and link-local addresses. That is not a feature for attackers. It is SSRF hygiene. A lookup tool that will fetch 127.0.0.1 or 169.254.169.254 is a hole, not a utility.',
            ['link' => ['href' => '/ip-dns-lookup', 'text' => 'Open the IP and DNS lookup']],
            ['h2' => 'A 45-second workflow when a hostname looks wrong'],
            ['ul' => [
                'Copy the hostname only. Strip https://, paths, query strings and a trailing slash.',
                'Open the lookup on shehanly.com. Confirm the URL.',
                'Paste the name. Read A and AAAA first. Then MX if mail is the question. Then TXT if deliverability or a verification token is the question.',
                'If you have an IP instead of a name, look up geolocation and ASN. Treat city-level geo as a hint, not a courtroom fact.',
                'Compare NS and SOA if you suspect a migration or a hijack of nameservers.',
                'Close the tab. You now have the public records. You do not have a second company log of the query sitting next to your home IP.',
            ]],
            ['link' => ['href' => '/ip-dns-lookup', 'text' => 'Look up the records now']],
            ['h2' => 'How to read the records without inventing a story'],
            ['ul' => [
                'Two A records is usually load balancing or a dual-homed host, not a compromise.',
                'A CNAME to a CDN is normal. Follow it. The edge IP will change. That is the product.',
                'MX pointing at Google or Microsoft is expected for those tenants. MX pointing at a random VPS is a finding if the business thinks mail is hosted elsewhere.',
                'A TXT record that starts v=spf1 is mail policy. A missing or p=none DMARC record is weak policy, not proof of a breach.',
                'CAA that lists only one CA means a different CA should refuse to issue. Empty CAA means any CA can issue.',
                'SOA serial that never moves can mean a forgotten zone. It can also mean a hidden primary. Do not guess. Ask the owner.',
            ]],
            'GeoIP is a database guess. A cloud anycast address will show a city that is not where the workload lives. ASN tells you the network operator. That is usually more honest than the city field.',
            ['h2' => 'The errors that waste an afternoon'],
            ['ul' => [
                'Looking up the URL instead of the host. dns_get_record does not want https://app.example.com/login.',
                'Trusting your laptop resolver. Corporate DNS and split horizon will show internal answers that the public internet never sees.',
                'Treating a 24-hour TTL as instant. Old records linger until the TTL dies. Wait, or query an authoritative NS directly.',
                'Confusing WHOIS contacts with DNS. The registrar record and the zone file are different databases.',
                'Calling this a port scan. A DNS lookup is not nmap. Do not slide from public records into unsolicited probing.',
            ]],
            'If the tool returns nothing, the name may not exist, the resolver timed out, or you pasted a private IP the proxy correctly refused. Check the input before you blame the site.',
            ['h2' => 'Legal line. Read it twice.'],
            ['ul' => [
                'Public DNS and public IP metadata are public. Reading them is normal operations and normal due diligence.',
                'You need written authorization before you scan ports, brute credentials, or test a system that is not yours.',
                'Do not use lookup results to harass, dox, or impersonate anyone.',
                'Do not feed the tool RFC1918 addresses hoping it will reach an internal host. It will refuse. That is the design.',
            ]],
            'Shehanly is a utility, not a red-team platform. The education guides cover defensive OSINT literacy. This post covers the lookup itself.',
            ['h2' => 'What a lookup tool must never do'],
            ['ul' => [
                'It must not log the queried name next to your IP in a public recent list.',
                'It must not follow redirects into 127.0.0.1, 10.0.0.0/8, 192.168.0.0/16 or cloud metadata IPs.',
                'It must not claim WHOIS privacy stripping is a hack.',
                'It must not ask you to create an account to see MX records.',
                'It must not wrap the result in a share link that indexes the hostname.',
            ]],
            'A fast test: look up example.com, open DevTools, watch Network. You should see a request to this domain only. If the browser posts the hostname to a third-party whois API with a key in JavaScript, close the tab.',
            ['h2' => 'Pair it with the rest of the stack'],
            ['link' => ['href' => '/url-encoder-guide', 'text' => 'Percent-decode a hostname that arrived inside a query string']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'Hash a zone file or export without uploading it']],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'Pretty-print a DNS-over-HTTPS JSON response']],
            ['link' => ['href' => '/education-guides', 'text' => 'Defensive OSINT literacy: what is public and what is not']],
            ['h2' => 'Why this post sits next to the tool'],
            'People search dns lookup because a hostname failed, mail bounced, or a certificate question showed up in a ticket. The honest page tells them the query itself can be sensitive, which records matter, where the legal line is, and then hands them the tool. That is the Shehanly pattern: rank for the job, teach the risk, finish the job.',
            ['link' => ['href' => '/ip-dns-lookup', 'text' => 'Look up DNS records and IP data']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Is a DNS lookup hacking?', 'No. Reading public DNS is normal. Scanning, exploiting or accessing systems without authorization is a different act and it is illegal in most places.'],
            ['Why do results differ from my terminal?', 'Propagation and cache. Your ISP resolver, a public resolver and the authoritative NS can disagree until the old TTL expires.'],
            ['Can I look up private IPs?', 'No. RFC1918, loopback and link-local addresses are rejected so the proxy cannot be used for SSRF.'],
            ['Does Shehanly keep a history of names I searched?', 'There is no account and no public recent-lookups list. The resolver runs on the server because a browser cannot be a public recursive resolver. The name is not turned into a share page.'],
        ],
    ],
];
