<?php
/** Extra blog posts merged after config/pages.php */
return [
         'blog' => [
             'slug' => 'blog',
             'category' => 'Guides',
             'type' => 'page',
             'nav' => 'Blog',
             'title' => 'Shehanly Blog - Privacy-First Tools, Security & Everyday Workflows',
             'h1' => 'The Shehanly blog',
             'description' => 'Practical guides on using free online tools without leaking data, converting documents safely, generating strong passwords and working faster with developer utilities.',
             'keywords' => 'shehanly blog, private online tools, free developer tools guides, password security, pdf converter safety, jwt decoder, disposable email, base64 encode decode',
             'intro' => 'Short, practical articles from the builder of Shehanly. No fluff. Each post solves one problem and points you at the free tool that does the work.',
             'body' => [
                 ['h2' => 'Latest posts'],
                 'New writing ships here first. Every article is written to rank, to teach, and to send you back into a tool you can actually use.',
                 ['link' => ['href' => '/word-counter-guide', 'text' => 'How to count words and reading time without uploading your draft (9 Sep 2026)']],
                 ['link' => ['href' => '/barcode-generator-guide', 'text' => 'How to generate a barcode without uploading your product data (8 Sep 2026)']],
                 ['link' => ['href' => '/ip-dns-lookup-guide', 'text' => 'How to look up DNS and IP data without leaking the domain you are investigating (7 Sep 2026)']],
                 ['link' => ['href' => '/url-encoder-guide', 'text' => 'How to URL encode and decode without leaking the query string (6 Sep 2026)']],
                 ['link' => ['href' => '/base64-guide', 'text' => 'How to encode and decode Base64 without uploading the payload (5 Sep 2026)']],
                 ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'How to convert Word to PDF online without leaking the document (4 Sep 2026)']],
                 ['link' => ['href' => '/json-formatter-guide', 'text' => 'How to format and validate JSON without sending the payload (3 Sep 2026)']],
                 ['link' => ['href' => '/hash-generator-guide', 'text' => 'How to generate MD5 and SHA-256 hashes without uploading the file (2 Sep 2026)']],
                 ['link' => ['href' => '/qr-code-guide', 'text' => 'How to generate a QR code without uploading your data (1 Sep 2026)']],
                 ['link' => ['href' => '/temp-mail-guide', 'text' => 'How to use a disposable email without leaking your real inbox (31 Aug 2026)']],
                 ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'How to decode a JWT in your browser without leaking the token (30 Aug 2026)']],
                 ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How to convert a PDF to Word online without leaking the file (29 Aug 2026)']],
                 ['link' => ['href' => '/strong-password-guide', 'text' => 'How to generate a strong password in your browser (27 Aug 2026)']],
                 ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data (26 Aug 2026)']],
                 ['link' => ['href' => '/education-guides', 'text' => 'Education guides: Excel, Word, PowerPoint and defensive security literacy']],
                 'Want a topic covered next? Use the Contact page and say exactly what you were trying to do when a random tool site made you hesitate.'
             ],
             'faq' => [
                 ['How often is the blog updated?', 'New posts go up when there is a real problem worth solving, not on a fake daily calendar.'],
                 ['Are these posts sales pages?', 'No. The tools stay free. The writing exists to teach and to earn search traffic the honest way.'],
             ],
         ],
    'word-counter-guide' => [
        'slug' => 'word-counter-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Word Counter Guide',
        'published' => '2026-09-09',
        'title' => 'How to Count Words and Reading Time Without Uploading Your Draft (2026)',
        'h1' => 'How to count words and reading time without uploading your draft',
        'description' => 'A 2026 guide to counting words, characters, sentences and reading time in the browser: why pasting a client draft into a random counter is a leak, how speaking time differs from reading time, and a 20-second workflow that never leaves the tab.',
        'keywords' => 'word counter online, character counter no upload, reading time calculator, speaking time estimator, count words privately, blog word count, shehanly',
        'intro' => 'A draft looks harmless until you remember what is in it. A client name. A product launch date. A school essay that is not submitted yet. The moment a word counter posts that text so it can print a number, the draft is no longer only yours. This guide shows how to count words, characters, sentences and reading time in the tab, pick an honest words-per-minute figure, and keep the manuscript on your machine.',
        'body' => [
            'Last updated: 9 September 2026. Written for students, freelancers, YouTubers, conference speakers and anyone who just finished a draft and needs a number before they hit send.',
            ['h2' => 'What a word counter actually does'],
            'It splits text into words, characters, sentences and paragraphs, then estimates how long a human will take to read or speak it. The count is not philosophy. It is a gate: assignment limits, SEO briefs, ad copy boxes, talk slots, Substack paywalls, university portals that reject 2501 words.',
            'None of those jobs need a server. String splitting runs in every browser. A local counter is a thin UI over Unicode-aware boundaries plus a clock.',
            ['h2' => 'Why most online word counters are a leak'],
            'Search word counter and the first results look identical. Paste, watch a number tick. What they hide is a form post. A client proposal, an unreleased chapter, a complaint letter with real names is now a copy on a box you do not run.',
            'Some tools keep Recent pastes. Some wrap the result in a share link. A unique draft is identifying even after you close the tab. Students paste essays into counters every week. That is how unpublished work leaves the laptop without a breach ticket.',
            ['h2' => 'The safe pattern: count in the tab'],
            'Shehanly counts words, characters with and without spaces, sentences, paragraphs and unique words in the browser. Reading and speaking time update as you type. Nothing is posted. Watch the Network panel while you paste a dummy paragraph. You should see static assets only.',
            ['link' => ['href' => '/word-counter', 'text' => 'Open the browser word counter']],
            ['h2' => 'A 20-second workflow when the limit is the only question'],
            ['ul' => [
                'Copy the draft from Word, Docs, Notion or a script file. Do not copy the comments pane unless those comments are going to the reader.',
                'Open the counter on shehanly.com. Confirm the URL.',
                'Paste. Read words first. Then characters if a form has a hard cap.',
                'Set reading speed to 200 wpm for careful prose, 230 for a blog, 250 to 300 for skimming. Speaking time is slower. Use 130 to 150 wpm for a talk.',
                'If you are over the limit, cut in the original file. Counting twice will not invent a shorter draft.',
                'Close the tab. The paste never left the machine.',
            ]],
            ['link' => ['href' => '/word-counter', 'text' => 'Count the draft locally now']],
            ['h2' => 'Reading time versus speaking time'],
            ['ul' => [
                'Silent reading of clean prose sits near 200 to 250 words per minute for most adults.',
                'Skimming a listicle is faster. Dense legal or academic text is slower.',
                'Spoken delivery is not reading. A conference talk at 160 wpm sounds rushed. 130 to 150 leaves room to breathe.',
                'YouTube hooks are shorter than they feel. A 15-second spoken line is roughly 35 to 40 words, not 80.',
            ]],
            'If the slot is eight minutes, do not paste a 2,400-word essay and hope. That is sixteen minutes at a sane pace. Cut before you step on stage.',
            ['h2' => 'What the number actually means'],
            ['ul' => [
                'Words: the limit most editors and portals care about.',
                'Characters with spaces: Twitter-era caps, SMS, some ad networks.',
                'Characters without spaces: rarer, but some academic portals still use it.',
                'Sentences and paragraphs: a smell test. One 900-word paragraph is not a blog post. It is a wall.',
                'Unique words: a rough vocabulary check, not a plagiarism score.',
            ]],
            'Keyword density is a hint, not a strategy. Stuffing a phrase to please a counter will not please a reader.',
            ['h2' => 'The errors that waste an afternoon'],
            ['ul' => [
                'Pasting the title, tags and body together, then wondering why the assignment is 40 words over.',
                'Counting a bibliography you will not read aloud.',
                'Trusting Word desktop, Google Docs and an online counter to agree. They split hyphenated words and URLs differently. Pick one source of truth for the portal you are submitting to.',
                'Using reading time as speaking time. They are different clocks.',
                'Pasting a PDF extract full of hyphenation artifacts. Rejoin broken words first or the count lies.',
            ]],
            'If two tools disagree by twenty words on a 3,000-word draft, that is noise. If they disagree by four hundred, you pasted different text.',
            ['h2' => 'What a word counter must never do'],
            ['ul' => [
                'It must not POST the textarea to print a number.',
                'It must not create a public /p/abc123 link of your last paste.',
                'It must not auto-save the draft to an account you did not ask for.',
                'It must not call itself an AI editor while shipping the manuscript to a model.',
                'It must not phone home with a sample sentence for product analytics.',
            ]],
            'A fast test: paste "probe draft", open DevTools, watch Network. If a request carries the sentence, close the tab.',
            ['h2' => 'Pair it with the rest of the stack'],
            ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'Freeze the finished draft to PDF without leaking the file']],
            ['link' => ['href' => '/text-summarizer', 'text' => 'Summarize a long draft in the AI tool when you need a short brief']],
            ['link' => ['href' => '/qr-code-guide', 'text' => 'Put a QR code on the last page of a handout']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'Generate a strong password if the CMS login is next']],
            ['h2' => 'Why this post sits next to the tool'],
            'People search word counter because a limit is the only thing standing between a draft and a submit button. The honest page tells them the paste is often unpublished work, why the count must stay in the tab, which clock to use for a talk versus a blog, and then hands them the tool. That is the Shehanly pattern: rank for the job, teach the risk, finish the job.',
            ['link' => ['href' => '/word-counter', 'text' => 'Count words, characters and reading time locally']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Does the word counter upload my draft?', 'No. Counting runs in the browser. Watch the Network tab if you want proof.'],
            ['Why does Word show a different number?', 'Hyphens, URLs, headings and footnotes are split differently. For a portal, use the same tool the marker will use. For your own limit, pick one counter and stay with it.'],
            ['What reading speed should I use?', '200 wpm for careful prose. 230 for a typical blog. 130 to 150 wpm for a spoken talk. Adjust if your audience is new to the topic.'],
            ['Is unique-word count the same as originality?', 'No. It only tells you how repetitive the vocabulary is. It is not a plagiarism check.'],
        ],
    ],
    'barcode-generator-guide' => [
        'slug' => 'barcode-generator-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Barcode Guide',
        'published' => '2026-09-08',
        'title' => 'How to Generate a Barcode Without Uploading Your Product Data (2026)',
        'h1' => 'How to generate a barcode without uploading your product data',
        'description' => 'A 2026 guide to CODE128, EAN-13, UPC-A and ITF-14 barcodes in the browser: why random barcode sites keep a copy of your SKU, how check digits work, and a 30-second workflow that never leaves the tab.',
        'keywords' => 'barcode generator online, ean-13 generator no upload, code128 barcode free, upc-a barcode maker, itf-14 carton barcode, generate barcode locally, shehanly',
        'intro' => 'A barcode looks like decoration until you remember what it encodes. A SKU that is not public yet. An internal lot number. A warehouse carton code. A pharmacy identifier. The moment a generator asks you to create an account so it can email you a PNG, that string is no longer only yours. This guide shows how to draw CODE128, EAN-13, UPC-A and ITF-14 in the tab, pick the right symbology, and export PNG or SVG without sending the value anywhere.',
        'body' => [
            'Last updated: 8 September 2026. Written for shop owners, warehouse teams, makers, event staff and anyone who needs a scannable code on a label without handing the catalog to a stranger.',
            ['h2' => 'What a barcode actually is'],
            'A barcode is a machine-readable spelling of a string. Bars and spaces stand in for digits or ASCII. A scanner reads the pattern, a check digit catches a mistype, and the till or warehouse app looks the number up in a database you already own.',
            'It is not encryption. Anyone with a phone camera can read it. Treat the value as public the moment the label is printed. The privacy problem is earlier: the generator should not keep a copy of a SKU you have not launched.',
            ['h2' => 'Pick the symbology before you pick the font size'],
            ['ul' => [
                'CODE128: the default for internal SKUs, tickets, asset tags and any ASCII string. It is compact and does not need a GS1 company prefix.',
                'CODE39: older, wider, still common on industrial labels. Fine when the scanner is old and the string is short.',
                'EAN-13: the retail number you see on a product box in most of the world. Twelve digits plus a check digit, or thirteen already including it.',
                'EAN-8: short retail codes for small packs. Seven or eight digits.',
                'UPC-A: the North American retail cousin of EAN-13. Eleven or twelve digits.',
                'ITF-14: carton and case codes. Thirteen or fourteen digits. Use it on the outer box, not the unit pack.',
                'Pharmacode: a niche binary code used on pharmaceutical packaging. Only use it when the line already expects it.',
            ]],
            'Wrong symbology is the number one wasted afternoon. An EAN-13 scanner will not treat your internal CODE128 SKU as a product. A till that expects UPC-A will reject a CODE128 drawing of the same digits.',
            ['h2' => 'Why most online barcode sites are a leak'],
            'Search barcode generator and the first results look identical. Type a number, download a PNG. What they hide is the rest of the funnel: a forced signup, a watermark unless you pay, a recent codes list tied to an email, or a share link that stays in their sitemap.',
            'A unique SKU is identifying even after you close the tab. A pre-launch catalog code sitting in someone else recent list is a leak. Some sites also log the value next to your IP so they can remarket label printers. That is not a utility. That is a lead form wearing a barcode.',
            ['h2' => 'The safe pattern: draw in the tab with JsBarcode'],
            'Shehanly renders the barcode in the browser. JsBarcode draws an SVG. You export PNG or SVG from that same drawing. Nothing is posted. Watch the Network panel while you type a dummy SKU. You should see static assets only.',
            ['link' => ['href' => '/barcode-generator', 'text' => 'Open the browser barcode generator']],
            ['h2' => 'A 30-second workflow when the label is due'],
            ['ul' => [
                'Decide the symbology first. Internal string: CODE128. Retail unit: EAN-13 or UPC-A. Outer carton: ITF-14.',
                'Open the generator on shehanly.com. Confirm the URL.',
                'Paste the value. For EAN-13 and UPC-A, twelve digits is enough. The library will compute the check digit.',
                'Set bar width and height to match the label stock. Thin bars on cheap paper will not scan.',
                'Keep human-readable text on unless the pack design already prints the number beside the code.',
                'Export SVG if the file is going into print software. Export PNG if you just need a sticker today.',
                'Scan the result with your own phone before you print two hundred copies.',
            ]],
            ['link' => ['href' => '/barcode-generator', 'text' => 'Generate the barcode locally now']],
            ['h2' => 'Check digits, quiet zones and the errors that waste an afternoon'],
            ['ul' => [
                'EAN-13 and UPC-A need the right digit count. Twelve digits plus check, or thirteen already including it. Fifteen digits is not a creative EAN.',
                'CODE128-C wants an even number of digits. If the string is mixed letters and numbers, stay on CODE128 auto.',
                'ITF and ITF-14 want even digit counts. Pad with a leading zero if the case code is short.',
                'Quiet zone is the white margin around the bars. Crop it in a slide deck and cheap scanners fail.',
                'Black on white still wins. Fancy brand colors look good in Figma and die under warehouse lights.',
                'A barcode is not a QR code. Do not encode a URL in CODE128 and expect a phone camera to open a page. Use the QR tool for URLs.',
            ]],
            'If the tool says the value does not satisfy the format, believe it. Fix the digit count. Do not keep widening the bars hoping a bad check digit becomes legal.',
            ['h2' => 'Barcode versus QR code'],
            'These are different jobs. A barcode encodes a short identifier for a scanner that already knows your catalog. A QR code encodes a URL, a Wi-Fi string or a block of text for a phone camera. Use a barcode on a product and a carton. Use a QR code on a poster, a menu or a setup card.',
            ['link' => ['href' => '/qr-generator', 'text' => 'Need a URL or Wi-Fi code instead? Open the QR generator']],
            ['link' => ['href' => '/qr-code-guide', 'text' => 'How to generate a QR code without uploading your data']],
            ['h2' => 'What a barcode tool must never do'],
            ['ul' => [
                'It must not force an account to return your own PNG.',
                'It must not stamp a watermark across the bars and call that a preview.',
                'It must not keep a public /codes/sku-123 page of the value you typed.',
                'It must not email the file to an address you typed in a hurry.',
                'It must not pretend a barcode is a secret. Encoding is not encryption.',
            ]],
            'A fast test: type TEST-001, open DevTools, watch Network. If a request carries the string, close the tab.',
            ['h2' => 'Print size that actually scans'],
            'A phone camera is forgiving. A supermarket laser is not. Give EAN-13 at least 25 mm of bar height on the pack. Give ITF-14 more. Do not shrink a CODE128 asset tag until the bars are a single pixel. Test one print on the real scanner before you run the batch.',
            'SVG scales. PNG does not. If the file is going into a label template that will be resized, export SVG.',
            ['h2' => 'Pair it with the rest of the stack'],
            ['link' => ['href' => '/qr-code-guide', 'text' => 'Generate a QR code in the browser when the payload is a URL']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'Hash a packing list without uploading the file']],
            ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'Freeze a label sheet to PDF after the codes are placed']],
            ['link' => ['href' => '/password-generator', 'text' => 'Generate a strong password if the inventory app needs a new login']],
            ['h2' => 'Why this post sits next to the tool'],
            'People search barcode generator because a label is due and a scanner is waiting. The honest page tells them the value can be sensitive before launch, which symbology matches the job, why the drawing must stay in the tab, and then hands them the tool. That is the Shehanly pattern: rank for the job, teach the risk, finish the job.',
            ['link' => ['href' => '/barcode-generator', 'text' => 'Generate CODE128, EAN-13, UPC-A or ITF-14 locally']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Does generating a barcode upload my SKU?', 'No. JsBarcode draws in the browser. Export is a local download. Watch the Network tab if you want proof.'],
            ['Which format should I use?', 'CODE128 for internal strings. EAN-13 or UPC-A for retail units. ITF-14 for cartons. Match what the scanner and the marketplace already expect.'],
            ['Do I need a GS1 prefix?', 'For a real retail EAN or UPC that will sit on a store shelf, yes. You buy the company prefix. For an internal CODE128 asset tag, no.'],
            ['PNG or SVG?', 'SVG for print templates that will be resized. PNG for a one-off sticker. Both come from the same local drawing.'],
        ],
    ],
];
