<?php
/** Extra blog posts merged after config/pages.php */
return [
         'blog' => [
             'slug' => 'blog',
             'category' => 'Guides',
             'type' => 'page',
             'nav' => 'Blog',
             'title' => 'Shehanly Blog - Privacy-First Tools, Security & Everyday Workflows',
             'h1' => 'The Shehanly blog',
             'description' => 'Practical guides on using free online tools without leaking data, converting documents safely, generating strong passwords and working faster with developer utilities.',
             'keywords' => 'shehanly blog, private online tools, free developer tools guides, password security, pdf converter safety, jwt decoder, disposable email',
             'intro' => 'Short, practical articles from the builder of Shehanly. No fluff. Each post solves one problem and points you at the free tool that does the work.',
             'body' => [
                 ['h2' => 'Latest posts'],
                 'New writing ships here first. Every article is written to rank, to teach, and to send you back into a tool you can actually use.',
                 ['link' => ['href' => '/qr-code-guide', 'text' => 'How to generate a QR code without uploading your data (1 Sep 2026)']],
                 ['link' => ['href' => '/temp-mail-guide', 'text' => 'How to use a disposable email without leaking your real inbox (31 Aug 2026)']],
                 ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'How to decode a JWT in your browser without leaking the token (30 Aug 2026)']],
                 ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How to convert a PDF to Word online without leaking the file (29 Aug 2026)']],
                 ['link' => ['href' => '/strong-password-guide', 'text' => 'How to generate a strong password in your browser (27 Aug 2026)']],
                 ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data (26 Aug 2026)']],
                 ['link' => ['href' => '/education-guides', 'text' => 'Education guides: Excel, Word, PowerPoint and defensive security literacy']],
                 'Want a topic covered next? Use the Contact page and say exactly what you were trying to do when a random tool site made you hesitate.'
             ],
             'faq' => [
                 ['How often is the blog updated?', 'New posts go up when there is a real problem worth solving, not on a fake daily calendar.'],
                 ['Are these posts sales pages?', 'No. The tools stay free. The writing exists to teach and to earn search traffic the honest way.'],
             ],
         ],
         'temp-mail-guide' => [
             'slug' => 'temp-mail-guide',
             'category' => 'Guides',
             'type' => 'page',
             'nav' => 'Temp Mail Guide',
             'published' => '2026-08-31',
             'title' => 'How to Use a Disposable Email Without Leaking Your Real Inbox (2026)',
             'h1' => 'How to use a disposable email without leaking your real inbox',
             'description' => 'A 2026 guide to disposable inboxes: when a 10-minute email is the right move, which sign-ups still demand your real address, and how to receive a verification code without handing a stranger your Gmail.',
             'keywords' => 'disposable email, 10 minute mail, temporary inbox, temp mail privacy, throwaway email address, shehanly temp mail',
             'intro' => 'A free trial, a one-time download, or a newsletter popup should not earn a permanent seat in your real inbox. A disposable address lets you receive the code and walk away. This guide shows when that is the right move, when it is not, and how to do it without leaking the mailbox that actually matters.',
             'body' => [
                 'Last updated: 31 August 2026. Written for anyone who is tired of spam from a site they used once, and for anyone who has watched a "free tool" ask for an email before it would even open the file.',
                 ['h2' => 'What a disposable inbox actually is'],
                 'A temporary email is a mailbox that exists long enough to catch one message. You generate an address, paste it into a form, wait for the verification mail, copy the code, and leave. The address is not yours. It is not a second identity. It is a one-shot inbox with a short clock.',
                 'Most public temp-mail sites expire in ten minutes. Some let you extend while the tab stays open. None of them should be used as a password-reset channel for an account you care about. When the inbox dies, so does your ability to recover that login.',
                 ['h2' => 'Why most "free email" landing pages are a bad idea'],
                 'A lot of disposable-mail sites show the inbox in a public stream. Anyone who guesses or refreshes the same address can read the same message. Some wrap ads around the mail body. Some sell the fact that you requested an address for a particular domain. A few require you to solve a captcha on every refresh, which is how they train their own abuse filters on your traffic.',
                 'The other failure mode is sending. If a temp-mail product lets you send mail, it will be used to spam. Serious providers stay receive-only. If a page offers a Compose button next to a 10-minute address, close it.',
                 ['h2' => 'The safe pattern: receive the code, never bind the account'],
                 'Use a disposable address when the other side only needs proof that an inbox exists. Do not use it when the other side will later send a password reset, an invoice, a 2FA code, or a legal notice. Those messages have to land somewhere you still control in six months.',
                 'Shehanly generates a receive-only inbox and polls it through a PHP proxy so the upstream mail provider never sees your browser IP. The default window is ten minutes. You can add another ten while the tab is open. There is no send button.',
                 ['link' => ['href' => '/temp-mail', 'text' => 'Open the 10-minute disposable inbox']],
                 ['h2' => 'A 60-second workflow for a one-time signup'],
                 ['ul' => [
                     'Decide first whether you will ever need this account again. If yes, use a real alias you control, not a public temp inbox.',
                     'Open the disposable inbox on shehanly.com. Confirm the URL. Copy the generated address once.',
                     'Paste it into the signup form. Do not reuse that address on a second site.',
                     'Stay on the inbox tab until the message arrives. Most verification mails land in under a minute.',
                     'Copy the code or click the confirm link from the message body. Do not forward the raw mail to your real inbox unless you trust the sender.',
                     'Close the tab when you are done. The address will expire. Treat it as gone.',
                 ]],
                 ['link' => ['href' => '/temp-mail', 'text' => 'Generate a disposable address now']],
                 ['h2' => 'When a throwaway address is the wrong tool'],
                 ['ul' => [
                     'Bank, tax, government, health, and employer accounts. Those inboxes have to survive.',
                     'Any service that will email a password reset later. A dead inbox is a locked account.',
                     'Purchases, invoices, and shipping updates. You need a record, not a ten-minute window.',
                     'Accounts you might recover on a new phone. Recovery mail is not optional.',
                     'Anything you would be embarrassed to see on a shared or public inbox stream.',
                 ]],
                 'If the site is worth keeping, create a real plus-address or a dedicated alias on a provider you own. Disposable mail is for the form you never want to hear from again.',
                 ['h2' => 'What a temp-mail tool must never do'],
                 ['ul' => [
                     'It must not let you send mail. Receive-only keeps the product off spam blocklists and off your conscience.',
                     'It must not publish a live public feed of every incoming message. That turns your verification code into a shared secret.',
                     'It must not ask for your real email as a backup. That defeats the point.',
                     'It must not keep the inbox after you close the tab unless you explicitly extended it.',
                     'It must not expose the upstream API key or your IP to the mail provider if a proxy can hide both.',
                 ]],
                 'A fast test: open the tool, start the inbox, watch the Network tab. You should see requests only to the site you opened, not to a third-party mail brand in the browser.',
                 ['h2' => 'Verification codes, magic links, and what to copy'],
                 'Most one-time signups send either a six-digit code or a confirm link. Copy the code. For a link, check the domain before you click. A disposable inbox is a magnet for phishing that looks like the brand you just typed.',
                 'If the mail never arrives, the usual causes are a full ten-minute window, a provider that blocks known disposable domains, or a form that silently rejects the address. Some banks and big SaaS products keep a blocklist. That is a signal: they expect a durable inbox, so give them one.',
                 ['h2' => 'Pair it with the rest of the privacy stack'],
                 'A throwaway inbox stops the email leak. It does not stop a password leak. Generate the password in the browser, store it in a manager you control, and never reuse it on the throwaway signup.',
                 ['link' => ['href' => '/password-generator', 'text' => 'Generate a strong password in the browser']],
                 ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
                 ['h2' => 'Why this post sits next to the tool'],
                 'People search disposable email because a form is blocking them and they do not want another newsletter. The honest page tells them when a 10-minute inbox is enough, when it will lock them out later, and then hands them the generator. That is the Shehanly pattern: rank for the job, teach the risk, finish the job.',
                 ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'Decode a JWT in the browser without leaking the token']],
                 ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']]
             ],
             'faq' => [
                 ['How long does a Shehanly disposable inbox last?', 'Ten minutes by default. You can extend it by another ten minutes while the tab stays open. When the window ends, the address is gone.'],
                 ['Can I send mail from the temporary address?', 'No. The tool is receive-only on purpose. A public send button turns a privacy utility into a spam cannon.'],
                 ['Should I use temp mail for my main accounts?', 'No. Use it for one-time signups you do not plan to recover. Password resets, invoices and 2FA belong in an inbox you still own next year.'],
                 ['Why does the site proxy the mailbox?', 'So the upstream mail provider sees the server, not your browser IP, and so no API key is ever shipped to the page.'],
             ],
         ],
         'jwt-decoder-guide' => [
             'slug' => 'jwt-decoder-guide',
             'category' => 'Guides',
             'type' => 'page',
             'nav' => 'JWT Decoder Guide',
             'published' => '2026-08-30',
             'title' => 'How to Decode a JWT in Your Browser Without Leaking the Token (2026)',
             'h1' => 'How to decode a JWT in your browser without leaking the token',
             'description' => 'A 2026 guide to inspecting JSON Web Token headers, payloads and expiry dates in your browser. Learn what a decoder should never do, why you must not paste a signing secret, and how to spot an expired session locally.',
             'keywords' => 'jwt decoder online, decode json web token, jwt payload inspector, jwt expiry check, private jwt debugger, shehanly',
             'intro' => 'A JWT is a session in three parts. The moment you paste it into a random debugger, you have handed someone else a live login. This guide shows how to read the header and payload in the tab, check expiry, and keep the signing key off the page.',
             'body' => [
                 'Last updated: 30 August 2026. Written for developers, testers and anyone who just got a 401 and needs to see what is inside the token without sending it to a stranger.',
                 ['h2' => 'What a JWT actually is'],
                 'A JSON Web Token is three Base64URL segments split by dots: header, payload, signature. The first two are readable by anyone who has the string. The third proves the first two were not edited, but only if you already hold the secret or public key. Decoding is not verifying. Those are different jobs.',
                 'The header names the algorithm. The payload carries claims such as sub, iss, aud, iat, nbf and exp. The signature is a blob. If you can read the payload in a decoder, so can anyone who intercepted the token. Treat the whole string like a password that expires.',
                 ['h2' => 'Why most online JWT debuggers are a bad idea'],
                 'Plenty of JWT debugger sites look convenient. Some send the token to a server so they can verify it. Some ask you to paste the HMAC secret or a private key into the same form. That is how a support session becomes a stolen session.',
                 'A token pasted into a third-party page can be logged, cached, or replayed against your API until exp hits. A signing secret pasted into the same box is worse: it lets someone mint new tokens, not just read one.',
                 ['h2' => 'The safe pattern: decode in the tab, never verify with a secret on a website'],
                 'Shehanly splits the JWT on the client, Base64URL-decodes the header and payload, and renders registered claims as local dates. There is no network request. There is no verify button that asks for a key. If you need to verify a signature, do it in your own backend or a local CLI you control.',
                 ['link' => ['href' => '/jwt-decoder', 'text' => 'Open the browser JWT decoder']],
                 ['h2' => 'A 60-second workflow when an API returns 401'],
                 ['ul' => [
                     'Copy the token from the Authorization header or from localStorage. Do not paste it into Slack, email or a ticket unless it is already revoked.',
                     'Open the decoder on shehanly.com. Confirm the URL. Paste once.',
                     'Read alg and typ in the header. If alg is none, stop. That token is not signed.',
                     'Check exp, iat and nbf as local times. An expired token is the most common 401. A token that is not valid yet means the clock or nbf is the problem.',
                     'Read aud and iss. A token minted for another app will fail even when it is not expired.',
                     'Close the tab. Do not leave a production access token sitting in a browser field on a shared machine.'
                 ]],
                 ['link' => ['href' => '/jwt-decoder', 'text' => 'Decode the token locally now']],
                 ['h2' => 'What the payload is allowed to tell you'],
                 ['ul' => [
                     'exp is seconds since epoch. If it is in the past, refresh. Do not keep retrying the same string.',
                     'iat tells you when it was minted. A token issued days ago on a short-lived API is a smell.',
                     'nbf means not before. A future nbf looks like an expiry bug and is often a timezone mistake.',
                     'aud and iss tell you whether this token belongs to this API at all.',
                     'Custom claims can hold roles, tenant ids or email. That is still PII. Do not screenshot it into a public channel.'
                 ]],
                 ['h2' => 'What a decoder must never do'],
                 ['ul' => [
                     'It must not send the token to a server for pretty printing. Splitting on dots is a local job.',
                     'It must not ask for a signing secret or a private key. Verification does not belong in a public webpage.',
                     'It must not store tokens in localStorage as a history feature unless you asked for it.',
                     'It must not offer to email you the decoded payload. That is a second copy of a live session.'
                 ]],
                 'A fast test: open the decoder, watch the Network tab, paste a dummy token. If a request fires with the JWT in the body, close the tab.',
                 ['h2' => 'Decode versus verify'],
                 'Decoding answers what this string claims. Verifying answers whether someone you trust signed it. Only verification stops a forged payload. A website that offers both usually wants your secret. Keep verification in your API, your test suite or a local tool.',
                 'If you are debugging an app you own, log the claim set on the server after verification, not the raw token in a public decoder. If you are debugging an app you do not own, you still should not paste a production bearer token into a random site.',
                 ['h2' => 'When the token is not the only problem'],
                 'If the payload looks fine and the API still rejects it, the usual causes are a wrong audience, a clock skew larger than the leeway, a rotated signing key, or an Authorization header that lost the Bearer prefix. Formatting the JSON of the payload on the same machine can help you see a typo in a custom claim.',
                 ['link' => ['href' => '/json-formatter', 'text' => 'Format the payload JSON locally']],
                 ['link' => ['href' => '/base64', 'text' => 'Base64 encode or decode a segment by hand']],
                 ['h2' => 'Why this post sits next to the tool'],
                 'People search jwt decoder because a request failed and they need the claims now. The honest page tells them decoding is local, verification is not a website job, and then hands them the inspector. That is the Shehanly pattern: rank for the job, teach the risk, finish the job.',
                 ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data']],
                 ['link' => ['href' => '/strong-password-guide', 'text' => 'Generate a strong password in the browser']],
                 ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']]
             ],
             'faq' => [
                 ['Does decoding a JWT verify the signature?', 'No. Decoding only reads the header and payload. Verification needs a secret or public key and should happen in software you control, not on a public website.'],
                 ['Is it safe to paste a production access token here?', 'The Shehanly decoder never sends the token to a server. A browser extension or a shared computer can still read the page. Prefer a dummy or already-revoked token when you can.'],
                 ['Why does Shehanly refuse to take my signing secret?', 'Because a signing secret lets anyone mint new tokens. A public webpage is the wrong place to keep that key.'],
             ],
         ],

         'qr-code-guide' => [
             'slug' => 'qr-code-guide',
             'category' => 'Guides',
             'type' => 'page',
             'nav' => 'QR Code Guide',
             'published' => '2026-09-01',
             'title' => 'How to Generate a QR Code Without Uploading Your Data (2026)',
             'h1' => 'How to generate a QR code without uploading your data',
             'description' => 'A 2026 guide to making static QR codes in the browser: when PNG beats SVG, which error-correction level survives print damage, why dynamic QR services track scans, and how to encode a URL or Wi-Fi string without sending it to a stranger.',
             'keywords' => 'qr code generator, free qr code no upload, static qr code, qr png svg download, wifi qr code, private qr generator, shehanly',
             'intro' => 'A QR code is just text drawn as a square. The moment a website asks you to create an account, shortens the URL for you, or promises scan analytics, it is no longer just drawing a square. This guide shows how to generate a static code in the tab, pick the right file format, and keep the payload off someone else\'s server.',
             'body' => [
                 'Last updated: 1 September 2026. Written for small businesses, event organisers, developers and anyone who has watched a free QR site turn a menu link into a tracking pixel.',
                 ['h2' => 'What a QR code actually is'],
                 'A QR code is a 2D barcode. The payload lives in the image. There is no account behind a static code and nothing to expire unless you encoded a short link that you later delete. If the image encodes https://shehanly.com, every scan opens that URL until the domain dies.',
                 'The square can hold a URL, plain text, a phone number, an SMS draft, a mailto, or a Wi-Fi credential string. Capacity depends on version and error correction. A short URL is easy. A 2,000-character dump is a dense, hard-to-scan mess. Keep the payload short.',
                 ['h2' => 'Static versus dynamic, and why most free generators lie'],
                 'A static code stores the real destination in the pixels. A dynamic code stores a short URL that redirects. Dynamic codes are how vendors sell scan counts, edit the destination later, and sometimes shut the code off when you stop paying.',
                 'If the generator forces a signup, shows a dashboard of scans, or gives you a branded short domain you do not control, you are making a dynamic code. Fine for a campaign you want to retarget. Bad for a printed poster that must still work in 2029.',
                 'The other lie is upload-to-render. Some sites send your URL to a server so they can log it, wrap it, or inject a landing page. You typed a private Wi-Fi password. They now have it.',
                 ['h2' => 'The safe pattern: draw the code in the browser'],
                 'Shehanly builds the QR locally with JavaScript. The payload never leaves the tab. There is no account, no short link, no scan log. You pick size, margin, colours and error-correction level, then download a PNG for screens or an SVG for print.',
                 ['link' => ['href' => '/qr-generator', 'text' => 'Open the browser QR code generator']],
                 ['h2' => 'A 60-second workflow for a poster, menu or business card'],
                 ['ul' => [
                     'Decide the exact destination first. Use the final URL, not a tracking redirect you do not own.',
                     'Open the generator on shehanly.com. Confirm the URL. Paste the payload once.',
                     'Start with error correction H if the code will be printed, stickered, or sit under a logo. Use M for a clean digital-only code.',
                     'Keep contrast high. Dark modules on a light background. Do not invert unless you have tested every camera you care about.',
                     'Export SVG for print and cut vinyl. Export PNG for Instagram, WhatsApp and slides.',
                     'Scan the download with your own phone before you send the file to a printer. If your camera hesitates, enlarge the code or shorten the payload.',
                 ]],
                 ['link' => ['href' => '/qr-generator', 'text' => 'Generate the QR code locally now']],
                 ['h2' => 'PNG or SVG'],
                 'PNG is a raster. It looks sharp at the size you exported and turns muddy when a designer stretches it on an A2 board. SVG is a vector. A print shop can scale it to a shopfront without inventing extra pixels.',
                 'Use PNG when the code will only ever live on a screen. Use SVG when ink is involved. If a printer asks for 300 DPI, give them the SVG and let their RIP do the work. Do not screenshot the page.',
                 ['h2' => 'Error correction is not decoration'],
                 ['ul' => [
                     'L recovers about 7 percent damage. Fine for a huge code on a clean screen.',
                     'M recovers about 15 percent. A reasonable default for digital shares.',
                     'Q recovers about 25 percent. Use it if the code will sit near a fold or a staple.',
                     'H recovers about 30 percent. Use it for print, outdoor vinyl, and any code that will have a logo in the centre.',
                 ]],
                 'Higher correction makes a denser code. If the square looks like noise, the payload is too long or the print size is too small. Shorten the URL before you drop the correction level.',
                 ['h2' => 'What you should encode, and what you should not'],
                 ['ul' => [
                     'A stable https URL you control. Best default.',
                     'A Wi-Fi string only if the network is a guest SSID you are happy to publish on a wall.',
                     'A tel: or mailto: for a card, if that number and inbox are meant to be public.',
                     'Do not encode a live access token, an API key, a one-time password, or an admin login.',
                     'Do not encode a document you would not tape to the same wall.',
                 ]],
                 'A QR code is public the moment it is printed. Treat the payload like a billboard.',
                 ['h2' => 'What a QR generator must never do'],
                 ['ul' => [
                     'It must not send the payload to a server to draw a few black squares.',
                     'It must not wrap your URL in a short link you cannot export or self-host.',
                     'It must not require an account to download a watermark-free file.',
                     'It must not expire a static code. Static codes do not expire. If a vendor says yours will, they redirected you.',
                     'It must not hide the real destination behind a consent or ads interstitial.',
                 ]],
                 'A fast test: generate a code for https://example.com, download it, and decode it with your camera. If the phone opens a different domain first, you were wrapped.',
                 ['h2' => 'Print size, quiet zone, and why cheap stickers fail'],
                 'Leave a quiet zone around the square. That empty margin is part of the spec. Cropping it to the modules is how menus stop scanning at lunch rush.',
                 'On a business card, the code should be at least 2 cm across after the margin. On a poster viewed from two metres, go larger. Test under the real lighting. Restaurant yellow bulbs and shopfront glare kill low-contrast codes.',
                 ['h2' => 'Pair it with the rest of the stack'],
                 'If the QR points at a page that collects an email, do not force a real inbox for a one-off download. If the landing page needs a password, generate that password in the browser too.',
                 ['link' => ['href' => '/temp-mail-guide', 'text' => 'Use a disposable inbox for one-time signups']],
                 ['link' => ['href' => '/strong-password-guide', 'text' => 'Generate a strong password in the browser']],
                 ['link' => ['href' => '/barcode-generator', 'text' => 'Need a 1D barcode for a shelf label instead?']],
                 ['h2' => 'Why this post sits next to the tool'],
                 'People search qr code generator because they have a URL and a print deadline. The honest page tells them static beats rented redirects, SVG beats a screenshot, and then hands them the generator. That is the Shehanly pattern: rank for the job, teach the risk, finish the job.',
                 ['link' => ['href' => '/qr-generator', 'text' => 'Create a watermark-free QR code']],
                 ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']]
             ],
             'faq' => [
                 ['Do Shehanly QR codes expire?', 'No. They are static. The destination is encoded in the image. The code works as long as that destination still exists.'],
                 ['Can I see how many people scanned my code?', 'Not from a static image. Scan counts require a redirect you control. If you need analytics, use your own short domain, not a rented QR dashboard.'],
                 ['Is my URL uploaded?', 'No. The Shehanly generator draws the code in your browser. Watch the Network tab while you type. You should not see the payload leave the page.'],
                 ['PNG or SVG for a restaurant menu?', 'SVG. Menus get reprinted and resized. A vector file stays sharp. Scan the proof before you send 200 copies to the printer.'],
             ],
         ],
];
