<?php
/** 3 Oct 2026 post. Loaded after pages-sept21.php so the blog index and this article win. */
return [
    'blog' => [
        'slug' => 'blog',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Blog',
        'title' => 'Shehanly Blog - Privacy-First Tools, Security & Everyday Workflows',
        'h1' => 'The Shehanly blog',
        'description' => 'Practical guides on using free online tools without leaking data, converting documents safely, generating strong passwords and working faster with developer utilities.',
        'keywords' => 'shehanly blog, private online tools, free developer tools guides, password security, pdf converter safety, jwt decoder, disposable email, base64 encode decode, paste audit, client side tools, clipboard hygiene, shared laptop hygiene, redact before convert',
        'intro' => 'Short, practical articles from the builder of Shehanly. No fluff. Each post solves one problem and points you at the free tool that does the work.',
        'body' => [
            ['h2' => 'Latest posts'],
            'New writing ships here first. Every article is written to rank, to teach, and to send you back into a tool you can actually use.',
            ['link' => ['href' => '/redact-before-convert-guide', 'text' => 'How to redact a PDF or Word file before you convert it online (3 Oct 2026)']],
            ['link' => ['href' => '/shared-laptop-hygiene-guide', 'text' => 'How to leave no files, no history and no secrets on a shared laptop after you use a tool (21 Sep 2026)']],
            ['link' => ['href' => '/clipboard-hygiene-guide', 'text' => 'How to keep tokens and passwords out of clipboard history after you use a tool (20 Sep 2026)']],
            ['link' => ['href' => '/prove-client-side-tool-guide', 'text' => 'How to prove an online tool stayed in your browser before you paste (19 Sep 2026)']],
            ['link' => ['href' => '/paste-audit-guide', 'text' => 'How to audit what you paste into online tools before you hit submit (18 Sep 2026)']],
            ['link' => ['href' => '/wifi-qr-code-guide', 'text' => 'How to generate a Wi-Fi QR code without uploading the network password (17 Sep 2026)']],
            ['link' => ['href' => '/base64-is-not-encryption-guide', 'text' => 'Base64 is not encryption: how to decode a blob without leaking it (16 Sep 2026)']],
            ['link' => ['href' => '/verify-download-hash-guide', 'text' => 'How to verify a downloaded file with SHA-256 before you run it (15 Sep 2026)']],
            ['link' => ['href' => '/phishing-url-check-guide', 'text' => 'How to decode a suspicious URL without visiting it (14 Sep 2026)']],
            ['link' => ['href' => '/client-file-workflow-guide', 'text' => 'How to process a client file online without leaking it (13 Sep 2026)']],
            ['link' => ['href' => '/browser-only-tools-guide', 'text' => 'Which Shehanly tools stay in your browser, and which ones do not (12 Sep 2026)']],
            ['link' => ['href' => '/code-explainer-guide', 'text' => 'How to explain code online without leaking your source (11 Sep 2026)']],
            ['link' => ['href' => '/text-summarizer-guide', 'text' => 'How to summarize an article online without creating an account (10 Sep 2026)']],
            ['link' => ['href' => '/word-counter-guide', 'text' => 'How to count words and reading time without uploading your draft (9 Sep 2026)']],
            ['link' => ['href' => '/barcode-generator-guide', 'text' => 'How to generate a barcode without uploading your product data (8 Sep 2026)']],
            ['link' => ['href' => '/ip-dns-lookup-guide', 'text' => 'How to look up DNS and IP data without leaking the domain you are investigating (7 Sep 2026)']],
            ['link' => ['href' => '/url-encoder-guide', 'text' => 'How to URL encode and decode without leaking the query string (6 Sep 2026)']],
            ['link' => ['href' => '/base64-guide', 'text' => 'How to encode and decode Base64 without uploading the payload (5 Sep 2026)']],
            ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'How to convert Word to PDF online without leaking the document (4 Sep 2026)']],
            ['link' => ['href' => '/json-formatter-guide', 'text' => 'How to format and validate JSON without sending the payload (3 Sep 2026)']],
            ['link' => ['href' => '/hash-generator-guide', 'text' => 'How to generate MD5 and SHA-256 hashes without uploading the file (2 Sep 2026)']],
            ['link' => ['href' => '/qr-code-guide', 'text' => 'How to generate a QR code without uploading your data (1 Sep 2026)']],
            ['link' => ['href' => '/temp-mail-guide', 'text' => 'How to use a disposable email without leaking your real inbox (31 Aug 2026)']],
            ['link' => ['href' => '/jwt-decoder-guide', 'text' => 'How to decode a JWT in your browser without leaking the token (30 Aug 2026)']],
            ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How to convert a PDF to Word online without leaking the file (29 Aug 2026)']],
            ['link' => ['href' => '/strong-password-guide', 'text' => 'How to generate a strong password in your browser (27 Aug 2026)']],
            ['link' => ['href' => '/private-online-tools-guide', 'text' => 'How to use free online tools without giving away your data (26 Aug 2026)']],
            ['link' => ['href' => '/education-guides', 'text' => 'Education guides: Excel, Word, PowerPoint and defensive security literacy']],
            'Want a topic covered next? Use the Contact page and say exactly what you were trying to do when a random tool site made you hesitate.',
        ],
        'faq' => [
            ['How often is the blog updated?', 'New posts go up when there is a real problem worth solving, not on a fake daily calendar.'],
            ['Are these posts sales pages?', 'No. The tools stay free. The writing exists to teach and to earn search traffic the honest way.'],
        ],
    ],
    'redact-before-convert-guide' => [
        'slug' => 'redact-before-convert-guide',
        'category' => 'Guides',
        'type' => 'page',
        'nav' => 'Redact Before Convert',
        'published' => '2026-10-03',
        'title' => 'How to Redact a PDF or Word File Before You Convert It Online (2026)',
        'h1' => 'How to redact a PDF or Word file before you convert it online',
        'description' => 'A 2026 checklist for freelancers and small teams: strip names, prices, IDs and hidden metadata from a PDF or DOCX before a free converter ever sees the file. Defensive hygiene only.',
        'keywords' => 'redact pdf before convert, remove metadata word before upload, pdf to word privacy, strip author name docx, black box is not redaction, shehanly redact guide, client file converter safety',
        'intro' => 'The converter is not the leak. The unredacted file is. A black rectangle in Preview does not delete the text under it, and Word still carries your name in the properties pane. Strip the document first, then convert.',
        'body' => [
            'Last updated: 3 October 2026. Written for freelancers, students and small teams who need a PDF as an editable Word file, or a DOCX as a PDF, and do not want the client name, the quote, or their own author field riding along. This is defensive document hygiene. It is not a guide to forging records or hiding evidence.',
            ['h2' => 'Why conversion is the wrong moment to discover secrets'],
            'PDF to Word and Word to PDF have to read the file. On Shehanly that read happens through a short-lived PHP proxy, the upload is unlinked, and no account is required. That still means the bytes existed on a server for the length of the job.',
            'If the file still contains a passport number, a bank line, a client email, or a tracked-change comment that says "do not send this price", the converter did its job and you did not do yours.',
            'Redact on a machine you control. Convert the redacted copy. Delete both the upload and the download when you are done.',
            ['link' => ['href' => '/pdf-to-word-guide', 'text' => 'How to convert a PDF to Word without leaking the file']],
            ['link' => ['href' => '/word-to-pdf-guide', 'text' => 'How to convert Word to PDF without leaking the document']],
            ['link' => ['href' => '/client-file-workflow-guide', 'text' => 'How to process a client file online without leaking it']],
            ['h2' => 'A black box is not redaction'],
            'Drawing a rectangle over a sentence in Preview, Photos, or a markup tool hides the pixels. Select-all in the PDF still copies the sentence. A converter that extracts text will pull the sentence back out and put it in the Word file in plain sight.',
            ['ul' => [
                'Real redaction removes the text from the content stream, not just the paint on top.',
                'In Adobe Acrobat, use the Redact tool, apply redactions, then save a new file. Do not export the marked-up original.',
                'In Word, delete the sentence. Do not change the font color to white. White text converts back to black text.',
                'Flatten only after the text is gone. Flattening a highlight does not delete the underlying characters.',
            ]],
            'If you cannot truly redact, do not convert that page. Export a page range that never contained the secret, or retype the safe paragraphs into a fresh document.',
            ['h2' => 'What to strip before the upload'],
            ['ul' => [
                'Names, emails, phone numbers, national IDs, account numbers, and addresses that the recipient does not already have.',
                'Prices, margins, and internal comments if the output is going to a client.',
                'Tracked changes and comments in Word. Accept or reject them, then delete the comments. Conversion loves to resurrect a comment thread.',
                'Hidden text, white text, headers, footers, and text boxes on the master page.',
                'The author, company, and last-modified-by fields in File, Info, Properties.',
            ]],
            'On Word for Microsoft 365: File, Info, Check for Issues, Inspect Document. Remove document properties and personal information, then save a copy with a boring name like draft-redacted.docx.',
            'On macOS Preview, markup is not enough. If the PDF is the source of truth, redact in a tool that deletes text, or rebuild the safe pages in Word and convert that.',
            ['h2' => 'Metadata survives a pretty export'],
            'A DOCX is a zip of XML. The author string lives in docProps/core.xml even when the first page looks clean. A PDF info dictionary can still say Creator, Author, and the full path of the machine that printed it.',
            ['ul' => [
                'Save As a new file after you inspect. Do not overwrite the signed original.',
                'Rename to something that is not the client name. Acme-payroll-September.pdf is a label.',
                'Print to PDF from a redacted Word file if you need a flat copy and you have already removed the properties.',
                'Hash the redacted file in the browser so you can prove later which bytes you converted.',
            ]],
            ['link' => ['href' => '/hash-generator', 'text' => 'Hash the redacted file in your browser']],
            ['link' => ['href' => '/verify-download-hash-guide', 'text' => 'How to verify a download with SHA-256']],
            ['h2' => 'A five-minute redaction pass'],
            ['ul' => [
                'Duplicate the file. Never redact the only copy of a contract.',
                'Search the document for @, phone patterns, currency symbols, and the client name.',
                'Kill comments, tracked changes, and hidden text.',
                'Inspect properties and remove author data.',
                'Export or save the redacted copy under a neutral filename.',
                'Open the redacted PDF and try to select the covered area. If text still copies, it is not redacted.',
                'Only then open the converter.',
            ]],
            ['link' => ['href' => '/pdf-to-word', 'text' => 'PDF to Word converter']],
            ['link' => ['href' => '/word-to-pdf', 'text' => 'Word to PDF converter']],
            ['h2' => 'After the convert'],
            'The output can reintroduce structure you thought was gone: a comment that became a paragraph, a header that repeated on every page, an alt text string on an image.',
            ['ul' => [
                'Search the Word result for the same names and numbers before you send it.',
                'Delete the upload and the download from the machine you used. Empty Trash.',
                'Overwrite the clipboard if you copied a paragraph that still had an email in it.',
                'Do not run the same file through a second random converter "to compare quality". That is a second copy.',
            ]],
            ['link' => ['href' => '/clipboard-hygiene-guide', 'text' => 'Overwrite the clipboard after the copy']],
            ['link' => ['href' => '/shared-laptop-hygiene-guide', 'text' => 'Close out a shared laptop after the download']],
            ['h2' => 'What never belongs in a free converter'],
            ['ul' => [
                'Live identity documents, full medical records, unsigned settlement numbers, production credentials.',
                'A file whose NDA forbids any third-party processor. Hygiene does not rewrite the contract.',
                'A scan you have not opened. Convert a dummy page first if you are on an unfamiliar tool.',
            ]],
            'Nine Shehanly tools never upload. Use those when the job is a hash, a password, a JWT decode, or a JSON format. Use the converters only for the redacted document.',
            ['link' => ['href' => '/browser-only-tools-guide', 'text' => 'Which tools stay in the browser']],
            ['link' => ['href' => '/password-generator', 'text' => 'Generate a password without an account']],
            ['link' => ['href' => '/jwt-decoder', 'text' => 'Decode a JWT in the tab']],
            ['h2' => 'Why this post sits next to the tools'],
            'People search pdf to word because a client sent a file they cannot edit. The useful page does not pretend the upload never happened. It tells them to kill the secrets first, name the file something boring, convert once, and check the output. That is the Shehanly pattern. Rank for the task. Prove the path. Leave less data behind than you started with.',
            ['link' => ['href' => '/', 'text' => 'Open the 15 free tools']],
            ['link' => ['href' => '/blog', 'text' => 'Back to the blog index']],
        ],
        'faq' => [
            ['Does highlighting text in Preview redact a PDF?', 'No. A highlight or black box hides pixels. The text is usually still selectable and a converter will extract it into the Word file.'],
            ['Does Shehanly keep my PDF after conversion?', 'No. The converter proxies the upload through PHP and unlinks it. Redact before that hop anyway, because the bytes still exist for the length of the job.'],
            ['Will Word to PDF remove my author name?', 'Not by itself. Inspect Document, remove properties, save a new file, then convert that copy.'],
            ['Can I convert only the safe pages?', 'Yes. Export a page range that never contained the secret, or paste the safe paragraphs into a fresh document and convert that.'],
            ['Is white text a redaction?', 'No. White font converts back to visible text. Delete the sentence.'],
        ],
    ],
];
